"""Describe native FDS file buffers and fixed-size save slots in Japanese and English."""
from pathlib import Path
import hashlib,json
HERE=Path(__file__).resolve().parent;SITE=HERE.parents[1];REPOS=SITE.parents[1]/'publish/github_20260912'
if not REPOS.is_dir():REPOS=SITE.parent
texts={};contracts={};sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def msg(key,ja,en):
 key='fds_file_'+key;texts[key]=dict(ja=ja,en=en);return key
native=msg('native','`--mapper=fds --fds-layout=fds32`用です。`--fds-meta`でファイルのID、ロード先、種類、起動時に読むかどうか、配置順を指定します。転送先とサイズは、実際に生成したディスクの情報から決まります。挿入した任意のディスクの内容を調べるAPIではありません。','Use with `--mapper=fds --fds-layout=fds32`. The `--fds-meta` manifest defines file IDs, load addresses, types, boot status and ordering. Transfer addresses and sizes come from the disk image produced by the build; this API does not inspect an arbitrary inserted disk.')
buffers=msg('buffers','CPUバッファは、全体が$0200～$07FFまたは$6000～$DFFFの一方に収まる必要があります。範囲の折り返しやI/Oレジスタへの転送は拒否します。ただし、コード・OAM・他の変数・コンパイラの作業領域と重ならないことは呼び出し側で保証してください。サンプルは共通コードをバンク0に置き、$8000を一時ロード先、$8500と$8600を4バイトのバッファとして使います。','Each CPU buffer must fit entirely within either $0200–$07FF or $6000–$DFFF. Wrapping spans and I/O-register destinations are rejected. The caller must still keep these buffers clear of code, OAM, other variables and compiler scratch storage. The sample uses bank 0 for common code, $8000 for staging, and four-byte buffers at $8500 and $8600.')
blocking=msg('blocking','同期式のBIOS呼び出しです。実行中のコードや復帰先をロードで上書きしないよう共通バンクから呼んでください。割り込み内からは呼べません。ディスクI/O中は描画とNMIを停止し、PPUのアドレス増分を1にし、ディスク以外のIRQ源を停止するなど、BIOSの前提を満たす必要があります。転送中にゲームや音楽の処理が継続することは保証しません。','These are synchronous BIOS calls. Call from common code so the transfer cannot overwrite the executing code or its return address; do not call from an interrupt handler. Satisfy BIOS prerequisites during disk I/O: stop rendering and NMI, use a PPU address increment of one, and disable non-disk IRQ sources. Continued gameplay or music during the transfer is not guaranteed.')
boundary=msg('boundary','掲載画像は独自作成のBIOS呼び出し規約テストで、コンパイル後のCPU処理、バッファ内容、保存後の再読み込み、全画素を確認したものです。実際のBIOSや物理ディスクの書き込み、CRC、電源断時の復旧を確認した画像ではありません。KUROSAKIの通常のFDS実行だけでは同じ保存処理を検証できません。','The capture uses an original BIOS calling-convention fixture to check compiled CPU code, buffer contents, save/readback behavior and every display pixel. It does not verify the real BIOS, physical disk writes, CRC or recovery after power loss. Ordinary FDS execution in KUROSAKI alone does not establish the same save behavior.')
fixture=msg('fixture','サンプル本体に加え、同じフォルダーの`fds_file_io_manifest.json`と`fds_file_io_payload.bin`を使います。下記の検証コマンドは、テスト用処理を独自のソースから一時生成して実行後に削除します。市販BIOSを配布物に含めたり、通常のゲーム用BIOSとしてこの検証処理を使ったりするものではありません。','Use the sample together with `fds_file_io_manifest.json` and `fds_file_io_payload.bin` from the same folder. The checker below generates a temporary fixture from original source and removes it afterward. No commercial BIOS is included, and this fixture is not a BIOS for normal games.')
idarg=msg('id','生成するディスクに含まれる、起動時に読まないファイルのID（0～254）。サンプルは73です。ディスク上で何番目に並ぶかを表す番号とは異なります。255、見つからないID、起動用ファイルは拒否します。','ID of a non-boot file included in the generated disk, 0..254; the sample uses 73. This is distinct from the file’s physical position. ID 255, absent IDs and boot files are rejected.')
expected=msg('expected','LOAD・SAVE・RELOADのSTATUSとBYTE CHECK ERRORSはすべて000です。INITIAL FIRST/LASTの011と044は、$8500へ読み込んだ4バイトの最初と最後です。内容を7・14・21・28へ変えて保存し、別の$8600へ読み直すため、SAVED FIRST / LASTは007と028になります。STAGING 8000 / SIZE 4はディスク側のロード先とファイル長です。独自テストでは、ID 73を実際の4番目のファイル（0起点の位置3）へ保存したことも確認しています。','LOAD, SAVE and RELOAD STATUS and BYTE CHECK ERRORS all show 000. INITIAL FIRST/LAST shows 011 and 044, the endpoints of the four bytes loaded into $8500. The sample changes them to 7, 14, 21 and 28, saves them, then reloads into $8600, so SAVED FIRST / LAST shows 007 and 028. STAGING 8000 / SIZE 4 identifies the disk-side load address and file length. The independent test also checks that ID 73 is saved at the actual fourth file, zero-based position 3.')
records={r['name']:r for r in json.loads((SITE/'reference/fc-api.json').read_text())['records']}
program='samples/api-examples/fc/fds_file_io.c';src=(SITE/program).read_text();code=src[src.index('#pragma'):].strip()
build='New-Item -ItemType Directory -Force .\\out | Out-Null\n.\\kitaqfc\\kitaqfc.exe .\\kitaq-docs\\samples\\api-examples\\fc\\fds_file_io.c -I .\\kitaqfc\\lib -I .\\kitaq-docs\\samples -o .\\out\\fds_file_io.fds --mapper=fds --fds-layout=fds32 --fds-no-license-bypass --fds-meta=.\\kitaq-docs\\samples\\api-examples\\fc\\fds_file_io_manifest.json --nes-chr=.\\kitaq-docs\\samples\\font.chr --no-cache --no-disasm\npython .\\kitaq-docs\\tools\\check_fds_file_examples.py'
def add(name,purpose,args,returns,notes):
 r=records[name];fp=hashlib.sha256(json.dumps({k:r.get(k) for k in ['name','signature','comment','definition','implementation_excerpt']},sort_keys=True).encode()).hexdigest()
 contracts['fc:'+name]=dict(review='fds-file-source-20260923',record_sha256=fp,purpose=[purpose],args=args,returns=[returns],notes=[native]+notes+[buffers,blocking,boundary,fixture],references=[dict(url='https://www.nesdev.org/wiki/FDS_BIOS',title='FDS BIOS calling convention')],example=dict(program=program,code=code,build=build,expected=[expected],files=['samples/api-examples/fc/fds_file_io_manifest.json','samples/api-examples/fc/fds_file_io_payload.bin']))
add('__fds_load_file',msg('load_purpose','ファイルをBIOSで読み込み、PRGデータを指定したCPUバッファへコピーします。セーブデータやステージデータを、ゲーム側で確保した領域へ取り込むための関数です。','Read a file through the BIOS and copy its PRG data into a CPU buffer. Use it to bring save data or level assets into memory reserved by the game.'),[['id',[idarg]],['dst',[msg('dst','PRGファイルのコピー先。実際のファイル長以上の領域が必要です。0を渡すとコピーせず、ファイルヘッダーのロード先に残します。CHR・ネームテーブルのPPUファイルは0のみ指定でき、BIOSが本来のPPU宛先へ転送します。','Destination for a PRG file, with space for its complete packaged length. Pass zero to leave the data at its header-defined destination without copying. For CHR/nametable PPU files, only zero is accepted; the BIOS transfers to the native PPU destination.')]]],msg('load_return','成功は0。BIOSの非ゼロエラーはそのまま返します。BIOSが成功を返しても転送数が1でなければ64（$40）、無効なID・バッファ・ファイル種別と宛先の組み合わせは255（$FF）です。','Zero on success. Nonzero BIOS errors are returned unchanged. A nominally successful BIOS call that did not load exactly one file returns 64 ($40). Invalid IDs, buffers or file-type/destination combinations return 255 ($FF).'),[msg('staging','BIOSのロード先はディスクのヘッダーで決まるため、先にその領域へ読み込み、その後dstへコピーします。二つの領域が重なってもコピー方向を選んで内容を保持しますが、一時ロード先自体の確保も必要です。転送失敗時はコピーを行いません。BIOS呼び出し後はバンク常駐記録を255（不明）にします。','The BIOS first loads into the address stored in the disk header, then this helper copies to dst. It selects the copy direction to preserve overlapping data, but the staging area must also be reserved. A failed transfer does not copy to dst. After a BIOS call, bank residency is marked 255 (unknown).')])
add('__fds_save_file',msg('save_purpose','あらかじめディスクの最後に確保した固定長のPRGセーブ領域を、CPUバッファの内容で上書きします。ファイルのID・名前・次回のロード先を保持します。','Overwrite a fixed-size PRG save slot reserved at the end of a disk side with bytes from a CPU buffer. The file keeps its ID, name and future load address.'),[['id',[idarg]],['src',[msg('src','保存するデータのCPU RAM上の先頭。lenバイトを読み出せる領域を渡します。VRAMを直接保存するAPIではありません。','Start of the data in CPU RAM, readable for len bytes. This API does not save VRAM directly.')]],['len',[msg('len','保存するバイト数。生成済みファイルの実際の長さと一致させてください。データが短いときは、保存用バッファの残りをゲーム側で埋めます。','Number of bytes to save; it must equal the packaged file length. If the game has less data, fill the unused part of its save buffer before calling.')]]],msg('save_return','成功は0、BIOSが返す書き込み保護・検証失敗などのエラーはその値です。無効なID、起動用またはPRG以外のファイル、同じ面で最後に並ばないファイル、長さの不一致、無効なCPU範囲は255（$FF）を返し、BIOSを呼びません。','Zero on success, otherwise the BIOS error such as write protection or write-verification failure. Returns 255 ($FF) without calling the BIOS for an invalid ID, a boot or non-PRG file, a file that is not last on its side, a length mismatch or an invalid CPU span.'),[msg('slot','BIOSのWriteFileは書き込む位置より後のファイルを論理的に隠すため、このAPIでは各面の最後にある非起動PRGファイルだけを保存対象にします。新規ファイルの追加や任意の長さへの変更は行いません。起動補助ファイルや自動オーバーレイも含め、最終配置で最後になっている必要があります。','BIOS WriteFile logically hides files following the write position. This API therefore accepts only the final non-boot PRG file on each side. It does not append a new file or resize a slot. The slot must be last in the final layout, including generated boot helpers and automatic overlays.'),msg('ordering','コンパイラはファイルID、ヘッダーのnumber、物理的な並び順を区別します。サンプルのIDは73、管理表のnumberは200ですが、BIOSへ渡す位置は3です。ディスク番号・面番号も配置から設定します。マニフェストと異なる構成に改変したディスクでは使わないでください。','The compiler distinguishes file ID, the header number and physical order. The sample has ID 73 and manifest number 200, but passes position 3 to the BIOS. Disk and side numbers also come from the resolved layout. Do not use this with a disk whose layout has been changed independently of the manifest.')])
review=dict(source_sha256={p:sha(REPOS/p) for p in ['kitaqfc/kitaqfc/CodeGenerator.cs','kitaqfc/kitaqfc/BankedAssemblerCore.cs','kitaqfc/kitaqfc/FdsDiskImageBuilder.cs','kitaqfc/lib/fds_file.h','kitaqfc/lib/intrinsics.h']})
for name,value in [('fds_file_contracts.json',contracts),('fds_file_texts.json',texts),('fds_file_review_sources.json',review)]:
 (HERE/name).write_text(json.dumps(value,ensure_ascii=False,indent=2),encoding='utf-8')
print('Authored two FDS file-I/O contracts in JA/EN.')
