"""Author the three sprite-zero synchronization APIs from their emitted code."""
from pathlib import Path
import hashlib,json
HERE=Path(__file__).resolve().parent;SITE=HERE.parents[1];REPOS=SITE.parents[1]/'publish/github_20260912'
if not REPOS.is_dir():REPOS=SITE.parent
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
texts={};contracts={}
def msg(key,ja,en):
 key='sprite0_'+key;texts[key]={'ja':ja,'en':en};return key
none=msg('none','戻り値はありません。','No return value.')
hit=msg('hit','OAMの0番スプライトと背景の不透明なピクセルを重ねます。背景・スプライトの描画を両方有効にしてください。スプライトの「背景の後ろ」属性を付けてもヒットします。左端8ピクセルは該当する表示許可が必要で、X=255の重なりはヒットしません。','Overlap an opaque pixel of OAM sprite 0 with an opaque background pixel, with both layers enabled. The behind-background priority flag still permits a hit. The leftmost eight pixels require the corresponding layer enables; overlap at X=255 cannot trigger a hit.')
poll=msg('poll','PPUSTATUS（$2002）のビット6が0になるまで待ち、続いて1になるまで待ちます。呼び出した時点ですでにヒット済みなら、次のフレームの新しいヒットを待ちます。フラグは読み取りでは解除されず、PPUが次のフレームの準備中に解除します。','Poll PPUSTATUS ($2002) bit 6 until it is clear, then until it is set. If a hit has already occurred when called, wait for a fresh hit in the next frame. Reading the flag does not acknowledge it; the PPU clears it during pre-render.')
blocking=msg('blocking','タイムアウトも失敗の戻り値もありません。0番スプライトが非表示、背景が透明、描画が無効など、重なりが発生しない設定では戻りません。呼ぶ前にヒット条件を保証してください。CPUのIRQ許可は不要で、この関数自身はNMIを有効化しません。サンプルのフレーム待機にはNMIを有効にしています。','There is no timeout or failure return. A hidden sprite 0, transparent background, disabled rendering or another setup without overlap leaves the call blocked. Guarantee a hit before calling. CPU IRQ enable is not required, and this function does not enable NMI. The sample enables NMI for its separate frame wait.')
latch=msg('latch','$2002を読むので、PPUのアドレス／スクロール共有ラッチとVBlankフラグにも影響します。途中まで書いた$2005/$2006の2バイト操作を、この呼び出しを挟んで続けないでください。NMI/IRQハンドラーから呼ばず、前景ループで使います。','Reads of $2002 also affect the shared PPU address/scroll write latch and the VBlank flag. Do not split a two-write $2005/$2006 operation around this call. Use it from the foreground, not from an NMI/IRQ handler.')
xarg=msg('x','横スクロール値0～255。画面内の物体のX座標ではありません。サンプルでは32を指定し、同じ背景の下部を左へ32ピクセル移動して表示します。','Horizontal scroll value, 0..255, not an object’s screen X coordinate. The sample uses 32 to display the lower part of the same background shifted left by 32 pixels.')
yarg=msg('y','縦スクロールの一時設定値0～255。通常の表示範囲は0～239です。このヘルパーは$2005へ書くため、描画中の縦位置を直ちに変更する機能ではありません。横分割のサンプルでは0を渡します。','Temporary vertical scroll setting, 0..255; the usual visible range is 0..239. This helper writes $2005, so it does not immediately change the live vertical position during rendering. The horizontal-split sample passes zero.')
vertical=msg('vertical','ヒット後に$2002を読み、$2005へX、Yの順に書きます。細かいX位置はすぐに変わり、タイル単位のX位置は次の水平再ロードで反映されます。Yは通常、次のプリレンダーで反映されますが、それまでに別のスクロール設定で上書きされることがあります。任意のX/Yへ即座に飛ばすラスタースクロール関数としては使わないでください。','After the hit, read $2002 and write X then Y to $2005. Fine X changes immediately; coarse X takes effect at the next horizontal reload. Y normally takes effect at the next pre-render reload, unless another scroll write replaces it first. This is not an immediate arbitrary-X/Y raster repositioning operation.')
timing=msg('timing','書き込み位置にはポーリングと命令実行の遅れがあります。KUROSAKIは走査線単位で描画するため、実機のドット単位の境界位置をこの画像だけで保証しません。サンプルではY=96～103の白い帯の中に切り替えを収め、境界付近の誤差が青・赤の帯へ出ない構成にしています。','Polling and instruction execution delay the writes. KUROSAKI renders by scanline, so these captures do not establish a dot-exact hardware boundary. The sample places the change inside the white band at Y=96..103, keeping boundary uncertainty away from the blue and red bars.')
scene=msg('scene','共有ヘッダー`fc_sprite0_scene.h`が独自の青・赤の帯と白い横帯を準備します。0番スプライトは画面(16,96)に置き、背景の後ろへ隠しています。OAMのYには表示位置−1の95を指定します。各フレームのVBlankで上部のスクロールを0へ戻してから、ヒットを待ちます。','The shared header `fc_sprite0_scene.h` prepares original blue/red bars and a white horizontal band. Sprite 0 sits at screen (16,96), hidden behind the background; its raw OAM Y is 95 because display Y is OAM Y+1. Each frame restores the top scroll to zero during VBlank before waiting for the hit.')
expected_wait=msg('wait_expected','青い縦帯はX=64～95、赤い縦帯はX=160～191にあり、白い横帯の上下で位置は変わりません。待つだけではスクロールを変更しないことを示します。120フレーム時点で116回、121フレームで117回の待機完了を確認し、次のフレームにも進み続けることを検証しています。','The blue bar occupies X=64..95 and the red bar X=160..191, aligned above and below the white band. Waiting alone does not change scrolling. The executed lesson completes 116 waits after 120 frames and 117 after 121 frames, verifying that it keeps advancing.')
expected_split=msg('split_expected','白い横帯より上では青がX=64～95、赤がX=160～191です。Y=104以降の下部では青がX=32～63、赤がX=128～159になり、下部だけ左へ32ピクセルずれます。横帯はY=96～103、縦帯の下端はY=207です。毎フレーム1回ずつ処理が完了することと、画像全体の色・位置を検証しています。','Above the white band, blue is at X=64..95 and red at X=160..191. Below it, from Y=104 onward, blue moves to X=32..63 and red to X=128..159: only the lower area shifts left by 32 pixels. The horizontal band is at Y=96..103 and the bars end at Y=207. Verification checks one completion per frame and every image pixel’s position and color.')
records={r['name']:r for r in json.loads((SITE/'reference/fc-api.json').read_text(encoding='utf-8'))['records']}
for name,mode,ja,en,expected in [
 ('__sprite0_wait_hit','wait','0番スプライトと背景が新しく重なるまで待ちます。画面内の既知の位置に処理を同期させるための待機で、スクロール値は変更しません。','Wait for a fresh sprite-zero/background overlap, synchronizing foreground work to a known region of the screen without changing scroll values.',expected_wait),
 ('__split_scroll_sprite0','split','0番スプライトの新しいヒットを待ち、横分割用にスクロールX/Yを書き込みます。上部を固定して下部の背景だけ横へずらす用途に使えます。','Wait for a fresh sprite-zero hit and write scroll X/Y for a horizontal split, keeping the top aligned while shifting the lower background.',expected_split),
 ('nes_split_scroll_sprite0','split_alias','`nes_game.h`から使える画面分割マクロです。XとYを1回ずつ`__split_scroll_sprite0`へ渡し、同じ待機とスクロール書き込みを行います。','Screen-split macro from `nes_game.h`. It passes X and Y once each to `__split_scroll_sprite0`, performing the same wait and scroll writes.',expected_split)]:
 r=records[name];program='samples/api-examples/fc/sprite0_'+mode+'.c';source=(SITE/program).read_text(encoding='utf-8')
 code=source[source.index('void main'):].strip()
 fingerprint=hashlib.sha256(json.dumps({k:r.get(k) for k in ['name','signature','comment','definition','implementation_excerpt']},sort_keys=True).encode()).hexdigest()
 build='New-Item -ItemType Directory -Force .\\out | Out-Null\n.\\kitaqfc\\kitaqfc.exe .\\kitaq-docs\\'+program.replace('/','\\')+' -I .\\kitaqfc\\lib -I .\\kitaq-docs\\samples -o .\\out\\sprite0_'+mode+'.nes --mapper=nrom --nes-chr=.\\kitaq-docs\\samples\\sprite0_scene.chr --no-cache --no-disasm'
 contracts['fc:'+name]=dict(review='sprite0-source-20260923',record_sha256=fingerprint,purpose=[msg(mode,ja,en)],args=[] if mode=='wait' else [['x',[xarg]],['y',[yarg]]],returns=[none],notes=[hit,poll,blocking,latch]+([] if mode=='wait' else [vertical])+[timing,scene],references=[dict(title='NESdev: PPU scrolling',url='https://www.nesdev.org/wiki/PPU_scrolling'),dict(title='NESdev: PPU programmer reference',url='https://www.nesdev.org/wiki/PPU_programmer_reference')],example=dict(program=program,code=code,build=build,expected=[expected]))
review={'source_sha256':{p:sha(REPOS/p) for p in ['kitaqfc/kitaqfc/CodeGenerator.cs','kitaqfc/lib/intrinsics.h','kitaqfc/lib/nes_game.h']}}
for name,value in [('sprite0_contracts.json',contracts),('sprite0_texts.json',texts),('sprite0_review_sources.json',review)]:
 (HERE/name).write_text(json.dumps(value,ensure_ascii=False,indent=2),encoding='utf-8')
print('3 sprite-zero contracts authored in JA/EN')
