"""Author distinct Japanese/English contracts for the 25 DMG-07 operations."""
from pathlib import Path
import hashlib,json,re,sys
HERE=Path(__file__).resolve().parent;SITE=HERE.parents[1];REPOS=SITE.parents[1]/'publish/github_20260912'
if not REPOS.exists():REPOS=SITE.parent
sys.path.insert(0,str(SITE/'tools'));import catalog
catalog.ROOT=REPOS
texts={};contracts={};review={};hashes={}
def msg(key,ja,en):
    key='dmg07_'+key;value={'ja':ja,'en':en}
    if key in texts:assert texts[key]==value
    texts[key]=value;return key
def note(key,ja,en):return msg('note_'+key,ja,en)
scope=note('scope','画像はKOKURAのDMG-07モデルで実行した結果です。接続するコンソールは個別に動作し、実際の送受信値を照合しています。実物のアダプターやケーブルの電気的特性・タイミングは未検証です。CGBの数値は青色で表示します。','Screens are captured from KOKURA’s DMG-07 model. Each console executes independently, and transmitted and received values are compared. Physical adapter/cable electrical behavior and timing are unverified. CGB screens display numeric values in blue.')
port=note('port','このドライバーがシリアルポートを専有します。通常のLinkやLink4と同時に動かさず、link_hwregs_gb.cとlink_dmg07.cを1回ずつ組み込みます。外部クロックはアダプターが供給し、CGB専用の高速通信には切り替えません。','This driver owns the serial port. Do not run ordinary Link or Link4 concurrently; include link_hwregs_gb.c and link_dmg07.c once each. The adapter supplies external clocks; the driver does not select CGB fast serial mode.')
poll=note('poll','Pollはフレームの途中でも繰り返し呼び、TickFrameは1フレームにつき1回だけ呼びます。VBlankごとにPollを1回呼ぶだけではバイト間の再設定に間に合いません。共通ヘッダーのd_pollはLYが144以上になった境界を検出してTickFrameを呼びます。両者を割り込みとメイン処理から同時に操作しないでください。','Call Poll repeatedly throughout the frame and TickFrame exactly once per frame. One Poll per VBlank cannot re-arm the port between adapter bytes. The shared header’s d_poll detects entry into LY >= 144 to call TickFrame once. Serialize both operations instead of racing an ISR against the main loop.')
slots=note('slots','ライブラリのプレイヤー番号は1～4、未検出は0です。接続マスクのビット0～3がプレイヤー1～4に対応します。KOKURAの--link-sessionに渡すslotは0～3なので、ROM内の番号と区別します。','Library player numbers are 1..4; zero means undiscovered. Connection-mask bits 0..3 correspond to players 1..4. KOKURA --link-session slot values are 0..3, a separate numbering convention from the ROM API.')
errors=note('errors','エラーは0=なし、1=不正なフェーズ、2=プレイヤー1ではない、3=接続準備不足、4=時間切れ、5=プロトコル不正、6=未読パケットの上書きです。要求の成功は0、受信取得の成功は1です。成功した要求が以前のエラーを消すことはありません。','Error codes are 0=none, 1=wrong phase, 2=not player 1, 3=not ready, 4=timeout, 5=protocol error and 6=unread packet overwritten. Requests succeed with zero; receive/pop operations succeed with one. A successful request does not clear an earlier error.')
pipeline=note('pipeline','SIZE=1で各台が1バイトを提出し、4バイトの配信はプレイヤー1～4の順です。最初の配信は捨て、次の配信から受け取ります。受信内容は1パケット前の提出値です。4バイトすべてが0xFFの配信は再起動通知として予約されています。','With SIZE=1 each console submits one byte; the four-byte broadcast is ordered by players 1..4. The initial broadcast is discarded. Subsequent broadcasts contain the previous packet’s submissions. An all-0xFF four-byte broadcast is reserved as the restart indication.')
mailbox=note('mailbox','受信メールボックスは最新の1パケットだけを保持します。未読のまま次が完成すると新しい内容で上書きし、エラー6とErrorCountを記録します。取り出すまでアダプターが待ってくれるわけではありません。','The receive mailbox holds only the latest packet. Completion of another packet overwrites unread data, latches error 6 and increments ErrorCount. The adapter does not wait for the application to consume the mailbox.')
counters=note('counters','SilenceFramesと診断カウンターは255で止まります。Initはすべて初期化しますが、通常のプロトコル再起動では診断カウンターを保持します。ClearErrorはエラー番号だけを消します。','SilenceFrames and diagnostic counters saturate at 255. Init resets them all; ordinary protocol restarts preserve diagnostic counters. ClearError clears only the error code.')
seq=note('seq','番号は8ビットで255の次は0です。パケット公開時にPacketSequence=SentSequence−1となります。その後も送信が始まるとSentSequenceが進むため、後から読む2つの番号が常に差1になるとは限りません。','Sequence numbers wrap from 255 to zero. At publication, PacketSequence equals SentSequence minus one. Later transmit starts advance SentSequence, so two getters sampled later need not differ by one.')
examples={
 'exchange':('同じROMを4台で動かし、各台が32＋プレイヤー番号を送ります。全台でPLAYER 1～4が33/34/35/36になります。最初の有効な配信でSENT SEQ=2、PACKET SEQ=1を記録し、1パケットの遅延を示します。表示はその時点の観測値を固定したものです。ゲームでは受信後もポーリングを続けます。','Run the same ROM on four consoles, each sending 32 plus its player number. Every console receives PLAYER 1..4 = 33/34/35/36. The first valid broadcast records SENT SEQ=2 and PACKET SEQ=1, showing the one-packet delay. The screen freezes that observation; a game continues polling afterwards.'),
 'absent':('アダプターを接続せずに実行します。PLAYER=0、START ERROR=2、SILENT FRAME=12、TIMEOUTS=1、ERROR=4になります。一度もアダプターを見ていないためDISCONNECTS=0です。空の取得ではEMPTY BUFFER=77を保持し、ClearError後はCLEARED=0になります。','Run without an adapter. Expect PLAYER=0, START ERROR=2, SILENT FRAME=12, TIMEOUTS=1 and ERROR=4. DISCONNECTS stays zero because no adapter has ever been seen. An empty read preserves EMPTY BUFFER=77; ClearError produces CLEARED=0.'),
 'restart':('4台のうちプレイヤー2が再起動を要求します。その台でPENDING=1とSENT FF=1を記録し、全台でDATA VALID=1、RESET PHASE=0、SLOT AFTER=0、RESET PRIME=0になります。要求直後に通信状態を捨てず、アダプターの通知後に探索へ戻ることを確認します。','Player 2 requests restart. That console records PENDING=1 and SENT FF=1. All four show DATA VALID=1, RESET PHASE=0, SLOT AFTER=0 and RESET PRIME=0. The driver preserves the active exchange until the adapter’s indication returns it to discovery.'),
 'overflow':('最初の有効パケットを読まず、次が届くまで待ちます。SENT SEQ=3、PACKET SEQ=2、ERROR=6となり、取得内容は最新の33/34/35/36です。ClearErrorでCLEAR ERROR=0になりますが、ErrorCountは1のままです。','Leave the first valid packet unread until another arrives. Expect SENT SEQ=3, PACKET SEQ=2 and ERROR=6; the read returns the latest 33/34/35/36. ClearError changes CLEAR ERROR to zero while ErrorCount remains one.')}
def build(lesson):
    lines=['New-Item -ItemType Directory -Force .\\out | Out-Null','.\\kitaqgb\\kitaqgb.exe .\\kitaq-docs\\samples\\api-examples\\gb\\dmg07_'+lesson+'.c -I .\\kitaqgb\\lib -I .\\kitaq-docs\\samples -o .\\out\\dmg07_'+lesson+'.gb --profile=dev --rst-disable --stack-bank=fixed --cgb=cgb --cart=mbc5 --romsize=128k --no-cache --no-disasm']
    if lesson=='absent':lines+=['.\\kokura\\kokura-cli.exe .\\out\\dmg07_absent.gb --hardware cgb --run-frames 90 --png .\\out\\absent.png']
    else:
        lines+=['.\\kokura\\kokura-cli.exe --link-topology dmg07 --run-frames 90 '+' '.join('--link-session "name=player'+str(i)+'|slot='+str(i-1)+'|rom=.\\out\\dmg07_'+lesson+'.gb|save_state=.\\out\\player'+str(i)+'.kqs"' for i in range(1,5))]
        for i in range(1,5):lines+=['.\\kokura\\kokura-cli.exe .\\out\\dmg07_'+lesson+'.gb --hardware cgb --load-state .\\out\\player'+str(i)+'.kqs --run-frames 2 --png .\\out\\player'+str(i)+'.png']
    return '\n'.join(lines)
launch=note('launch','kitaqgb・kokura・kitaq-docsを同じ親フォルダーへ配置し、親フォルダーでPowerShellを開きます。4台通信では同じROMを4セッションで起動します。初代GB用に試す場合は、全コマンドの--cgb=cgbを--cgb=dmg、--hardware cgbを--hardware dmgへ変更します。','Place kitaqgb, kokura and kitaq-docs under one parent directory and open PowerShell there. Four-console examples launch the same ROM in four sessions. For DMG checks, replace --cgb=cgb with --cgb=dmg and --hardware cgb with --hardware dmg throughout.')
dataset=json.loads((SITE/'reference/gb-api.json').read_text(encoding='utf-8'));byname={r['name']:r for r in dataset['records']}
def add(name,ja,en,rj,retn,lesson,code,args=(),notes=(),snippet_source=None,slot=1):
    name='LinkDmg07_'+name;r=byname[name]
    for part,path in [('header',r['path']),('definition',r['definition']['path'])]:
        found=next(d for d in catalog.definitions(REPOS/path) if d['name']==name);hashes[path]=hashlib.sha256((REPOS/path).read_bytes()).hexdigest()
        if part=='header':
            for k in ['ret','args','signature','path','line','comment','body']:r[k]=found[k]
        else:r['definition']=found
    names=[re.search(r'(\w+)\s*$',a).group(1) for a in r['args'].split(',') if a.strip() not in ['','void']];assert names==[a[0] for a in args],(name,names)
    fingerprint=hashlib.sha256(json.dumps({k:r.get(k) for k in ['name','signature','comment','definition','implementation_excerpt']},sort_keys=True).encode()).hexdigest()
    program='samples/api-examples/gb/dmg07_'+lesson+'.c';assert code in (SITE/(snippet_source or program)).read_text(encoding='utf-8'),name
    example={'program':program,'code':code,'build':build(lesson),'expected':[msg('example_'+lesson,*examples[lesson])],'player':slot}
    if snippet_source:example['snippet_source']=snippet_source
    contracts['gb:'+name]={'review':'dmg07-source-20260922','record_sha256':fingerprint,'purpose':[msg(name+'_purpose',ja,en)],'args':[[n,[msg(name+'_'+n,j,e)]] for n,j,e in args],'returns':[msg(name+'_returns',rj,retn)],'notes':list(notes)+[scope,launch],'example':example}
    review['gb:'+name]={'record_sha256':fingerprint,'header_line':r['line'],'definition_line':r['definition']['line']}
none=('戻り値はありません。','No return value.')
add('Init','探索状態、受信保存領域、診断値を初期化し、アダプターからのクロックを待ち受けます。','Reset discovery, receive storage and diagnostics, then arm reception for adapter clocks.',*none,'exchange','LinkDmg07_Init(0);',[('rate','アダプターへ返す8ビットRATE。0なら既定の0x10を使います。','Eight-bit RATE response to the adapter; zero selects the default 0x10.')],[port,slots,note('init','SCを0x80、SBを0x88に設定し、IEとIFのシリアルビットだけを消します。ほかの割り込み許可ビットやCPUのIME状態を変更する処理ではありません。','Sets SC to 0x80 and SB to 0x88; clears only the serial bits in IE and IF. It does not alter the other interrupt-enable bits or CPU IME state.')])
helper=(SITE/'samples/gb_dmg07_example.h').read_text(encoding='utf-8');pollcode=helper[helper.index('void d_poll()'):helper.index('// Display')].strip()
add('Poll','完了済みのシリアル1バイトを現在のフェーズで処理し、次の応答を設定して再び受信を開始します。','Process one completed serial byte in the current phase and immediately arm the next response.',*none,'exchange',pollcode,notes=[port,poll,note('pollbusy','SCの開始ビットが立っている間は何もしません。完了を処理するとSilenceFramesと時間切れラッチをリセットします。初期化前には呼ばないでください。','Does nothing while SC’s start bit is set. Processing completion resets SilenceFrames and the timeout latch. Initialize before polling.')],snippet_source='samples/gb_dmg07_example.h')
add('TickFrame','無通信時間と開始・再起動ハンドシェイクの時間を1フレーム分進め、期限に達したら回復を要求します。','Advance silence and start/restart watchdogs by one frame, requesting recovery at the deadline.',*none,'absent',pollcode,notes=[poll,counters,note('watchdog','既定の期限は12回で、組込み前にLINK_DMG07_TIMEOUT_FRAMESを1～255へ設定できます。同じ無通信状態では1回だけ時間切れを数え、次の受信バイトでラッチを解除します。転送中は位置を保持して境界で再起動し、探索・開始待ちでは探索へ戻ります。','The default deadline is 12 calls; define LINK_DMG07_TIMEOUT_FRAMES as 1..255 before inclusion to choose another deadline. A silence episode is counted once until another byte clears its latch. Transfer recovery preserves byte alignment; discovery/start recovery returns to discovery.')],snippet_source='samples/gb_dmg07_example.h')
add('GetPhase','探索、開始要求、開始確認、データ転送のうち現在の段階を読みます。','Read the current discovery, start-request, confirmation or transfer phase.','0=PING、1=REQUEST_AA、2=WAIT_CC、3=TRANSFERです。','0=PING, 1=REQUEST_AA, 2=WAIT_CC, 3=TRANSFER.','exchange','result[8]=LinkDmg07_GetPhase();',notes=[note('phase','状態を読むだけでポーリングや待機はしません。要求を受け付けただけではTRANSFERにならず、連続する4バイトの0xCCを受信して初めて転送へ移ります。','Does not poll or wait. Acceptance of a start request is insufficient for TRANSFER: four consecutive 0xCC bytes are required.')])
add('GetLocalSlot','アダプターの状態通知から分かった自機のプレイヤー番号を読みます。','Read this console’s player number learned from adapter status.','検出済みは1～4、未検出または探索へのリセット直後は0です。','Returns 1..4 when discovered; zero before discovery or immediately after a discovery reset.','exchange','slot=LinkDmg07_GetLocalSlot();',notes=[slots])
add('GetConnectedMask','最後に受け付けた接続プレイヤーの集合を4ビットで読みます。','Read the four-bit set of players in the last accepted status.','ビット0～3に接続状態を返します。未検出は0、4台接続は15です。','Bits 0..3 report connected players. Undiscovered is zero; four connected players is 15.','exchange','result[1]=LinkDmg07_GetConnectedMask();',notes=[slots,note('cached','探索中に受け付けた値を保存しています。呼び出すたびに物理配線を調べるものではなく、転送中の表示は最後の通知に基づきます。','Returns cached discovery status rather than probing physical wiring. During transfer it reflects the most recent accepted notification.')])
add('GetLastStatus','最後に検証を通ったアダプターの状態バイトを変換せずに読みます。','Read the last validated raw adapter status byte.','上位4ビットは接続マスク、下位3ビットは自機番号です。未検出は0です。','The high nibble is the connection mask; the low three bits contain the local player number. Initially zero.','exchange','result[2]=LinkDmg07_GetLastStatus();',notes=[slots,note('status','ビット3が1、自機番号が0または5以上、検出後に自機番号が変わる通知は拒否し、エラー5を記録します。拒否された値はLastStatusへ保存しません。','Rejects status with bit 3 set, player number zero or above four, or a changed local number after discovery. Rejection latches error 5 without storing that value as LastStatus.')])
add('HasPingStatus','4バイトの探索交換を終えた通知が未消費かどうかを調べます。','Inspect whether a completed four-byte discovery exchange is awaiting acknowledgment.','未消費の通知があれば1、なければ0です。','Returns 1 for an unconsumed notification, otherwise 0.','exchange','result[4]=LinkDmg07_HasPingStatus();',notes=[note('pingflag','フラグを読むだけです。探索中の不正な状態バイトでも交換自体は進むため、このフラグだけで全データの妥当性や転送開始完了を判断せず、番号・マスク・LastErrorも確認します。','Reads only a flag. A discovery exchange can progress despite a rejected status byte; do not use this flag alone to infer fully valid data or completed startup. Check the slot, mask and LastError too.')])
add('ConsumePingStatus','探索完了通知を1回分取り出してフラグを消します。','Consume and clear a completed-discovery notification.','通知があれば1、なければ0です。','Returns 1 when consumed, otherwise 0.','exchange','result[3]=LinkDmg07_ConsumePingStatus();',notes=[note('consume','通知だけを消し、番号・接続マスク・LastStatusの保存値は残します。繰り返し呼ぶと新しい通知が来るまで0になります。','Clears only the notification, preserving slot, mask and LastStatus. Further calls return zero until a new notification arrives.')])
add('RequestTransmission','物理プレイヤー1から、次の探索パケット境界で開始要求を送るよう予約します。','Schedule a start request from physical player 1 at the next discovery-packet boundary.','予約できれば0。フェーズ不正は1、プレイヤー1でなければ2、自機接続ビットがなければ3です。','Returns 0 when scheduled, 1 for the wrong phase, 2 when not player 1, or 3 when the local connection bit is absent.','exchange','result[5]=LinkDmg07_RequestTransmission();',notes=[slots,errors,note('start','PINGでのみ予約できます。全4台がそろうまで待つ処理は含まず、サンプルはアプリ側でマスク15を待ちます。予約は即時転送ではなく、整列した0xAA列を送ってから0xCC列を待ちます。','Can be scheduled only in PING. It does not itself wait for all four players; the example checks mask 15 in application code. Scheduling is asynchronous: aligned 0xAA traffic precedes the 0xCC confirmation.')])
add('RequestRestart','転送中のパケット境界から再起動制御を送るよう予約します。','Schedule restart control traffic beginning at a transfer packet boundary.','TRANSFERなら0、それ以外は1です。予約中・送信中の再要求も0です。','Returns 0 in TRANSFER, otherwise 1. Repeated requests while pending/sending also return 0.','restart','result[3]=LinkDmg07_RequestRestart();result[4]=LinkDmg07_GetRestartState();',notes=[pipeline,errors,note('restart','どのプレイヤーでも要求できます。途中のバイト位置を壊さず、境界から0xFFを送り続け、アダプターの全0xFF通知を受けて探索へ戻ります。要求しただけでは自機番号や受信パイプラインを消しません。','Any player may request it. Preserves the current byte position, sends aligned 0xFF traffic, and returns to discovery after the adapter’s all-0xFF indication. Merely requesting it does not erase the local slot or receive pipeline.')],slot=2)
add('GetRestartState','再起動要求の待機・送信状態を読みます。','Read whether restart control is absent, pending or being sent.','0=なし、1=境界待ち、2=制御送信中です。','0=none, 1=pending boundary, 2=sending control traffic.','restart','result[4]=LinkDmg07_GetRestartState();',notes=[note('restartstate','これは通信フェーズとは別の状態です。値0だけでは接続済みや転送可能とは判断できません。','Separate from the communication phase. Zero alone does not imply an established or usable connection.')],slot=2)
add('SetLocalByte','次に自機データを送るパケット用の1バイトを設定します。','Set the one-byte application value for a future outgoing packet.',*none,'exchange','LinkDmg07_SetLocalByte(32+slot);',[('value','提出する8ビット値。','Eight-bit application value to submit.')],[pipeline,note('sampletime','値はパケットのバイト0を設定するときに読み取ります。すでにSBへ設定したバイトは変更しません。最初の提出値は開始要求前に設定します。','Sampled when packet byte zero is armed. Does not modify an already armed SB byte. Set the first submission before requesting startup.')])
add('IsPipelinePrimed','初回の未定義配信を捨てて受信準備を終えたか調べます。','Inspect whether the initial undefined broadcast has been discarded.','初回配信の処理後は1、初期化・探索へのリセット・開始確認時は0です。','Returns 1 after the initial broadcast; initialization, discovery reset and startup confirmation clear it.','exchange','result[9]=LinkDmg07_IsPipelinePrimed();',notes=[pipeline,note('primed','1でも完成済みパケットがあるとは限りません。取り出せるかどうかはHasPacketで調べます。','A primed pipeline need not contain a completed packet. Use HasPacket to determine whether a read is available.')])
add('HasPacket','通常データの完成済み4バイトパケットが未読か調べます。','Inspect whether a completed four-byte data packet is unread.','未読があれば1、空なら0です。','Returns 1 for unread data, otherwise 0.','exchange','result[15]=LinkDmg07_HasPacket();',notes=[pipeline,mailbox])
add('ReadPacket','最新の完成済みパケットを取り出し、未読フラグを消します。','Copy the latest completed packet and clear its unread flag.','取得できれば1、空なら0です。空ではdstを書き換えません。','Returns 1 when consumed, 0 when empty. Empty reads leave dst unchanged.','exchange','result[10]=LinkDmg07_ReadPacket(packet);',[('dst','4バイトの書き込み可能な領域。0なら内容を読み捨てます。','Four writable bytes; null discards the packet.')],[pipeline,mailbox,note('retained','読んだ後も保存領域にはデータが残るため、GetPacketSlotで参照できます。空のReadPacketはその保存値を再取得する操作ではありません。','Cached bytes remain available through GetPacketSlot after consumption. An empty ReadPacket does not copy those cached bytes again.')])
add('GetPacketSlot','保存中のパケットから指定プレイヤーの1バイトを読みます。','Read one player’s byte from cached packet storage.','1～4なら対応する保存値、不正な番号なら0です。','Returns the cached byte for player 1..4, or zero for an invalid number.','exchange','result[16]=LinkDmg07_GetPacketSlot(4);',[('player_slot','物理プレイヤー番号1～4。','Physical player number, 1..4.')],[slots,note('cachebyte','未読フラグは調べず、消費もしません。初期化直後は0、消費後や探索へのリセット後は保存値を返すことがあるため、新着判定には使いません。','Neither checks nor consumes readiness. Returns zero just after initialization and may return retained bytes after consumption or a discovery reset. Do not use it as a new-data test.')])
add('GetSentSequence','自機の提出バイトが実際にクロックで送り出された回数を読みます。','Read the count of application submission bytes actually clocked out.','8ビットの送信番号です。初回の提出も数えますが、再起動制御の送信は数えません。','Returns the eight-bit sent sequence. Counts the initial submission but excludes restart-control traffic.','exchange','result[6]=LinkDmg07_GetSentSequence();',notes=[seq,pipeline])
add('GetPacketSequence','最後にメールボックスへ公開したパケットの番号を読みます。','Read the sequence assigned to the most recently published packet.','8ビットの受信パケット番号です。読み取りで未読フラグは変わりません。','Returns the eight-bit packet sequence without changing readiness.','exchange','result[7]=LinkDmg07_GetPacketSequence();',notes=[seq,mailbox])
add('GetSilenceFrames','最後のシリアル完了処理から経過したフレーム数を読みます。','Read frames counted since the last processed serial completion.','0～255。完了処理で0へ戻り、TickFrameごとに増えます。','0..255; processed completion resets it, and each TickFrame increments it.','absent','result[6]=LinkDmg07_GetSilenceFrames();',notes=[poll,counters])
add('GetTimeoutCount','無通信またはハンドシェイクの期限超過を記録した回数を読みます。','Read the count of silence or handshake deadline expirations.','0～255の累積値です。','Returns a cumulative value in 0..255.','absent','result[7]=LinkDmg07_GetTimeoutCount();',notes=[counters,note('timeoutonce','受信が再開するまで同じ無通信状態を毎フレーム加算しません。ClearErrorを呼んでもこの抑制ラッチと累積値は残ります。','Does not count the same silence episode every frame before reception resumes. ClearError preserves both this suppression latch and the cumulative count.')])
add('GetDisconnectCount','検出済みアダプターの無通信、または探索マスクからのプレイヤー減少を数えます。','Read recorded loss events: silence after seeing an adapter, or players disappearing from discovery status.','0～255の累積イベント数です。失われた人数ではありません。','Returns 0..255 events, not the number of lost players.','absent','result[8]=LinkDmg07_GetDisconnectCount();',notes=[counters,note('disconnect','アダプター未検出のまま期限を超えても増えません。1回の状態変化で複数人が消えても1イベントです。','A deadline before any adapter has been observed does not increment it. Multiple players removed by one status change count as one event.')])
add('GetErrorCount','受信プロトコル不正と未読パケットの上書きを記録した回数を読みます。','Read the count of received-protocol errors and unread-packet overwrites.','0～255の累積値です。要求の引数・状態エラーや時間切れはこの数に含めません。','Returns 0..255. Request validation/state errors and timeouts are not included.','overflow','result[19]=LinkDmg07_GetErrorCount();',notes=[counters,mailbox])
add('LastError','最後に記録したエラー番号を読みます。','Read the most recently latched error code.','0～6のエラー番号です。','Returns error code 0..6.','absent','result[9]=LinkDmg07_LastError();',notes=[errors,note('last','読み取りでは消えません。複数の問題が起きたときの全履歴ではなく、最後のコードだけです。','Reading does not clear it. Stores only the latest code, not a history of every error.')])
add('ClearError','最後のエラー番号を0へ戻します。','Reset the last-error code to zero.',*none,'overflow','LinkDmg07_ClearError();result[21]=LinkDmg07_LastError();result[22]=LinkDmg07_GetErrorCount();',notes=[counters,note('clear','受信データ、フェーズ、接続情報、時間切れラッチは変えません。これだけで再接続や受信再開を行う関数ではありません。','Preserves received data, phase, connection information and the timeout latch. This call alone does not reconnect or resume reception.')])
assert len(contracts)==25
module=msg('module','DMG-07は各台からの1バイトを4台へ配信するアダプターです。このライブラリは、探索、プレイヤー1による開始要求、1パケット遅れの配信、整列した再起動制御を扱います。EXCHANGEで基本の4台通信、NO ADAPTERで時間切れ、OVERFLOWで読み忘れ、RESTARTで回復を学べます。','The DMG-07 broadcasts one submitted byte from each console to all four players. This library handles discovery, player-1 startup, delayed packet broadcasts and aligned restart control. Learn four-console exchange with EXCHANGE, timeout behavior with NO ADAPTER, unread data with OVERFLOW and recovery with RESTART.')
for file,data in [('dmg07_contracts.json',contracts),('dmg07_texts.json',texts),('dmg07_modules.json',{'gb:link_dmg07':[module,slots,port,poll,pipeline]}),('dmg07_review_sources.json',{'source_sha256':hashes,'records':review})]:
    (HERE/file).write_text(json.dumps(data,ensure_ascii=False,indent=2),encoding='utf-8')
(SITE/'reference/gb-api.json').write_text(json.dumps(dataset,ensure_ascii=False,indent=2),encoding='utf-8')
print('25 individually authored DMG-07 contracts')
