"""Author eight FC wireframe contracts from implementation and a complete example."""
from pathlib import Path
import hashlib,json,re,sys
HERE=Path(__file__).resolve().parent;SITE=HERE.parents[1]
REPOS=SITE.parents[1]/'publish/github_20260912'
sys.path.insert(0,str(SITE/'tools'))
import catalog
catalog.ROOT=REPOS
texts={};contracts={}
def msg(key,ja,en):
    key='fc_wire_'+key;texts[key]={'ja':ja,'en':en};return key
none=msg('none','戻り値はありません。','No return value.')
memory=msg('memory','CHR RAM 8 KiBと、書き込み可能なカートリッジPRG RAM $6800～$70BF、ゼロページ$00～$0Aを使います。--nes-chr-ramでビルドしてください。共有作業領域を使うため再入できません。','Requires 8 KiB of CHR RAM, writable cartridge PRG RAM at $6800–$70BF and zero-page scratch at $00–$0A. Build with --nes-chr-ram. Shared working storage makes the renderer non-reentrant.')
video=msg('video','Init→BeginFrame→描画→EndFrameの順に使います。背景パターンテーブル2面、ネームテーブル0、背景パレット、スクロールをライブラリが管理し、NMIを無効にします。他のPPU書き込み処理と同時に動かさないでください。','Call Init, BeginFrame, drawing functions and EndFrame in that order. The library owns both background pattern tables, nametable zero, the background palette and scroll, and disables NMI. Do not run another PPU writer concurrently.')
size=msg('size','表示領域は64×48（既定）、96×64、128×96です。wire3d.cをインクルードする前にWIRE3D_FC_WIDTHとWIRE3D_FC_HEIGHTを組で指定します。画面中央へ配置され、小さいサイズほど描画・転送量を減らせますが、予約するRAM容量は同じです。','Choose 64×48 (default), 96×64 or 128×96 by defining both WIRE3D_FC_WIDTH and WIRE3D_FC_HEIGHT before including wire3d.c. The viewport is centered on screen. Smaller views reduce rendering and transfer work but reserve the same RAM capacity.')
scene=msg('scene','完成画像は黒地に水色の枠、中央の立方体、上側の十字、下側の横線です。枠は2D座標、十字は点の回転と投影、横線は3D線、立方体は頂点・辺の配列を使う例です。各関数の役割を同じ画面で見比べられます。','The completed image has a cyan border, a central cube, an upper cross and a lower horizontal line on black. The border uses 2D coordinates; the cross uses point rotation and projection; the lower line uses camera-space endpoints; the cube uses vertex and edge arrays. These shapes let you compare the roles of the APIs on one screen.')
verification=msg('verification','掲載画像はKUROSAKIで3サイズを実行し、全256×240画素の位置・色とRAMの計算結果を照合したものです。実機の速度を保証する測定ではありません。','The images were captured in KUROSAKI at all three sizes. Checks compare every pixel of the 256×240 image, including color, and the numeric results in RAM. They are not hardware performance measurements.')
angles=msg('angles','回転量は32段階で1周です。0は回転なし、8は90度、16は180度です。値の下位5ビットを使います。回転の順序はY→X→Zです。','Angles use 32 steps per turn: 0 is no rotation, 8 is 90 degrees and 16 is 180 degrees. Only the low five bits are used. Rotations are applied in Y, X, Z order.')
path=SITE/'reference/fc-api.json';data=json.loads(path.read_text(encoding='utf-8'))
declarations={r['name']:r for r in catalog.definitions(REPOS/'kitaqfc/lib/wire3d.h')}
definitions={r['name']:r for r in catalog.definitions(REPOS/'kitaqfc/lib/wire3d.c')}
program='samples/api-examples/fc/wire3d_projection.c';source=(SITE/program).read_text(encoding='utf-8')
build='New-Item -ItemType Directory -Force .\\out | Out-Null\n.\\kitaqfc\\kitaqfc.exe .\\kitaq-docs\\samples\\api-examples\\fc\\wire3d_projection.c -I .\\kitaqfc\\lib --mapper=nrom --nes-chr-ram -o .\\out\\wire3d_projection.nes --no-cache --no-disasm\n.\\kurosaki\\kurosaki.exe run .\\out\\wire3d_projection.nes --headless --frames 180 --png .\\out\\wire3d_projection.png'

def arg(name,ja,en):return [name,[msg('arg_'+name+'_'+str(len(texts)),ja,en)]]
def add(short,ja,en,args,snippet,notes=(),returns=None,expected=None):
    name='Wire3DFC_'+short;record=dict(declarations[name])
    record.update(module='wire3d',availability='implementation',definition=definitions[name])
    record['example']={'source':program,'calls':[name]}
    data['records']=[r for r in data['records'] if r['name']!=name]+[record]
    assert snippet in source,name
    fingerprint=hashlib.sha256(json.dumps({k:record.get(k) for k in ['name','signature','comment','definition','implementation_excerpt']},sort_keys=True).encode()).hexdigest()
    contracts['fc:'+name]=dict(review='fc-wireframe-source-20260922',record_sha256=fingerprint,purpose=[msg(short+'_purpose',ja,en)],args=args,returns=[returns or none],notes=list(notes)+[memory,video,size,verification],example=dict(program=program,code=snippet,build=build,expected=[scene]+([expected] if expected else [])))

add('Init','CHR RAMと背景マップ、ステージ、変更タイルの履歴を初期化し、水色の線を描く背景表示を有効にします。現在の画面内容は消えます。','Initialize CHR RAM, the background map, staging pixels and dirty-tile history, then enable background rendering with cyan lines. Existing screen contents are erased.',[], 'Wire3DFC_Init();')
add('BeginFrame','前の描画で触れたタイルのステージデータを消し、新しい図を描ける状態にします。表示中のCHRテーブルと画面は書き換えません。','Clear staged pixels in tiles touched by the previous drawing, preparing an empty frame. The displayed CHR table and visible image remain unchanged.',[], 'Wire3DFC_BeginFrame();',notes=[msg('begin_sequence','描画のたびに最初に呼びます。EndFrameの前にもう一度呼ぶと、その時点までのステージ上の線を消します。','Call once at the start of each drawing. Calling again before EndFrame erases the lines staged so far.')])
screen_args=[arg(n,('始点' if n[0]=='a' else '終点')+'の'+('横' if n[-1]=='x' else '縦')+'座標です。表示領域左上を(0,0)とするピクセル値で、−512～511を指定します。',('Start' if n[0]=='a' else 'End')+' '+('horizontal' if n[-1]=='x' else 'vertical')+' coordinate in viewport pixels, from −512 to 511. The viewport top left is (0,0).') for n in ['ax','ay','bx','by']]
add('DrawLine2D','両端を含む線をステージへ描き、触れたタイルを転送対象として記録します。カメラ投影は行いません。','Rasterize an inclusive line into staging memory and mark touched tiles for upload. No camera projection is performed.',screen_args,'Wire3DFC_DrawLine2D(0,0,WIRE3D_FC_WIDTH-1,0);',notes=[msg('line_clip','座標が−512～511の範囲を外れると線全体を描きません。有効な座標では表示領域外のピクセルを捨てます。描画済みの線とはORで合成し、画面への反映はEndFrameで行います。','Reject the whole line if any endpoint coordinate is outside −512..511. Otherwise discard pixels outside the viewport. New pixels are ORed with staged lines and become visible through EndFrame.')])
point_args=[arg(n,n+'成分を読み書きするs16へのポインターです。3成分は別々の有効な領域を指し、入力値を各−63～63に保ちます。','Pointer to the writable s16 '+n+' component. Use three distinct locations and keep each input component in −63..63.') for n in ['x','y','z']]
angle_args=[arg(n,n[1].upper()+'軸の回転角です。32段階で1周します。',n[1].upper()+'-axis angle, in 32 steps per turn.') for n in ['rx','ry','rz']]
add('RotatePoint','モデル空間の1点をその場で回転します。位置の平行移動や透視投影は行いません。','Rotate one model-space point in place, without translation or perspective projection.',point_args+angle_args,'Wire3DFC_RotatePoint(&px,&py,&pz,0,0,8);',notes=[angles,msg('rotate_limits','いずれかのポインターが0なら何も変更せず戻ります。Q6整数演算の小数部は0方向へ丸めます。入力範囲を自動的に制限する処理はありません。','If any pointer is null, return without modifying coordinates. Q6 integer products truncate toward zero. Input components are not automatically clamped.')],expected=msg('rotate_expected','サンプルの(24,0,0)はZ軸の90度回転で(0,24,0)になり、投影後の十字が立方体より上に現れます。','In the sample, a 90-degree Z rotation changes (24,0,0) to (0,24,0); its projected cross appears above the cube.'))
projection_args=[arg(n,'カメラから見た'+n.upper()+'座標です。'+('−127～127を指定します。正のXは右、正のYは上です。' if n!='z' else '奥行き32～255を指定します。値が大きいほど遠くなります。'),'Camera-space '+n.upper()+' coordinate. '+('Use −127..127. Positive X is right and positive Y is up.' if n!='z' else 'Depth must be 32..255; larger values are farther away.')) for n in ['x','y','z']]
projection_args += [arg(n,'投影した'+('横' if n=='sx' else '縦')+'座標を書き込むs16ポインターです。2出力は異なる有効な領域を指します。','Writable s16 pointer for the projected '+('horizontal' if n=='sx' else 'vertical')+' pixel coordinate. Use distinct output locations.') for n in ['sx','sy']]
add('ProjectPoint','カメラ空間の1点を表示領域のピクセル座標へ変換します。画面中央が投影の中心です。描画やマスクの変更は行いません。','Project one camera-space point to viewport pixels, using the viewport center as the projection center. This does not draw or change a mask.',projection_args,'projected=Wire3DFC_ProjectPoint(px,py,pz+96,&sx,&sy);',returns=msg('project_return','成功は1、座標範囲外または出力ポインターが0なら0です。失敗時は出力先を変更しません。','Return 1 on success, or 0 for out-of-range coordinates or null output pointers. Failed calls leave outputs untouched.'),notes=[msg('project_outside','有効な奥行きでも、投影結果は表示領域外になることがあります。画面端への制限は行いません。逆数表による整数近似を使うため、浮動小数点による理想的な投影とは数ピクセル異なる場合があります。','Valid depth does not guarantee an on-screen result. Output coordinates are not clamped to the viewport. Integer reciprocal approximation may differ by a few pixels from ideal floating-point projection.')],expected=msg('project_expected','十字の中心は、64×48で(32,16)、96×64で(48,20)、128×96で(64,33)です。座標は画面全体ではなく各表示領域の左上が原点です。','The cross center is (32,16) at 64×48, (48,20) at 96×64 and (64,33) at 128×96, measured from the viewport top left.'))
line3_args=[arg(n,('始点' if n[0]=='a' else '終点')+'のカメラ空間'+n[1].upper()+'座標です。'+('−127～127を指定します。' if n[1]!='z' else '奥行き32～255を指定します。'),('Start' if n[0]=='a' else 'End')+' camera-space '+n[1].upper()+' coordinate; '+('use −127..127.' if n[1]!='z' else 'use depth 32..255.')) for n in ['ax','ay','az','bx','by','bz']]
add('DrawLine3D','カメラ空間の両端点を投影し、両方が有効なら線を描きます。モデルの回転や平行移動は呼び出し側で済ませます。','Project two camera-space endpoints and draw the line when both are valid. Perform any model rotation or translation before calling.',line3_args,'Wire3DFC_DrawLine3D(-24,-24,96,24,-24,96);',notes=[msg('near_clip','片方だけでも投影条件を満たさなければ線全体を捨てます。近接面との交点を求めるクリッピングは行いません。有効な線の画面外ピクセルはDrawLine2Dで除外します。','If either endpoint fails projection, discard the whole segment. There is no intersection clipping at the near plane. DrawLine2D discards off-viewport pixels of accepted segments.')])
model_args=[arg('vertices','s8のx/y/zを持つWire3DFC_Vec3の配列です。頂点成分は各−63～63に保ち、宣言した個数分を用意します。','Array of Wire3DFC_Vec3 records with s8 x/y/z components. Keep components in −63..63 and supply the declared number of vertices.'),arg('vertex_count','頂点数です。24を超える場合は先頭24頂点だけを扱います。','Vertex count; values above 24 use only the first 24 vertices.'),arg('edges','頂点番号a/bを持つWire3DFC_Edgeの配列です。edge_count個の要素を用意します。','Array of Wire3DFC_Edge records containing vertex indices a/b. Supply edge_count elements.'),arg('edge_count','処理する辺の数（0～255）です。使用頂点数以上の番号を含む辺は省略します。','Number of edges to process (0..255). Edges referencing vertices beyond the effective vertex count are skipped.')]
model_args += [arg(n,'回転後の頂点へ加える'+n.upper()+'方向の位置です。加算後の各点がProjectPointの入力範囲に収まるようにします。',n.upper()+' translation added after rotation. Transformed points must satisfy ProjectPoint input ranges.') for n in ['x','y','z']]
add('DrawModel','頂点を回転・移動・投影して共有し、辺の配列に従って線を描きます。各辺で同じ頂点を計算し直すことを避けます。','Rotate, translate and project vertices once, then reuse their screen coordinates while drawing indexed edges.',model_args+angle_args,'Wire3DFC_DrawModel(example_vertices,8,example_edges,12,0,0,96,0,3,0);',notes=[angles,msg('model_limits','verticesまたはedgesが0なら描画しません。表は現在のPRGマッピングで読み取れる必要があります。面データや奥行きマスクは使わず、有効な辺をすべて描きます。立方体の奥側の辺も見えます。','Null vertices or edges produce no drawing. Tables must remain readable in the current PRG mapping. This API uses no face data or depth mask and draws every valid edge, so rear cube edges remain visible.')])
add('EndFrame','触れたタイルと、裏側CHRテーブルの消去が必要なタイルを転送し、完了後のVBlankで表示面を切り替えます。','Upload touched tiles and tiles that must be erased from the hidden CHR table, then switch the displayed table at a fresh VBlank after completion.',[], 'Wire3DFC_EndFrame();',notes=[msg('end_batches','1回のVBlankで最大16タイル（低位ビットプレーン128バイト）を転送します。必要な回数だけ待つ同期処理です。wire3d_uploaded_tilesは転送したタイル数、wire3d_transfer_framesは転送バッチ数＋表示切り替えの待機1回であり、ゲーム全体で経過したフレーム数ではありません。','Each VBlank batch transfers at most 16 tiles, or 128 low-bitplane bytes. This synchronous call waits for as many batches as needed. wire3d_uploaded_tiles reports transferred tiles; wire3d_transfer_frames counts upload batches plus one swap wait, not total elapsed game frames.'),msg('end_clear','裏側の過去の描画も考慮するため、物体が移動した後に古い線を消せます。タイルの全内容を前後比較する差分検出ではなく、描画で触れたタイルの履歴を使います。','History for the hidden table allows old lines to be erased after objects move. Tracking is based on tiles touched by drawing, rather than comparing every tile byte between frames.')])
assert len(contracts)==8
header='kitaqfc/lib/wire3d.h'
data['headers']=sorted(set(data['headers']+[header,'kitaqfc/lib/wire3d_tables.h']))
data['records'].sort(key=lambda r:(r['module'],r['name']))
path.write_text(json.dumps(data,ensure_ascii=False,indent=2),encoding='utf-8')
for name,value in [('fc_wireframe_contracts.json',contracts),('fc_wireframe_texts.json',texts),('fc_wireframe_review_sources.json',{'source_sha256':{('kitaqfc/lib/'+name):hashlib.sha256((REPOS/'kitaqfc/lib'/name).read_bytes()).hexdigest() for name in ['wire3d.c','wire3d.h','wire3d_tables.h']}})]:
    (HERE/name).write_text(json.dumps(value,ensure_ascii=False,indent=2),encoding='utf-8')
print('8 FC wireframe API contracts added to the standard source inventory')
