"""Individually authored English/Japanese contracts for all 37 link.h APIs."""
from pathlib import Path
import hashlib,json,re,sys
HERE=Path(__file__).resolve().parent;SITE=HERE.parents[1];REPOS=SITE.parents[1]/'publish/github_20260912'
if not REPOS.exists():REPOS=SITE.parent
sys.path.insert(0,str(SITE/'tools'));import catalog
catalog.ROOT=REPOS
texts={};contracts={};records={};source_hashes={}
def message(key,ja,en):
    key='link_'+key;value={'ja':ja,'en':en}
    if key in texts:assert texts[key]==value,key
    texts[key]=value;return key
def note(key,ja,en):return message('note_'+key,ja,en)
shared=note('shared','ライブラリは1台につき1つの通信状態を共有します。バイト送受信は全二重で、片側が内部クロック、もう片側が外部クロックを使います。通常速度は1ビット512クロック、CGB高速は16クロックです。','Each machine has one shared link state. Byte exchanges are full duplex: one side supplies the internal clock and the other uses external clocks. Normal speed takes 512 clocks per bit; CGB fast speed takes 16.')
codes=note('codes','エラーコードは0=正常、1=使用中、2=時間切れ、3=受信容量不足、4=設定またはプロトコル不正、5=ACK待ちで切断を示す応答です。開始・設定関数の成功は0、受信取得関数の成功は1なので区別してください。成功しても過去のエラーは消えません。','Error codes are 0=none, 1=busy, 2=timeout, 3=receive overflow, 4=invalid configuration/protocol and 5=an ACK timeout with a disconnect-like response. Start/configuration calls succeed with 0; receive/pop calls succeed with 1. Successful calls do not clear a latched error.')
reset=note('reset','初期化は受信キュー、パケット、接続先、エラーを破棄し、転送とシリアル割り込みを停止します。送受信中のデータを保存する操作ではありません。','Initialization discards byte queues, packets, peer selection and errors, and disables the transfer and serial IRQ source. It does not preserve an in-flight exchange.')
critical=note('critical','内部のクリティカルセクションはソフトウェアの入れ子深さを使います。外側のセクションを抜けるとCPU割り込みが有効になるため、直前のIME状態の保存は前提にしないでください。','Internal critical sections track software nesting depth. Leaving the outer section enables CPU interrupts, so do not assume that a previously disabled IME state is preserved.')
ring=note('ring','受信リングは8要素中7バイトを保持できます。満杯では新しいバイトを捨て、エラー3を記録します。受信値0も有効なデータです。','An eight-entry receive ring holds seven bytes. A full ring drops the new byte and latches error 3. A received zero byte is valid data.')
logical=note('logical','Link4はホスト0と、1～3の相手を論理的に管理します。SelectPeerは電気的な配線を切り替えるコマンドを送りません。KOKURAのlink4接続ではコンパイラのメタデータを使って接続先を追従させます。DMG-07実機のプロトコルにはLinkDmg07を使います。','Link4 manages logical host slot 0 and peer slots 1–3. SelectPeer does not send a command that switches physical wiring. KOKURA’s link4 topology follows the selected peer through compiler metadata. Use LinkDmg07 for the physical DMG-07 protocol.')
duplicate=note('duplicate','Link4では同じ受信バイトを通常リングと相手別リングの両方へ入れます。片方を読んでも他方は減りません。パケットのポーリングは通常リングを消費するので、不要な相手別の生バイトも定期的に読み捨て、満杯を防ぎます。','Link4 copies each received byte to both the ordinary ring and a per-peer ring. Reading one does not drain the other. Packet polling consumes the ordinary ring; regularly discard unused per-peer raw bytes as well to prevent overflow.')
packet=note('packet','パケットは0xA5、コマンド、長さ、0～24バイトの内容、XORチェックサムの順で送り、受信確認0x79（ACK）または受信拒否0x1F（NAK）を返します。チェックサムはコマンド・長さ・内容のXORです。各機の通常メールボックスは1パケット、Link4は相手ごとにも1パケットを保持します。','A packet contains 0xA5, command, length, 0–24 payload bytes and an XOR checksum. The response is 0x79 (ACK, accepted) or 0x1F (NAK, rejected). The checksum XORs the command, length and payload. Each machine has one shared packet mailbox; Link4 additionally has one mailbox per peer.')
polling=note('polling','送受信の両側で継続してポーリングします。タイマーはハードウェアのフレーム数ではなく、進展のない呼び出し90回で満了します。ACKを待つための0xFF送信だけでは期限を延長せず、送信は最大3回試みます。再送で同じ内容が届く場合があるため、厳密に1回だけ実行したいコマンドにはアプリ側の識別番号を付けます。','Keep polling on both endpoints. A timeout counts 90 calls without progress, not hardware frames. Sending 0xFF solely to clock an ACK does not extend that deadline; transmission allows at most three attempts. Retries can deliver duplicates, so add application-level identifiers when a command must run exactly once.')
buffer=note('buffer','受信先の容量を渡す引数はありません。dstを使う場合は最大長24バイトの書き込み可能な領域を用意します。cmd・len・dstは個別に0を渡して省略できます。空き通知と読み取りを別スレッドや割り込みで競合させないでください。','There is no destination-capacity parameter. Provide 24 writable bytes when using dst. cmd, len and dst may independently be null. Serialize mailbox inspection and consumption against other code and interrupts.')
scope=note('scope','掲載画像はKOKURA上の結果です。複数台を使う通信例では、リンクしたエミュレータで送受信値を照合し、その終了状態から画面を取得しています。実機ケーブルや実物の4人用アダプターを使った検証ではありません。','The screens come from KOKURA. Multi-endpoint examples check values on linked emulator instances, and screens are captured from their final saved states. These checks do not establish physical cable or four-player adapter behavior.')
examples={
'control':('初期化、使用中エラー、外部クロック待ち、受信リングの満杯を確かめます。BUSY ERROR=1、TIMEOUT=2、OPEN RX=255、OVERFLOW=3、QUEUE BYTES=7になります。IRQ REQUEST=1を確認してから、割り込み禁止のままハンドラー本体を明示呼び出しします。','Check initialization, busy rejection, an external-clock timeout and ring capacity. Expect BUSY ERROR=1, TIMEOUT=2, OPEN RX=255, OVERFLOW=3 and QUEUE BYTES=7. After observing IRQ REQUEST=1, the lesson explicitly dispatches the handler body while the serial IRQ source remains masked.'),
'raw_master':('同梱のBYTE SLAVEと接続します。42を送り99を受け取り、次に双方で0を交換します。RECEIVED=1、PEER BYTE=99、ZERO READY=1、ZERO BYTE=0が、受信した0と未受信の違いを示します。CGB同士では2回目を高速クロックで行います。','Connect to BYTE SLAVE. Send 42 and receive 99, then exchange zero in both directions. RECEIVED=1, PEER BYTE=99, ZERO READY=1 and ZERO BYTE=0 distinguish valid zero data from no data. Two CGB instances use fast clocks for the second exchange.'),
'raw_slave':('同梱のBYTE MASTERがクロックを供給します。PEER BYTE=42、ZERO READY=1、ZERO BYTE=0になります。その後のEMPTY READも0になるため、空かどうかは準備フラグかTryReadの戻り値で判断します。','BYTE MASTER supplies the clocks. Expect PEER BYTE=42, ZERO READY=1 and ZERO BYTE=0. EMPTY READ is also zero afterwards, which is why readiness or TryRead’s return value is needed to distinguish an empty queue.'),
'packet_master':('コマンド49と3バイト7/42/255を送り、送信直後に元の配列を変更します。QUEUED=0、重複開始はSECOND SEND=1です。この使用中エラーは送信成功後も残り、ClearErrorで0にします。受信側のPAYLOAD 2=42が、内容をコピーしていることの確認になります。','Send command 49 with payload 7/42/255, then change the source array. QUEUED=0 accepts the send; SECOND SEND=1 rejects a second start. That busy error remains latched until ClearError. PAYLOAD 2=42 on the receiving endpoint proves that the queued payload is an owned copy.'),
'packet_slave':('同梱のPACKET MASTERと接続し、COMMAND=49、LENGTH=3、PAYLOAD=7/42/255を確認します。ReadPacket後のCONSUMED=0は、メールボックスが空になったことを示します。','Connect to PACKET MASTER and check COMMAND=49, LENGTH=3 and payload 7/42/255. CONSUMED=0 after ReadPacket means that the mailbox is now empty.'),
'four_host':('4つのROMをKOKURAのlink4で接続します。ホストは相手1/2/3から161/162/163を受け取り、LAST PEER=3になります。続いて各相手へコマンド65/66/67と7/42/255を送ります。各相手の画面でも内容を確認します。','Connect all four ROMs with KOKURA’s link4 topology. The host receives 161/162/163 from peers 1/2/3 and shows LAST PEER=3. It then sends commands 65/66/67 with payload 7/42/255; verify those values on each peer’s screen too.'),
'four_peer1':('4スロットの相手1として、HOST BYTE=17、COMMAND=65、LENGTH=3、PAYLOAD 2=42を確認します。CONSUMED=0は相手0のメールボックスを消費した後の値です。','As peer 1 of four slots, expect HOST BYTE=17, COMMAND=65, LENGTH=3 and PAYLOAD 2=42. CONSUMED=0 is the host mailbox flag after consumption.'),
'deadline':('相手を接続せずにパケットを送ります。内部クロックのバイト転送自体は完了してもACKが来ないため、再試行後にNO ACK ERROR=5になります。Cancel後はCANCEL BUSY=0です。','Send with no peer attached. Byte transfers complete under internal clocks, but no ACK arrives; after retries, NO ACK ERROR=5. Cancel leaves CANCEL BUSY=0.')}
specs={s['name']:s for s in json.loads((HERE/'link_examples.json').read_text(encoding='utf-8'))}
dataset=json.loads((SITE/'reference/gb-api.json').read_text(encoding='utf-8'));byname={r['name']:r for r in dataset['records']}
def build_commands(lesson):
    group = ['raw_master','raw_slave'] if lesson.startswith('raw_') else ['packet_master','packet_slave'] if lesson.startswith('packet_') else ['four_host','four_peer1','four_peer2','four_peer3'] if lesson.startswith('four_') else [lesson]
    lines=['New-Item -ItemType Directory -Force .\\out | Out-Null']
    for item in group:
        lines.append('.\\kitaqgb\\kitaqgb.exe .\\kitaq-docs\\'+specs[item]['source'].replace('/','\\')+' -I .\\kitaqgb\\lib -I .\\kitaq-docs\\samples -o .\\out\\link_'+item+'.gb --profile=dev --rst-disable --stack-bank=fixed --cgb=cgb --cart=mbc5 --romsize=128k --no-cache --no-disasm')
    if len(group)>1:
        lines.append('.\\kokura\\kokura-cli.exe --link-topology '+('link4' if len(group)==4 else 'pair')+' --run-frames 360 '+ ' '.join('--link-session "name='+item+'|slot='+str(i)+'|rom=.\\out\\link_'+item+'.gb|save_state=.\\out\\'+item+'.kqs"' for i,item in enumerate(group)))
        for item in group:
            lines.append('.\\kokura\\kokura-cli.exe .\\out\\link_'+item+'.gb --hardware cgb --load-state .\\out\\'+item+'.kqs --run-frames 2 --png .\\out\\'+item+'.png')
    else:
        lines.append('.\\kokura\\kokura-cli.exe .\\out\\link_'+lesson+'.gb --hardware cgb --run-frames 330 --png .\\out\\'+lesson+'.png')
    return '\n'.join(lines)

def add(name,ja,en,retja,reten,lesson,code,args=(),notes=()):
    r=byname[name];header=REPOS/r['path'];definition=next(d for d in catalog.definitions(header) if d['name']==name)
    for k in ['ret','args','signature','path','line','comment','body']:r[k]=definition[k]
    source=REPOS/r['definition']['path'];r['definition']=next(d for d in catalog.definitions(source) if d['name']==name)
    for f in [header,source]:source_hashes[f.relative_to(REPOS).as_posix()]=hashlib.sha256(f.read_bytes()).hexdigest()
    names=[re.search(r'(\w+)\s*$',a).group(1) for a in r['args'].split(',') if a.strip() not in ['', 'void']];assert names==[a[0] for a in args],(name,names,args)
    fingerprint=hashlib.sha256(json.dumps({k:r.get(k) for k in ['name','signature','comment','definition','implementation_excerpt']},sort_keys=True).encode()).hexdigest()
    program=specs[lesson]['source'];text=(SITE/program).read_text(encoding='utf-8');assert code in text,(name,'snippet');assert re.search(r'\b'+name+r'\s*\(',code),name
    build=build_commands(lesson)
    contracts['gb:'+name]={'review':'link-source-20260917','record_sha256':fingerprint,'purpose':[message(name+'_purpose',ja,en)],'args':[[n,[message(name+'_'+n,j,e)]] for n,j,e in args],'returns':[message(name+'_returns',retja,reten)],'notes':list(notes)+[scope], 'example':{'program':program,'code':code,'build':build,'expected':[message('example_'+lesson,*examples[lesson])]}}
    records['gb:'+name]={'record_sha256':fingerprint,'header_line':r['line'],'definition_line':r['definition']['line']}
none=('戻り値はありません。','No return value.')
boolout=('out','受信値を書き込む1バイトの領域。0なら読み捨てます。','Writable byte destination; null discards the byte.')
peer=('peer_slot','設定済みの自分以外のスロット。ホストからは1～slot_count−1、相手からは0を指定します。','Configured remote slot: 1..slot_count−1 from the host, or 0 from a peer.')
outputs=[('cmd','受信コマンドを書き込む1バイト。0なら省略します。','Writable command byte; null omits it.'),('len','受信長0～24を書き込む1バイト。0なら省略します。','Writable length byte, 0..24; null omits it.'),('dst','最大24バイトの書き込み先。0なら内容を読み捨てます。','Writable payload buffer with room for 24 bytes; null discards the payload.')]
sendargs=[('data','lenバイトを読み取る元。len=0のときだけ0を渡せます。','Readable source of len bytes; may be null only when len is zero.'),('len','内容の長さ0～24バイト。','Payload length in bytes, 0..24.'),('cmd','受信側アプリが意味を定める8ビットのコマンド。','Application-defined eight-bit command.')]
add('Link_InitCommon','通信状態を初期値へ戻し、外部クロック待ちの役割にします。','Reset the shared link state to its external-clock default.',*none,'control','Link_InitCommon();result[0]=Link_IsBusy();result[1]=Link_HasByte();result[2]=Link_LastError();',notes=[shared,reset,critical])
add('Link_InitMaster','状態を初期化し、自機がクロックを供給する役割を選びます。','Reset state and make this machine the clock source.',*none,'raw_master','Link_InitMaster();Link_SetUseInterrupt(0);Link_SetFastClock(0);',notes=[shared,reset,critical])
add('Link_InitSlave','状態を初期化し、相手から来るクロックで通信する役割を選びます。','Reset state and select externally clocked communication.',*none,'raw_slave','Link_InitSlave();result[0]=Link_BeginTransfer(99);',notes=[shared,reset,critical])
add('Link_SetUseInterrupt','シリアル割り込みの許可ビットを設定し、保留中の要求を消します。','Set the serial interrupt-enable bit and clear a pending serial request.',*none,'control','Link_SetUseInterrupt(1);result[3]=(IE_REG&8)!=0;Link_SetUseInterrupt(0);result[4]=(IE_REG&8)!=0;',[('on','0で無効、0以外で有効にします。','Zero disables; any nonzero value enables.')],[critical,note('irq','割り込みベクター0058hのハンドラーは別途必要です。ライブラリは自動登録しません。サンプルは転送開始前に許可を戻し、実際のCPU割り込み入口は検証していません。','Install a handler at vector 0058h separately; this library does not register one. The sample masks the source again before transferring and does not test a CPU interrupt entry stub.')])
add('Link_SetFastClock','以後の内部クロック転送でCGB高速ビットを使うか選びます。','Choose whether future internally clocked transfers use the CGB fast-clock bit.',*none,'raw_master','lesson_delay(12);Link_SetFastClock(__cgb_is_cgb());result[5]=Link_BeginTransfer(0);value=77;',[('on','0で通常、0以外で高速を要求します。','Zero requests normal speed; nonzero requests fast speed.')],[shared,note('fast','転送中の速度は変更しません。外部クロック側ではこの設定を使いません。CGB対応を調べる機能はなく、サンプルは両側を同じ機種で動かします。','Does not change an in-flight transfer. External-clock transfers ignore this setting. Hardware support is not checked; run both sample endpoints on matching hardware modes.')])
add('Link_IsBusy','完了済みの転送を一度取り込んでから、送受信中か返します。','Poll once for completion, then report whether an exchange remains active.','1なら使用中、0ならアイドルです。','Returns 1 while busy, otherwise 0.','raw_master','result[3]=Link_IsBusy();result[4]=Link_HasByte();',notes=[ring,note('busyside','単なる状態読み取りではありません。完了していればSBをキューへ入れ、受信準備フラグやエラーも変わり得ます。','This is not a passive query: a completed SB byte is enqueued, which can change readiness and error state.')])
add('Link_HasByte','通常受信リングに未読バイトがあるか調べます。','Inspect whether the ordinary receive ring contains unread data.','未読があれば1、空なら0です。','Returns 1 when data is queued, otherwise 0.','raw_slave','result[1]=Link_HasByte();value=77;result[2]=Link_TryReadByte(&value);result[3]=value;',notes=[ring,note('nopoll','ハードウェアをポーリングしません。Link_Pollまたはシリアルハンドラーで転送完了を先に取り込みます。','Does not poll hardware. Collect completion through Link_Poll or the serial handler first.')])
add('Link_LastError','最後に記録された通信エラーを消さずに取得します。','Read the most recently latched link error without clearing it.','現在のエラーコード0～5です。','Returns the current error code, 0..5.','packet_master','result[2]=Link_LastError();Link_ClearError();result[3]=Link_LastError();',notes=[codes])
add('Link_ClearError','エラー表示だけを0に戻します。','Clear only the error latch.',*none,'control','Link_ClearError();result[8]=Link_LastError();',notes=[codes,note('clear','転送、キュー、パケットの状態はそのままです。停止が必要ならLink_Cancel、全体を破棄するなら初期化を使います。','Transfers, queues and packet state remain unchanged. Use Link_Cancel to stop the byte transfer, or initialize again to discard all state.')])
add('Link_BeginTransfer','1バイトをSBへ置き、1回の全二重交換を開始または待ち受けます。','Load SB and start or arm one full-duplex byte exchange.','開始できれば0、すでに使用中なら1です。','Returns 0 when started/armed, or 1 if already busy.','raw_master','lesson_delay(12);result[0]=Link_BeginTransfer(42);value=0;result[1]=Link_WaitByte(8,&value);result[2]=value;',[('out','相手へ送る8ビット値。受信だけが目的でも値を1つ送ります。','Eight-bit outgoing value; every exchange sends a byte even if only reception matters.')],[shared,codes,note('start','外部クロックの役割では相手がクロックを送るまで完了しません。使用中の再呼び出しは、送信中のバイトを置き換えません。','An external-clock endpoint waits for the other side to supply clocks. A busy rejection does not replace the byte already in flight.')])
add('Link_Poll','SCの開始ビットが消えた転送だけを取り込み、受信キューへ追加します。','Collect a busy transfer only after SC clears its start bit, and enqueue the received byte.',*none,'raw_slave','for(i=0;i<24;i++){Link_Poll();if(Link_HasByte())break;m_wait();}',notes=[ring,note('poll','1回の呼び出しで待ち続けることはありません。ソフトウェア上でアイドルなら何もしません。タイムアウトも設定しません。','A call does not block. It does nothing when software state is idle and does not implement a timeout.')])
add('Link_Cancel','実行中または外部クロック待ちのバイト転送を停止します。','Stop the active or externally clocked byte transfer.',*none,'control','Link_Cancel();result[12]=Link_IsBusy();result[13]=(SC&128)!=0;Link_ClearError();',notes=[critical,note('cancel','SCを0にし、使用中とシリアル要求を消します。受信済みバイト、パケット状態、エラーは消しません。プロトコルを最初からやり直す場合は初期化も行います。','Writes SC=0 and clears busy and serial-request state. Received bytes, packet state and errors remain. Reinitialize as well when restarting the protocol from scratch.')])
add('Link_OnSerialIRQ','シリアル要求を確認済みのハンドラーから、完了したバイトを取り込みます。','Collect a completed byte from a handler that has identified a serial request.',*none,'control','lesson_delay(2);result[14]=(IF_REG&8)!=0;Link_OnSerialIRQ();result[15]=Link_HasByte();result[16]=Link_ReadByte();result[17]=(IF_REG&8)!=0;',notes=[ring,critical,note('dispatch','この関数自身はSCの完了ビットを調べません。転送がまだ進行中のタイマー割り込み等から呼ばないでください。例は実際のIF.serial要求をCPU割り込み禁止中に確認して明示呼び出しし、関数本体を検証します。ベクターの設置例ではありません。','The function does not check SC for completion. Do not call it from an unrelated timer interrupt while serial transfer is active. This example explicitly dispatches after a real IF.serial request with the serial CPU IRQ source masked; it tests the body, not vector installation.')])
add('Link_TryReadByte','通常受信リングの先頭を、待たずに1バイト取り出します。','Pop one byte from the ordinary receive ring without waiting.','取り出せれば1、空なら0。空の場合outは変更しません。','Returns 1 when popped, 0 when empty; an empty read leaves out unchanged.','raw_slave','result[1]=Link_HasByte();value=77;result[2]=Link_TryReadByte(&value);result[3]=value;',[boolout],[ring,critical,duplicate])
add('Link_ReadByte','通常受信リングから1バイトを値として取り出します。','Return one byte popped from the ordinary receive ring.','受信値を返します。空の場合も0です。','Returns the received byte; an empty queue also returns zero.','raw_slave','result[6]=Link_HasByte();result[7]=Link_ReadByte();result[8]=Link_ReadByte();result[9]=Link_LastError();',notes=[ring,critical,note('zero','0を受信したのか空なのか、この戻り値だけでは判断できません。TryReadByteの成功値、または読み取り前のHasByteを使います。','The return value alone cannot distinguish a received zero from an empty queue. Use TryReadByte’s success flag, or HasByte before reading.')])
add('Link_WaitByte','直ちにポーリングし、必要ならVBlank単位で期限付き受信待ちをします。','Poll immediately, then wait for a byte with a VBlank-based limit.','取得できれば1。時間切れ、またはout=0なら0です。','Returns 1 on receipt, 0 on timeout or a null output.','control','value=77;result[9]=Link_WaitByte(2,&value);result[10]=value;result[11]=Link_LastError();',[('timeout_frames','最大のVBlank待ち回数。0でも最初のポーリングと取得を行います。','Maximum number of VBlank waits. Zero still performs the initial poll and read.'),('out','必須の1バイト書き込み先。0なら待たず、エラーも変更せず0を返します。','Required writable byte. Null returns zero immediately without changing the error latch.')],[ring,note('wait','LCDを動作させて使います。時間切れはエラー2を記録し、outを変更しません。転送そのものは停止しないため、終了する場合はCancelします。','Use with the LCD running. Timeout latches error 2 and leaves out unchanged. The transfer itself is not cancelled; call Cancel if abandoning it.')])
add('Link_SendPacket','送信内容を内部バッファへコピーし、パケット送信を予約します。','Copy the payload into owned storage and schedule packet transmission.','受付なら0、送信状態が空いていなければ1、不正な長さやポインターなら4です。','Returns 0 when accepted, 1 for busy packet state, or 4 for invalid length/pointer.','packet_master','result[0]=Link_SendPacket(data,3,0x31);data[1]=0;result[1]=Link_SendPacket(data,3,0x32);',sendargs,[codes,packet,polling,note('accepted','0は送信の受付です。相手による受信やACKの完了を意味しません。送信元配列は受付後に再利用できます。','Zero means queued, not received or acknowledged by the peer. The source array may be reused after acceptance.')])
add('Link_PollPacket','受信バイトを解析し、次の送信またはACKを開始して、期限と再試行を進めます。','Parse received bytes, start the next outgoing byte or ACK, and advance timeout/retry state.',*none,'packet_slave','Link_InitSlave();for(i=0;i<120;i++){Link_PollPacket();m_wait();}',notes=[packet,polling,note('nomix','同じ受信リングを直接のReadByte等でも読むと、パケットの途中を消費してしまいます。通常の生バイト読出しとパケット受信を同時に混ぜないでください。','Raw ReadByte-style calls consume the same ordinary ring and can steal part of a packet. Do not mix raw reads with packet reception.'),duplicate])
add('Link_HasPacket','通常の完成済みパケットメールボックスを調べます。','Inspect the shared completed-packet mailbox.','未読パケットがあれば1、空なら0です。','Returns 1 for an unread packet, otherwise 0.','packet_slave','result[0]=Link_HasPacket();cmd=0;len=0;result[1]=Link_ReadPacket(&cmd,&len,data);',notes=[packet,note('packetflag','プロトコルを進めず、フラグだけを読みます。送信相手がACKを受け取ったかどうかを示すフラグではありません。','Reads a flag without progressing the protocol. It does not indicate whether the sender has received its ACK.')])
add('Link_ReadPacket','完成済みパケットをコピーし、通常メールボックスを空にします。','Copy a completed packet and consume the shared mailbox.','取り出せれば1、空なら0。空では出力を書き換えません。','Returns 1 when consumed, 0 when empty; empty reads leave outputs unchanged.','packet_slave','result[0]=Link_HasPacket();cmd=0;len=0;result[1]=Link_ReadPacket(&cmd,&len,data);',outputs,[buffer,note('sharedmail','Link4の場合は、この共有パケットと同じ相手のメールボックスも空になります。他の相手のメールボックスは残ります。','In Link4 mode, also clears the peer mailbox corresponding to this shared packet. Other peer mailboxes remain available.')])
add('Link4_InitHost','2～4スロットの論理ホストとして初期化し、最初の相手を1にします。','Initialize a logical host with two to four slots and select peer 1.','設定できれば0、slot_countが範囲外なら4です。','Returns 0 for valid configuration, 4 for an invalid slot count.','four_host','result[0]=Link4_InitHost(4);result[1]=Link4_GetMode();result[2]=Link4_GetLocalSlot();result[3]=Link4_GetSlotCount();result[4]=Link4_GetSelectedPeer();',[('slot_count','ホスト自身を含むスロット数2～4。','Number of slots including the host, 2..4.')],[reset,logical,critical,note('invalidinit','設定の妥当性を調べる前に初期化します。失敗しても前の接続設定や未読データは残りません。','Initialization occurs before validation. A failed call still discards the previous topology and unread data.')])
add('Link4_InitPeer','指定スロットの外部クロック側として初期化し、相手をホスト0にします。','Initialize an externally clocked peer and select host slot 0.','設定できれば0。スロット数や自分の番号が不正なら4です。','Returns 0 for valid configuration, 4 for an invalid slot count/local slot.','four_peer1','result[0]=Link4_InitPeer(1,4);result[1]=Link4_GetMode();result[2]=Link4_GetLocalSlot();result[3]=Link4_GetSlotCount();result[4]=Link4_GetSelectedPeer();',[('local_slot','自分の番号1～slot_count−1。','Local slot, 1..slot_count−1.'),('slot_count','ホストを含む総数2～4。','Total slots including the host, 2..4.')],[reset,logical,critical,'link_note_invalidinit'])
for name,ja,en,rj,retn,code in [
('Link4_GetMode','論理的な接続の役割を取得します。','Read the configured logical role.','0=未設定、1=ホスト、2=相手です。','0=unconfigured, 1=host, 2=peer.','result[1]=Link4_GetMode();'),
('Link4_GetLocalSlot','自機に設定されたスロット番号を取得します。','Read this machine’s configured slot.','ホストは0、相手は1～3です。未設定時も0です。','Host is 0; peers are 1..3. Unconfigured state also returns 0.','result[2]=Link4_GetLocalSlot();'),
('Link4_GetSlotCount','設定された総スロット数を取得します。','Read the configured total slot count.','有効な設定は2～4、未設定は0です。','Valid configurations return 2..4; unconfigured returns 0.','result[3]=Link4_GetSlotCount();'),
('Link4_GetSelectedPeer','次の交換で使う論理的な宛先を取得します。','Read the currently selected logical destination.','ホストでは選択中の相手、相手では0、未設定では255です。','Host returns its selected peer; a peer returns 0; unconfigured returns 255.','result[4]=Link4_GetSelectedPeer();'),
('Link4_GetLastRxPeer','最後に完了したバイトを割り当てた相手番号を取得します。','Read the peer attributed to the last completed byte.','ホストは選択相手、相手は0。まだ受信していなければ255です。','Host returns the selected peer and a peer returns 0; before reception returns 255.','result[19]=Link4_GetLastRxPeer();'),
('Link4_GetLastTxPeer','最後のバイト転送を開始した時点の宛先を取得します。','Read the destination recorded when the last byte transfer started.','記録済みの宛先番号。開始前は255です。','Returns the recorded destination, or 255 before any start.','result[20]=Link4_GetLastTxPeer();')]:
 add(name,ja,en,rj,retn,'four_host',code,notes=[logical,note('notdetect','これらは設定や転送履歴の読み取りです。実物の接続検出、全相手への問い合わせ、転送完了待ちは行いません。','These are configuration/history getters. They do not detect physical connections, query every peer or wait for transfer completion.')])
add('Link4_SelectPeer','未完了の交換がないことを確かめ、次の論理的な宛先を変更します。','Poll completion and change the logical destination only while idle.','選択できれば0、バイト/パケット/ACKが使用中なら1、未設定や不正な相手なら4です。','Returns 0 on selection, 1 for busy byte/packet/ACK state, or 4 for an unconfigured/invalid peer.','four_host','result[25]=Link4_SelectPeer(1);result[26]=Link_LastError();',[peer],[logical,codes])
add('Link4_BeginTransferTo','宛先を選んでから1バイトの交換を開始します。','Select a destination, then start one byte exchange.','選択または開始時の最初のエラー。成功は0です。','Returns the first selection/start error, or 0 on success.','four_host','result[6+slot]=Link4_BeginTransferTo(slot,16+slot);',[peer,('out','送る8ビット値。','Outgoing eight-bit value.')],[logical,codes,duplicate])
add('Link4_HasByteFrom','指定相手の受信リングに未読バイトがあるか調べます。','Inspect unread data in one peer’s receive ring.','データがあれば1、空または不正な相手なら0です。','Returns 1 for queued data, 0 for empty/invalid peer.','four_host','result[9+slot]=Link4_HasByteFrom(slot);value=0;',[peer],[ring,duplicate,note('peernopoll','この問い合わせはハードウェアをポーリングせず、不正な相手でもエラーラッチを変更しません。','This query does not poll hardware; an invalid peer does not change the error latch.')])
add('Link4_TryReadByteFrom','指定相手の受信リングから1バイトを取り出します。','Pop one byte from a specific peer’s receive ring.','取り出せれば1。空または不正な相手なら0で、outはそのままです。','Returns 1 on a pop; empty/invalid peer returns 0 and preserves out.','four_host','if(slot==1)result[13]=Link4_TryReadByteFrom(slot,&value);',[peer,boolout],[ring,duplicate,critical])
add('Link4_TryReadByteAny','番号の小さい相手から順に調べ、最初に見つかった1バイトを取り出します。','Scan remote slots in ascending order and pop the first available byte.','取得できれば1、どこにもなければ0です。','Returns 1 on receipt, otherwise 0.','four_host','else {other=255;Link4_TryReadByteAny(&other,&value);result[12+slot]=other;}',[('peer_slot','受信元を書き込む1バイト。0なら番号の出力を省略します。','Writable origin-slot byte; null omits the origin output.'),boolout],[ring,duplicate,critical,note('priority','自分のスロットは飛ばします。番号の小さい相手に未読が続くと大きい相手より先に返るため、公平な巡回が必要なら相手別の取得を使います。','Skips the local slot. Continuously queued lower slots take priority; use per-peer reads when round-robin fairness is required.')])
add('Link4_SendPacketTo','宛先を選択し、その相手へのパケットをコピーして予約します。','Select a logical peer, copy the packet and schedule its transmission.','選択または予約時の最初のエラー。受付は0です。','Returns the first selection/queueing error; 0 means accepted.','four_host','result[21+slot]=Link4_SendPacketTo(slot,data,3,64+slot);',[peer]+sendargs,[logical,codes,packet,polling,duplicate,note('sendselect','選択に成功してから長さ等を調べるため、内容が不正で予約に失敗しても、宛先だけは変更される場合があります。','Selection happens before payload validation; a rejected payload can still leave the new destination selected.')])
add('Link4_PollPacket','共通のパケット処理を、現在の接続先に対して1回進めます。','Advance the shared packet engine once for the currently selected peer.',*none,'four_host','for(i=0;i<50;i++){Link4_PollPacket();while(Link4_TryReadByteFrom(slot,0)){}m_wait();}',notes=[logical,packet,polling,duplicate,note('oneroute','全スロットを順番に選ぶ処理は含まれません。相手を切り替えるのは、送受信が完了して選択可能になってからです。','Does not rotate across all slots. Change peers only after the exchange has finished and selection is permitted.')])
add('Link4_HasPacketFrom','指定相手の完成済みパケットメールボックスを調べます。','Inspect the completed-packet mailbox for one remote slot.','未読があれば1、空または不正な相手なら0です。','Returns 1 for an unread packet, 0 for empty/invalid peer.','four_peer1','result[9]=Link4_HasPacketFrom(0);result[10]=Link4_ReadPacketFrom(0,&cmd,&len,data);',[peer],[logical,packet,'link_note_peernopoll'])
add('Link4_ReadPacketFrom','指定相手のパケットをコピーし、そのメールボックスを消費します。','Copy a packet from a specific peer and consume its mailbox.','取得できれば1、空または不正な相手なら0です。','Returns 1 when consumed, 0 for empty/invalid peer.','four_peer1','result[9]=Link4_HasPacketFrom(0);result[10]=Link4_ReadPacketFrom(0,&cmd,&len,data);',[peer]+outputs,[buffer,note('peermail','通常メールボックスがこの相手のパケットを指している場合だけ、通常側も消します。他の相手の未読パケットは保持します。','Clears the shared mailbox only when it refers to this same peer’s packet. Unread packets from other peers remain available.')])
contracts['gb:Link_PollPacket']['example']['additional']=[{'program':specs['deadline']['source'],'code':(SITE/specs['deadline']['source']).read_text(encoding='utf-8').split('u16 ticks;',1)[1].split('m_wait();M_LCDC',1)[0].strip(),'build':build_commands('deadline'),'expected':[message('example_deadline',*examples['deadline'])]}]
launch=note('launch','コマンドはkitaqgb・kokura・kitaq-docsを同じ親フォルダーに置き、その親でPowerShellを開いて実行します。接続する全ROMをビルドしてからまとめて起動します。Link4では出力されたシンボル等のメタデータをROMの隣に残してください。初代GBで確認する場合は全コマンドの--cgb=cgbを--cgb=dmg、--hardware cgbを--hardware dmgへ変更します。','Run these PowerShell commands from the parent containing kitaqgb, kokura and kitaq-docs. Build every participating ROM before launching the linked session. For Link4, retain the generated symbol metadata beside the ROMs. For DMG runs, change --cgb=cgb to --cgb=dmg and --hardware cgb to --hardware dmg throughout.')
for contract in contracts.values():contract['notes'].append(launch)
assert len(contracts)==37
for n,v in [('link_contracts.json',contracts),('link_texts.json',texts),('link_modules.json',{'gb:link':[message('module','このライブラリは、バイト交換、最大24バイトのパケット、接続先別キューの3層で通信を扱います。まずBYTE MASTER/SLAVEを動かし、次にPACKET、最後にLINK4へ進むと、クロックと受信待ちの関係を確認できます。ハードウェアレジスタ定義、link.c、link_packet.cは同じプログラムに1回ずつ組み込みます。サンプルのgb_link_example.hがこの順序をまとめています。','The library provides three layers: byte exchanges, packets of up to 24 bytes, and peer-specific queues. Start with BYTE MASTER/SLAVE, then PACKET, then LINK4 to learn clock ownership and receive readiness. Include the hardware-register unit, link.c and link_packet.c exactly once in a program; gb_link_example.h supplies that order.'),logical,polling]}),('link_review_sources.json',{'source_sha256':source_hashes,'records':records})]:
 (HERE/n).write_text(json.dumps(v,ensure_ascii=False,indent=2),encoding='utf-8')
(SITE/'reference/gb-api.json').write_text(json.dumps(dataset,ensure_ascii=False,indent=2),encoding='utf-8')
print('37 individually authored link contracts')
