"""Author FDS register, compiled-metadata and residency queries from final code."""
from pathlib import Path
import hashlib,json
HERE=Path(__file__).resolve().parent;SITE=HERE.parents[1];REPOS=SITE.parents[1]/'publish/github_20260912'
if not REPOS.is_dir():REPOS=SITE.parent
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
texts={};contracts={}
def msg(key,ja,en):
    key='fds_query_'+key;texts[key]={'ja':ja,'en':en};return key
none=msg('none','戻り値はありません。','No return value.')
mapper=msg('mapper','`--mapper=fds`でビルドしてください。`__fds_available`以外のFDS専用関数をカートリッジ向けに呼ぶと、KQFC2420でビルドを拒否します。','Build with `--mapper=fds`. Calling an FDS-only function other than `__fds_available` for a cartridge mapper is rejected with KQFC2420.')
boundary=msg('boundary','掲載画像はKUROSAKIでディスクの起動ファイルをRAMへ直接配置して確認したものです。このサンプルはBIOSを呼ばず、ファイルの読み書き、ディスク交換、実機での起動を検証していません。検証用の空のファームウェアはBIOSの代用品ではありません。サンプルは画面更新用NMIを使い、不要なマスク可能IRQを無効にしています。','The capture uses KUROSAKI’s direct loading of disk boot files into RAM. This sample calls no BIOS routine and does not verify file transfers, disk swapping or boot on hardware. The empty test firmware is not a replacement BIOS. The sample uses NMI for display updates and disables maskable IRQs, which these queries do not need.')
buildnote=msg('buildnote','ビルド例ではBIOSの起動画面用の追加ファイルを付けず、ネイティブFDS配置の`.fds`を作ります。KUROSAKIの直接起動で確認するための構成です。実機用ディスクの起動手順は、これとは別に確認してください。','The build example produces a native-layout `.fds` without the extra approval-screen boot files. This configuration is for checking KUROSAKI direct boot; a hardware disk’s boot procedure needs separate validation.')
blocked=msg('blocked','タイムアウトはありません。ディスクが入っていなければ戻らず、画面更新や入力処理を続けたい場合は`__fds_disk_ready()`を各フレームで調べてください。サンプルは先に存在を確認し、入っている場合だけ待機関数を呼びます。挿入済みなら、新たな抜き差しは待ちません。','There is no timeout. An absent disk leaves the call blocked. Poll `__fds_disk_ready()` once per frame if the game must keep updating its display or accepting input. The sample checks presence before entering either wait. An already-inserted disk satisfies the wait without a new removal/insertion cycle.')
notready=msg('notready','判定対象は$4032のビット0（ディスクの有無）です。ビット1の転送準備状態、ファイルの存在、ロード完了は確認しません。名前のreadyを「読み書きを開始できる」と解釈しないでください。','The test uses $4032 bit 0, which reports disk presence. It does not check bit 1’s drive readiness, file existence or load completion. The word “ready” here must not be taken as permission to start a transfer.')
statusmodel=msg('statusmodel','KUROSAKIのFDSコントローラーは簡易モデルです。この例では挿入状態が1、書き込み禁止マスクが0、ステータスが0になりますが、未挿入・保護付きディスク・CRC異常への応答はこの画面で確認したことにはなりません。','KUROSAKI uses a partial FDS controller model. This example observes presence 1, protection mask 0 and status 0; the capture does not establish behavior for ejection, protected media or CRC errors.')
status_expected=msg('status_expected','PRESENT / PROTECT / STATUSの下に1 / 0 / 0、COMPLETED PRESENCE WAITSの下に2が出ます。二つの待機関数が戻ったことを示し、ファイル転送の成功表示ではありません。最下部にもNO FILE TRANSFER TESTEDと表示します。','Under PRESENT / PROTECT / STATUS the screen shows 1 / 0 / 0, followed by 2 under COMPLETED PRESENCE WAITS. Both presence waits returned; this is not a file-transfer success indicator. NO FILE TRANSFER TESTED is shown below.')
available_expected=msg('available_expected','FDS向けでは001、NROM向けでは000を表示します。同じCソースでもビルド時の対象によって値が変わり、ディスクの有無を調べているわけではないことを示します。','The FDS build displays 001; the NROM build displays 000. The same C source returns a different value according to the compilation target, independently of whether a disk is inserted.')
metadata_expected=msg('metadata_expected','表のID 16は存在1・513バイト、ID 17は存在1・0バイト、ID 18は存在0・0バイトです。TABLE VALUES MATCH: PASSは取得値をこの組み合わせと比較した結果です。サイズ0だけでは「空のレコード」と「該当なし」を区別できないことを示します。','The table shows ID 16 as present with 513 bytes, ID 17 as present with zero bytes, and ID 18 as absent with zero bytes. TABLE VALUES MATCH: PASS compares the retrieved values with this combination. A size of zero alone cannot distinguish an empty record from a missing ID.')
resident_expected=msg('resident_expected','CURRENT BANKは1、BANK 1 RESIDENTは1、BANK 2 RESIDENTは0、OVERLAY FUNCTIONSは2です。バンク2に二つの関数を収録していても、起動直後にバンク2がロード済みになるわけではありません。`--fds-no-overlay-table`を付けた検証では最後の値だけ0になります。','CURRENT BANK is 1, BANK 1 RESIDENT is 1, BANK 2 RESIDENT is 0 and OVERLAY FUNCTIONS is 2. Packaging two functions in bank 2 does not make that bank resident at startup. In the verification build with `--fds-no-overlay-table`, only the last value changes to zero.')
idarg=msg('id','検索するファイルID。管理表では0～254を使い、255は終端用です。ファイル番号、ファイル名、ロード先アドレスとは別の値です。','File ID to look up. Metadata uses IDs 0..254; 255 is reserved as the terminator. An ID is distinct from a file number, filename or destination address.')
meta=msg('meta','`--fds-meta=...`または`--fds-manifest=...`で指定した管理表と、自動生成したオーバーレイのレコードを検索します。ディスクのディレクトリは読みません。管理表にレコードがないファイルは、ディスクに収録されていても見つかりません。手動レコードと自動レコードの合計は42件までです。','Searches the compiled table from `--fds-meta=...` or `--fds-manifest=...`, together with generated overlay records. It does not read a disk directory. A file without a table record is not found even if it is packaged on disk. Manual and generated records together are limited to 42.')
metasize=msg('metasize','返すサイズは管理表の宣言値です。sourceファイルから推定した実際の長さ、オーバーレイ末尾の切り詰め後の長さ、交換したディスクの内容と一致するとは限りません。実データの範囲確認には正しいサイズを管理表へ指定してください。','The size is the metadata’s declared value. It need not equal the inferred length of a source file, a trimmed overlay’s payload length or the contents of a swapped disk. Declare accurate sizes when using these queries to bound data access.')
resident=msg('resident','FDSの標準起動処理は常駐記録を1で初期化します。`__fds_load_bank()`はロード成功時に記録を更新します。`__fds_load_file()`または`__fds_load_overlay()`による直接ロード、およびバンク転送の失敗では記録が255（不明）になります。メモリ内容の照合は行わないため、直接メモリを書き換える場合は記録に依存しないでください。独自のリセット処理を用意する場合は初期化も自分で管理します。','The standard FDS startup initializes the residency record to 1. `__fds_load_bank()` updates it after a successful load. Raw loads through `__fds_load_file()` or `__fds_load_overlay()`, and failed bank transfers, set the record to 255 (unknown). No memory contents are checked; do not rely on the record after modifying the window directly. A custom reset routine must manage initialization itself.')
bankarg=msg('bank','比較する論理バンク番号。標準起動時の記録は1、自動オーバーレイは2以降です。0は共通コードのバンクであり、この常駐記録の初期値ではありません。','Logical bank number to compare. Standard startup records 1; generated overlays use 2 and above. Bank 0 holds common code and is not the startup value of this residency record.')
records={r['name']:r for r in json.loads((SITE/'reference/fc-api.json').read_text(encoding='utf-8'))['records']}
def add(name,lesson,ja,en,args,returns,notes):
    r=records[name];program='samples/api-examples/fc/fds_'+lesson+'.c';src=(SITE/program).read_text(encoding='utf-8');code=src[src.index('void main'):].strip()
    build='New-Item -ItemType Directory -Force .\\out | Out-Null\n.\\kitaqfc\\kitaqfc.exe .\\kitaq-docs\\'+program.replace('/','\\')+' -I .\\kitaqfc\\lib -I .\\kitaq-docs\\samples -o .\\out\\fds_'+lesson+'.fds --mapper=fds --fds-layout=fds32 --fds-no-license-bypass --nes-chr=.\\kitaq-docs\\samples\\font.chr --no-cache --no-disasm'
    if lesson=='metadata':build+=' --fds-meta=.\\kitaq-docs\\samples\\api-examples\\fc\\fds_metadata.json'
    if lesson=='available':build+='\n# Cartridge comparison\n.\\kitaqfc\\kitaqfc.exe .\\kitaq-docs\\'+program.replace('/','\\')+' -I .\\kitaqfc\\lib -I .\\kitaq-docs\\samples -o .\\out\\fds_available.nes --mapper=nrom --nes-chr=.\\kitaq-docs\\samples\\font.chr --no-cache --no-disasm'
    fingerprint=hashlib.sha256(json.dumps({k:r.get(k) for k in ['name','signature','comment','definition','implementation_excerpt']},sort_keys=True).encode()).hexdigest()
    contracts['fc:'+name]=dict(review='fds-query-source-20260923',record_sha256=fingerprint,purpose=[msg(name+'_purpose',ja,en)],args=args,returns=returns,notes=notes+[boundary,buildnote],example=dict(program=program,code=code,build=build,expected=[dict(available=available_expected,status=status_expected,metadata=metadata_expected,residency=resident_expected)[lesson]]))
add('__fds_available','available','ビルド対象がFDSかどうかを返します。共通のゲームコードで対象別の案内を表示する場合に使います。','Report whether the compilation target is FDS, for example when displaying target-specific information in shared game code.',[],[msg('available_return','FDS向けなら1、それ以外なら0。実行時に周辺機器を検出する処理ではありません。','1 for an FDS build, otherwise 0. This is not runtime peripheral detection.')],[msg('available_note','この関数はNROMなどのカートリッジ向けにも使用できます。ただし、`if (__fds_available())`の中にFDS専用APIを書いても、そのAPIの対象制限を回避できるわけではありません。対象別のビルドではソースの構成も分けてください。','This query is valid for cartridge targets such as NROM. Placing an FDS-only API inside `if (__fds_available())` does not exempt that API from target checks; arrange target-specific source accordingly.')])
add('__fds_disk_ready','status','ディスクが挿入されているかを、その場で調べて返します。挿入待ちの画面で毎フレーム呼ぶなど、処理を止めずに存在を確認できます。','Check disk presence immediately, allowing an insertion prompt to poll once per frame without blocking.',[],[msg('ready_return','$4032のビット0が0なら1、1なら0を返します。','Returns 1 when $4032 bit 0 is clear and 0 when it is set.')],[mapper,notready,statusmodel])
add('__fds_side','status','$4032の書き込み禁止ビットをマスクして返します。この関数はディスクのA面／B面を識別しません。','Return the masked write-protection bit from $4032. This function does not identify disk side A or B.',[],[msg('side_return','$4032 & 0x04。0または4であり、0/1の真偽値ではありません。ハードウェア上のビット2は書き込み禁止または未挿入を示します。','Returns $4032 & 0x04: either 0 or 4, not a normalized Boolean. Hardware bit 2 indicates write protection or an ejected disk.')],[mapper,statusmodel,msg('side_note','保存処理で使うなら`(__fds_side() != 0)`と比較します。ただし、保存可能かどうかはディスクの存在やBIOSの戻り値も含めて判断してください。','For a protection test, use `(__fds_side() != 0)`. Disk presence and the BIOS operation’s return value are also needed to decide whether saving succeeds.')])
add('__fds_error','status','FDSのハードウェアステータスレジスター$4030を読みます。ディスク操作の前回エラーを保存しておく変数ではありません。','Read the FDS hardware status register at $4030. This is not a stored error from the last disk operation.',[],[msg('error_return','$4030の8ビット値をそのまま返します。BIOSのエラーコードは`__fds_load_file()`や`__fds_save_file()`の戻り値を保存して扱ってください。','Returns the entire eight-bit $4030 value. Preserve the return value of `__fds_load_file()` or `__fds_save_file()` when handling BIOS error codes.')],[mapper,statusmodel,msg('error_note','ステータスの読み取りは割り込み要求の確認応答にもなります。別の割り込み処理が同じ状態を使う場合、無計画にポーリングしないでください。KUROSAKIでは、この読み取りで保留中のFDS IRQフラグが解除されます。','Reading status also acknowledges interrupt requests. Do not poll indiscriminately if another handler relies on the same status. KUROSAKI clears its pending FDS IRQ flag on this read.')])
for name,ja,en in [('__fds_wait_ready','ディスクが挿入されるまでCPUで待ちます。','Wait in a CPU polling loop until a disk is present.'),('__fds_wait_insert','ディスク挿入待ちを表す呼び出し名です。`__fds_wait_ready()`と同じ存在判定ループを呼びます。','Express a disk-insertion wait. Calls the same presence-polling loop as `__fds_wait_ready()`.')]:add(name,'status',ja,en,[],[none],[mapper,notready,blocked,statusmodel])
add('__fds_file_exists','metadata','指定IDのレコードが、コンパイル済みのファイル管理表にあるかを調べます。サイズ0のレコードも「存在する」と判定します。','Check whether the compiled file metadata contains the requested ID. A zero-size record still counts as present.',[['id',[idarg]]],[msg('exists_return','管理表にあれば1、なければ0。挿入中ディスクの内容についての保証ではありません。','1 when the compiled table contains the ID, otherwise 0. This does not guarantee that the inserted disk contains that file.')],[mapper,meta,metasize])
add('__fds_file_size','metadata','指定IDに対して管理表へ登録されたバイト数を返します。ロード予定の資産の宣言サイズを調べる用途です。','Return the byte size declared for an ID in compiled metadata, for example when inspecting an asset’s planned load size.',[['id',[idarg]]],[msg('size_return','登録された16ビット符号なしサイズ（0～65535）。該当IDがない場合も0です。必要に応じて`__fds_file_exists()`を併用します。','The declared unsigned 16-bit size, 0..65535. Missing IDs also return zero; use `__fds_file_exists()` when that distinction matters.')],[mapper,meta,metasize])
add('__fds_current_bank','residency','現在ロード済みとして記録されている論理バンク番号を返します。ディスクから読み直す操作は行いません。','Return the logical bank recorded as resident, without reading anything from disk.',[],[msg('current_return','ソフトウェアが保持する8ビットの常駐バンク番号。標準起動直後は1、不明な状態では255です。','The eight-bit software residency record; 1 immediately after standard startup, or 255 when unknown.')],[mapper,resident])
add('__fds_is_bank_resident','residency','指定バンクが常駐記録と一致するかを調べます。ロードが必要か判断する前に使えますが、この関数自体はロードしません。','Compare a requested bank with the residency record. It can help decide whether a load is needed, but does not perform one.',[['bank',[bankarg]]],[msg('is_return','有効な番号が記録と一致すれば1、それ以外は0。255（不明）は記録が255でも0です。','1 if a valid bank matches the record, otherwise 0. Bank 255 (unknown) always returns zero, even when the record is 255.')],[mapper,resident])
add('__fds_overlay_function_count','residency','リンク時にオーバーレイバンク（2以降）へ配置された関数の件数を返します。ロード済みの件数やファイル数ではありません。','Return the number of functions placed in overlay banks 2 and above by the linker. This is neither a resident-function count nor a file count.',[],[msg('count_return','関数表の先頭バイト（0～255）。該当関数がない場合や`--fds-no-overlay-table`を指定した場合は0です。255件を超える表はKQFC2511で拒否します。','The table’s leading count byte, 0..255. Zero when there are no overlay functions or `--fds-no-overlay-table` is used. More than 255 entries are rejected with KQFC2511.')],[mapper,msg('count_note','コード生成では0の仮データを置き、ネイティブFDS配置のリンク時に、バンク・アドレスが確定した関数表へ置き換えます。サンプルの二つの関数はバンク2へ収録されますが呼びません。`--fds-layout=legacy`の初期データだけを見て関数数を判断しないでください。','Code generation creates a zero placeholder; native FDS linking replaces it with the table after bank/address placement. The sample packages two functions in bank 2 without calling them. The initial data in `--fds-layout=legacy` is not a census of overlay functions.')])
for name in ['__fds_side','__fds_error','__fds_disk_ready','__fds_wait_ready','__fds_wait_insert']:
    contracts['fc:'+name]['references']=[dict(title='NESdev: FDS hardware registers',url='https://www.nesdev.org/wiki/Famicom_Disk_System')]
fixture=msg('metadata_fixture','サンプルの`fds_metadata.json`と二つの`.bin`ファイルはCソースと同じフォルダーに置きます。ID 16の独自データは0～255を2回と末尾0の513バイト、ID 17のデータは空です。両方ともPRG形式（type 0）の非起動ファイルとして収録し、この例ではロードしません。sourceの相対パスは管理表のあるフォルダーを基準に解決します。','Keep `fds_metadata.json` and its two `.bin` files beside the C source. ID 16 contains an original 513-byte sequence: 0..255 twice, then zero. ID 17 has an empty payload. Both are non-boot PRG files (type 0), and this lesson does not load them. Relative source paths are resolved from the manifest’s directory.')
for name in ['__fds_file_exists','__fds_file_size']:contracts['fc:'+name]['notes'].insert(3,fixture)
review={'source_sha256':{p:sha(REPOS/p) for p in ['kitaqfc/kitaqfc/CodeGenerator.cs','kitaqfc/kitaqfc/BankedAssemblerCore.cs','kitaqfc/kitaqfc/FdsDiskMetadata.cs','kitaqfc/kitaqfc/FdsDiskImageBuilder.cs','kitaqfc/lib/fds.h','kitaqfc/lib/fds_file.h','kitaqfc/lib/fds_overlay.h','kitaqfc/lib/intrinsics.h']}}
for name,value in [('fds_query_contracts.json',contracts),('fds_query_texts.json',texts),('fds_query_review_sources.json',review)]:
    (HERE/name).write_text(json.dumps(value,ensure_ascii=False,indent=2),encoding='utf-8')
print(len(contracts),'FDS query contracts authored in JA/EN')
