"""Source-reviewed bilingual contracts for the third 100-item batch."""
from pathlib import Path
import hashlib,json,sys
import re as regex
HERE=Path(__file__).resolve().parent;SITE=HERE.parents[1];REPOS=SITE.parents[1]/'publish/github_20260912'
if not REPOS.exists():REPOS=SITE.parent
sys.path.insert(0,str(SITE/'tools'));import catalog
catalog.ROOT=REPOS
texts={};contracts={};sources={};reviews={};modules={};auth={}
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def msg(key,ja,en):
    key='b300_'+key
    if key in texts:assert texts[key]=={'ja':ja,'en':en},key
    texts[key]={'ja':ja,'en':en};return key
def pair(key,ja,en):return [msg(key,ja,en)]
def note(key,ja,en):return msg(key,ja,en)
def add(p,n,g,ja,en,retja,reten,args=(),notes=()):
    key=p+':'+n
    auth[key]={'group':g,'purpose':pair(key+'_purpose',ja,en),'returns':pair(key+'_returns',retja,reten),'args':[[a,pair(key+'_'+a,j,e)] for a,j,e in args],'notes':list(notes)}
def gb(n,g,ja,en,rj='戻り値はありません。',re='No return value.',args=(),notes=()):add('gb',n,g,ja,en,rj,re,args,notes)
def fc(n,g,ja,en,rj='戻り値はありません。',re='No return value.',args=(),notes=()):add('fc',n,g,ja,en,rj,re,args,notes)
cell=note('cell','座標はピクセルではなく現在のマップのセルです。通常マップは8×8ピクセル、メタタイルマップは16×16ピクセルで1セルです。','Coordinates address cells in the current map: 8×8 pixels for ordinary tiles, 16×16 pixels for metatiles.')
maplife=note('maplife','有効なマップは全体で1つです。記述子はコピーしますが、配列は必要な間ずっと読み取り可能にします。画像のタイルデータは別途VRAMへ読み込んでください。','There is one shared active map. The descriptor is copied, but its arrays must remain readable for as long as needed. Load tile graphics into VRAM separately.')
pathlimits=note('pathlimits','探索は共有の約4KiB作業領域を使い、再入できません。マップは1024セル以下、探索する距離は254以下にします。0xFFは未到達を表すため、255歩の経路は扱えません。出力配列は現在のマップの幅×高さバイトを用意します。','Search uses about 4 KiB of shared, non-reentrant workspace. Limit maps to 1024 cells and explored distances to 254. Distance 0xFF means unreached, so a 255-step route is not representable. Cost/mask outputs need width*height writable bytes.')
xy=[('x','セルのX座標。','Cell X coordinate.'),('y','セルのY座標。','Cell Y coordinate.')]
tx=[('tx','メタタイルのX座標。','Metatile X coordinate.'),('ty','メタタイルのY座標。','Metatile Y coordinate.')]
gb('map_load','map_path','通常マップの記述子を読み込み、左上の最大20×18タイルを現在の背景マップへ描きます。','Load an ordinary-map descriptor and draw up to 20×18 tiles from its upper-left corner into the selected background map.',args=[('bank','記述子・衝突ビット・イベント配列を置くROMバンク。','ROM bank for the descriptor, collision bits and events.'),('map','9バイトのpacked map_t。tilesは幅×高さのタイル番号、collision_bitsは下位ビットからのビット列、eventsはセルごとの1バイトです。タイル配列はbank_tilesを使います。','Packed nine-byte map_t. tiles contains width*height tile IDs; collision_bits packs cells least-significant bit first; events stores one byte per cell. Tile reads use bank_tiles.')],notes=[maplife,cell,note('map_small','小さいマップの外側は消去しません。bank_tiles=0は通常マップではバンク0を表し、記述子のバンクの継承指定ではありません。','Cells outside a small map are not cleared. For ordinary maps, bank_tiles=0 means bank zero; it does not inherit the descriptor bank.')])
gb('map_is_blocked','map_path','移動先セルの衝突情報を調べます。メタタイルモードでは定義のcollisionを使います。','Test whether a destination cell blocks movement; metatile mode uses the definition’s collision field.','障害物・範囲外・マップ未設定は1、通行可能なら0。通常マップの衝突配列がNULLなら範囲内は0です。','Returns 1 for a wall, outside coordinate or missing map; 0 for passable cells. A NULL ordinary collision array makes all in-bounds cells passable.',xy,[cell])
gb('map_trigger_at','map_path','セルにイベントが設定されているかを調べます。イベントの実行は行いません。','Check whether a cell has an event, without executing it.','設定ありで1、それ以外は0。通常マップのイベント値やメタタイルのイベントIDそのものは返しません。','Returns 1 if an event is present, otherwise 0; does not return the stored event byte or metatile event ID.',xy,[cell])
gb('camera_center','map_path','通常マップの対象セルを20×18タイルの画面中央へ寄せ、マップ端でスクロールを止めます。','Center an ordinary-map cell in a 20×18-tile viewport, clamping at map edges.',args=xy,notes=[note('center','原点はmax(x−10,0), max(y−9,0)をマップ端で制限し、8倍した下位8ビットをSCX/SCYへ書きます。メタタイルモードでは反映しません。新しい行や列をVRAMへ転送する機能はありません。','The origin starts at max(x−10,0), max(y−9,0), clamps to map edges, then writes the low bytes of origin*8 to SCX/SCY. Metatile mode does not apply it. It does not stream new rows or columns into VRAM.')])
for n,axis in [('map_current_width','width'),('map_current_height','height')]:
    j='幅' if axis=='width' else '高さ'
    gb(n,'map_path','現在のマップの'+j+'を取得します。','Read the active map’s '+axis+'.','セル単位の'+j+'。未設定なら0です。','Returns '+axis+' in cells, or zero if no map is loaded.',notes=[cell])
gb('map_load_metatile','metatile','メタタイルマップを選択し、カメラ(0,0)から10×9セルを20×18タイルへ展開します。','Select a metatile map and expand a 10×9-cell viewport at camera (0,0) into 20×18 tiles.',args=[('bank','記述子を置くROMバンク。','ROM bank containing the descriptor.'),('map','metatile_map_tへのポインタ。幅・高さは16×16セル数。ID配列と7バイトのmetatile_t定義表を参照します。','Pointer to metatile_map_t. Dimensions count 16×16 cells. It references an ID array and a table of seven-byte metatile_t definitions.')],notes=[maplife,note('meta_bank','bank_tilesが0なら記述子のバンクを使い、0以外ならID配列・定義表の両方にそのバンクを使います。定義は左上・右上・左下・右下のタイル、collision、palette、eventの順です。paletteは描画時に自動適用しません。','bank_tiles=0 inherits the descriptor bank; a nonzero value selects the bank for both IDs and definitions. A definition stores top-left, top-right, bottom-left, bottom-right tiles, collision, palette and event. Drawing does not automatically apply palette metadata.')])
gb('map_draw_visible','metatile','指定したメタタイル原点から10×9セルを背景へ描き、再描画用のカメラ位置を記憶します。','Draw 10×9 metatiles from the requested origin and remember that camera position for dirty redraws.',args=[('camera_tx','左上セルのX。加算が8ビットで周回しないよう246以下にします。','Leftmost cell X; keep at most 246 to avoid byte wrap during traversal.'),('camera_ty','上端セルのY。247以下にします。','Topmost cell Y; keep at most 247.')],notes=[note('meta_zero','範囲外セルはメタタイルID 0で描きます。定義0を必ず用意してください。背景の20×18タイル以外とCGB属性は変更しません。','Outside cells draw metatile ID zero, so always supply definition zero. The call leaves cells outside the 20×18 tile viewport and CGB attributes unchanged.')])
for n,ja,en,rj,re in [
('map_get_metatile','セルのメタタイルIDを読みます。','Read a cell’s metatile ID.','IDを返します。範囲外・未設定は0です。','Returns the ID, or zero outside the map or without metatile mode.'),
('map_get_attr','セルの定義にあるpaletteメタデータを読みます。','Read palette metadata from the cell’s metatile definition.','paletteの1バイト。範囲外は定義0の値、メタタイル未設定は0です。','Returns the palette byte. Outside cells use definition zero; without metatile mode returns zero.'),
('map_is_solid','セルが壁かを調べ、通常マップでは衝突ビットへ処理を委ねます。','Test solidity, delegating to collision bits in ordinary-map mode.','collisionが非0または範囲外なら1、通行可能なら0です。','Returns 1 for nonzero collision or an outside cell, otherwise 0.'),
('map_get_event','メタタイルのイベントIDを読みます。通常マップではイベントの有無を調べます。','Read a metatile event ID; ordinary maps report event presence.','メタタイルはeventの値、通常マップは0/1。未設定・範囲外は0です。','Returns the metatile event byte or ordinary-map Boolean; missing/outside cells return zero.')]:gb(n,'metatile',ja,en,rj,re,tx,[cell])
gb('map_mark_dirty','metatile','有効なメタタイル座標を指定して、画面全体の再描画を予約します。','Mark the viewport for redraw when given a valid metatile coordinate.',args=tx,notes=[note('dirty','1セルだけの更新キューではなく、共有のdirtyフラグを立てます。範囲外は無視します。IDや定義そのものは変更せず、呼び出し側が先に書き換えます。','Sets one shared dirty flag rather than queuing a per-cell update. Outside coordinates are ignored. The caller changes IDs or definitions separately before marking dirty.')])
gb('map_flush_dirty','metatile','再描画が予約されていれば、保存済みカメラ位置から表示範囲を描き直して予約を解除します。','If dirty, redraw the viewport at its saved camera origin and clear the dirty flag.',notes=[note('flush','dirtyでなければ何もしません。描画対象は10×9メタタイル全体で、変更セルだけではありません。','Does nothing when clean. A dirty redraw covers all 10×9 metatiles, not just the changed cell.')])

unit=[('u','有効なunit_t。位置はセル単位、moveは歩数、atk_min/atk_maxは射程、hpとactedは行動可否に使います。','Valid unit_t: cell position, move in steps, inclusive atk_min/atk_max range, hp and acted for action eligibility.')]
mask=[('out_mask','幅×高さバイトの書き込み先。セルごとに0または1を書きます。','Writable width*height bytes; receives zero or one for each cell.')]
gb('unit_can_act','map_path','HPが残り、まだ行動していないユニットかを調べます。','Check that a unit has HP and has not acted.','hp≠0かつacted=0なら1、それ以外は0。状態は変更しません。','Returns 1 when hp is nonzero and acted is zero; otherwise 0. Does not modify the unit.',unit)
gb('unit_move_range','map_path','ユニットの位置からmove歩以内に到達できるセルを移動マスクへ変換します。','Build a movement mask of cells reachable within the unit’s move allowance.','マップがあれば1、幅または高さが0なら0。ユニットの原点は必ず範囲内にしてください。','Returns 1 for an available map, 0 for zero dimensions. The unit’s origin must be in bounds.',unit+mask,[cell,pathlimits,note('origin','探索開始セルは壁でも到達済みになります。HP・acted・他のユニットは移動範囲に影響しません。','The origin is seeded as reachable even when blocked. HP, acted and other units do not affect the movement mask.')])
gb('unit_attack_range','map_path','各セルとのマンハッタン距離がatk_min以上atk_max以下になる攻撃範囲を作ります。','Mark cells whose Manhattan distance lies between atk_min and atk_max, inclusive.','マップがあれば1、幅または高さが0なら0。','Returns 1 for an available map, 0 for zero dimensions.',unit+mask,[cell,note('attack','障害物・射線・味方の位置は考慮しません。距離の計算結果が255以下になる範囲で使います。最小射程が最大射程より大きければ全セル0です。','Ignores obstacles, line of sight and friendly units. Keep evaluated distances at most 255. If minimum range exceeds maximum range, every cell is zero.')])
originargs=[('sx','開始セルX。範囲内を指定します。','In-bounds start cell X.'),('sy','開始セルY。','Start cell Y.')]
gb('range_fill_move','map_path','上下左右へ1歩ずつ広げる幅優先探索で、開始セルからの移動コストを作ります。','Flood cardinal neighbors at unit cost with breadth-first search to build movement costs.',args=originargs+[('move','移動上限0～254。0なら開始セルだけです。','Movement limit 0..254; zero reaches only the origin.'),('out_costmap','幅×高さバイトの出力。未到達は255、開始セルは0です。','Writable width*height cost array: 255 unreached, zero at the origin.')],notes=[cell,pathlimits,note('range_invalid','マップ未設定や範囲外の開始セルでは出力を変更しません。開始セル以外の壁には入りません。','Missing maps or invalid origins leave output unchanged. Blocked destination cells are not entered.')])
gb('path_find_bfs','map_path','上下左右の最短経路を求め、開始点からの移動方向列へ変換します。','Find a shortest cardinal route and write its directions in start-to-goal order.','経路長を返します。未到達・不正座標・max_len超過・開始点と目標が同じ場合は0です。','Returns route length; zero means unreachable, invalid coordinates, insufficient max_len, or an already reached goal.',originargs+[('gx','目標セルX。開始セルと異なる壁は目標にできません。','Goal cell X; a blocked goal distinct from the origin is rejected.'),('gy','目標セルY。','Goal cell Y.'),('out_path','max_lenバイト以上の配列。0=上、1=右、2=下、3=左。','Writable array of at least max_len bytes; 0=up, 1=right, 2=down, 3=left.'),('max_len','許容する出力長。短すぎる場合は切り詰めずに失敗します。','Output capacity; an excessive route fails rather than being truncated.')],[cell,pathlimits,note('pathlimit','max_lenは探索距離の上限ではありません。失敗時に出力を新しい経路として使わないでください。','max_len limits output, not the search radius. Do not use output as a new route after failure.')])

savefmt=note('savefmt','既定は4スロット×512バイトです。各スロットは6バイトのヘッダーと最大506バイトのデータを持ちます。MBC5と8KiB SRAMのビルド例を示します。処理後はRAMを無効にし、以前のRAMバンクや有効状態は復元しません。','Defaults to four 512-byte slots, each with a six-byte header and up to 506 payload bytes. The sample uses MBC5 with 8 KiB SRAM. Calls finish with RAM disabled and do not restore its previous bank or enable state.')
slot=[('slot','スロット番号0～3。','Slot number 0..3.')]
for n,ja,en,rj,re,write in [
('save_write','指定スロットへデータと長さ・チェックサムを書き込みます。','Write data, length and checksum into a slot.','引数が有効なら1、不正なスロット・長さなら0。書き戻し検査はしません。','Returns 1 for valid arguments, 0 for invalid slot/length; does not perform readback verification.',True),
('save_read','ヘッダー・長さ・チェックサムを検査し、成功時だけデータをコピーします。','Validate header, exact length and checksum, copying data only after successful validation.','成功で1、検査失敗で0。失敗時は出力配列を変更しません。','Returns 1 on success, 0 on failed validation; failure leaves the destination unchanged.',False),
('save_load','save_readと同じ検査を通して保存データを読み込みます。','Load saved data through the same validation performed by save_read.','読み込み成功で1、失敗で0。要求した長さが保存時と一致する必要があります。','Returns 1 on a successful load, otherwise 0; requested length must match the saved length.',False)]:
    gb(n,'save',ja,en,rj,re,slot+[('data','保存する読み取り元。lenバイトが必要です。' if write else '読み込み先。lenバイトを書き込める必要があります。','Readable source of len bytes.' if write else 'Writable destination of len bytes.'),('len','データ長0～506バイト。読み込み時は保存された長さと完全一致させます。','Payload length 0..506 bytes. Reads require an exact match with the saved length.')],[savefmt,note('save_atomic','8ビット加算チェックサムはすべての破損を検出するものではありません。書き込みは電源断に対して原子的ではなく、成功値は実機への保存保証ではありません。','The additive eight-bit checksum cannot detect every corruption. Writes are not atomic across power loss; a success result alone is not a guarantee of physical persistence.')])
for n,ja,en in [('save_exists','スロットのヘッダー・長さ・チェックサムを調べ、有効な保存があるか確認します。','Validate a slot’s header, length and checksum to check for a usable save.'),('save_check','データを取り出さず、save_existsと同じ完全性検査を行います。','Perform the same integrity check as save_exists without extracting the payload.')]:gb(n,'save',ja,en,'有効なら1、それ以外は0。長さ0の保存も有効です。','Returns 1 if valid, otherwise 0. A zero-length save can be valid.',slot,[savefmt])
gb('save_init','save','RAMバンク0を選んで一度有効化し、無効化して初期化を終えます。','Select RAM bank zero, enable it briefly, then disable it.',notes=[savefmt,note('save_init_preserve','保存データは消去せず、カートリッジの検出やフォーマットも行いません。','Does not erase saved data, detect cartridge hardware or format slots.')])
gb('save_clear','save','指定スロットの512バイトを0で埋め、保存を無効にします。','Zero all 512 bytes of a slot to invalidate its save.',args=slot,notes=[savefmt,note('save_clear_invalid','0～3以外のスロットは無視します。ほかのスロットは変更しません。','Ignores slots outside 0..3 and leaves other slots unchanged.')])
for n,write in [('__sram_read8',False),('__sram_write8',True)]:
    gb(n,'save','CPUアドレスからSRAMの1バイトを読みます。' if not write else 'CPUアドレスへSRAMの1バイトを書きます。','Read one SRAM byte at a CPU address.' if not write else 'Write one SRAM byte at a CPU address.','読み取ったu8。RAMの存在や値の有効性は検査しません。' if not write else '戻り値はありません。','Returns the byte without checking RAM presence or data validity.' if not write else 'No return value.',[('arg0','$A000～$BFFFのCPUアドレス。','CPU address in $A000..$BFFF.')]+([('arg1','書き込む0～255の値。','Byte value 0..255.')] if write else []),[note('sram_raw','アクセス前に$0000へ0x0Aを書いてRAMを有効にし、終了時は0を書いて無効にします。バンク選択・範囲検査は行いません。呼び出し側でRAMバンクを設定してください。チェックサムや保存ヘッダーも扱いません。','Writes 0x0A to $0000 to enable RAM before access, then writes zero to disable it afterward. Does not select the bank or validate the address; the caller configures the RAM bank. No save header or checksum is managed.')])

scriptfmt=note('scriptfmt','命令は00 END、01 TEXT(bank,ptr16)、02 SET_FLAG(id16)、03 CLEAR_FLAG(id16)、04 JUMP(bank,ptr16)、05 IF_FLAG(id16,bank,ptr16)、06 CHOICE(count,table16)、07 WAIT(n)、08 CALL_EVENT(bank,ptr16)です。16ビット値は下位バイトが先です。文字列・ポインタ表と命令列は読み取り中に消さず、バンク境界をまたがせないでください。','Opcodes: 00 END; 01 TEXT(bank,ptr16); 02 SET_FLAG(id16); 03 CLEAR_FLAG(id16); 04 JUMP(bank,ptr16); 05 IF_FLAG(id16,bank,ptr16); 06 CHOICE(count,table16); 07 WAIT(n); 08 CALL_EVENT(bank,ptr16). Words are little-endian. Keep strings, pointer tables and instructions readable and within their mapped banks.')
gb('script_run','script','実行するスクリプトを選び、待ち回数・選択結果・復帰先を初期化します。','Select a script and reset its wait count, choice result and saved return location.',args=[('bank','命令列のROMバンク。','ROM bank of the instruction stream.'),('script','有効な終端付き命令列の先頭。呼び出しだけでは実行しません。','Start of a valid terminated stream; this call arms it without executing commands.')],notes=[scriptfmt])
gb('script_wait_frames','script','次のscript_step呼び出しを指定回数だけ待ち状態にします。','Make the next specified number of script_step calls wait.',args=[('n','待つ呼び出し回数0～255。0なら待ちを解除します。','Number of waiting calls, 0..255; zero clears the wait.')],notes=[note('script_time','1フレームに1回script_stepを呼ぶとフレーム数になります。関数自体はハードウェアのVBlankを待ちません。','This becomes a frame count only when script_step is called once per frame; the function does not itself wait for VBlank.')])
gb('script_step','script','命令を進め、表示・選択・待ち・終端で呼び出し元へ戻ります。','Advance commands until output, choice, waiting or completion yields control.','0=TEXT/CHOICEで中断、1=待ち、2=終了または未実行。未知の命令も2で終了します。','0=TEXT/CHOICE yield; 1=waiting; 2=finished or inactive. Unknown opcodes also terminate with 2.',notes=[scriptfmt,note('script_control','WAIT nは読み取った回で1を返し、その後さらにn回待ちます。CALL_EVENTの復帰先は1段だけです。CHOICEは0でない件数が必要で、選択まで内部で待ち続けます。待ちのない無限ジャンプはゲームループを止めるため、必ず終了かyieldする命令へ到達させます。','WAIT n returns 1 on decoding, then waits for n more calls. CALL_EVENT has only one saved return slot. CHOICE needs a nonzero count and blocks internally until selection. A non-yielding jump loop blocks the game loop, so ensure execution reaches a terminator or yielding command.')])

farargs=[('p','bankとptrを持つfar_ptr_t。ptrはCPUから見えるアドレスです。','far_ptr_t containing bank and ptr, where ptr is a CPU-visible address.')]
for n,ja,en,rj,re in [('far_read8','バンク付きポインタから1バイトを読みます。','Read one byte through a bank-qualified pointer.','u8の値。','The byte as u8.'),('far_read16','バンク付きポインタから下位バイト先行の16ビット値を読みます。','Read a little-endian word through a bank-qualified pointer.','u16の値。','The word as u16.')]:gb(n,'far',ja,en,rj,re,farargs,[note('far_macro','マクロはpのbankとptrを別々に参照します。副作用のある式をpへ渡さないでください。ROM読み取り中のバンク切り替えは組み込み関数が行って復元します。割り込みから同じバンク操作を重ねないでください。','The macro reads p.bank and p.ptr separately; do not pass a side-effecting expression. The intrinsic temporarily selects the ROM bank and restores it. Avoid concurrent bank changes from interrupts.')])
gb('far_read_block','far','バンク付きポインタから連続したバイト列をRAMへコピーします。','Copy consecutive bytes from a bank-qualified pointer into RAM.',args=[('dst','lenバイトを書き込めるRAM先頭。','Start of len writable RAM bytes.')]+farargs+[('len','コピーするバイト数。元のバンク内に収めます。','Byte count; keep the source extent within its bank.')],notes=[note('far_copy','__farmemcpyへのマクロです。ROMバンク境界を自動でまたぐ機能はなく、重なる領域の移動にも使いません。','Macro forwarding to __farmemcpy. It does not cross ROM bank boundaries automatically and is not an overlapping-memory move.')])

gb('danmaku_reset','danmaku','96発の弾プールを空にし、最大同時数・生成総数・満杯による拒否総数を0へ戻します。','Empty the 96-bullet pool and reset peak, lifetime spawn and full-pool rejection counters.',notes=[note('dmreset','プレイヤー座標・無敵フラグ・背景RAMマップは変更しません。ゲーム開始時に呼び、これらは別途設定します。','Leaves player coordinates, invulnerability and the RAM tile map unchanged; set those separately at game start.')])
gb('danmaku_clear','danmaku','有効な弾をすべて消し、現在数・今回のヒット/かすり・次の探索位置を初期化します。','Deactivate all bullets and clear live count, current hit/graze events and the allocation cursor.',notes=[note('dmclear','ピーク・生成総数・拒否総数は保持します。画面から弾を消すにはRAMマップを消去して転送してください。','Preserves peak and lifetime counters. Clear and upload the RAM map to remove bullets from the display.')])
dmxy=[('x','初期Xピクセル0～159。','Initial pixel X, 0..159.'),('y','初期Yピクセル0～127。','Initial pixel Y, 0..127.')]
gb('danmaku_spawn','danmaku','空きスロットを巡回検索し、指定した位置と速度の弾を1発作ります。','Search free slots cyclically and create one bullet with the requested position and velocity.','生成できれば1、範囲外または満杯なら0。範囲外の要求はdm_rejectedへ加算しません。','Returns 1 on allocation, 0 for outside coordinates or a full pool. Outside requests do not increment dm_rejected.',dmxy+[('vx','符号付きQ4.4速度−128～127。16が1更新あたり右へ1ピクセルです。','Signed Q4.4 velocity −128..127; 16 moves one pixel right per update.'),('vy','符号付きQ4.4速度。正は下方向です。','Signed Q4.4 velocity; positive moves down.')],[note('dmcounters','位置は内部で1/16ピクセル単位です。生成/拒否のu16総数は65535の次に0へ周回します。メモリの動的確保は行いません。','Positions are stored in sixteenths of a pixel. The u16 spawn/rejection totals wrap after 65535. No dynamic allocation is used.')])
gb('danmaku_fan','danmaku','32方向のテーブルから速度を作り、角度をずらしながら弾を連続生成します。','Generate a fan using a 32-direction velocity table and a fixed angular step.',args=dmxy+[('direction','開始角。下位5ビットを使い、0=右、8=下、16=左、24=上。','Starting angle, masked to five bits: 0=right, 8=down, 16=left, 24=up.'),('step','弾ごとの角度増分。32方向で周回します。','Angle increment per bullet, wrapping over 32 directions.'),('count','生成試行数。96に制限します。','Attempt count, capped at 96.'),('speed','1/16ピクセル単位の速さ。64（4ピクセル/更新）に制限します。','Speed in sixteenths of a pixel, capped at 64 (four pixels/update).')],notes=[note('dmfan','満杯でも残りの生成を試行します。sin/cos表は整数近似で、斜め方向の距離は丸めの影響を受けます。','Continues attempting remaining spawns when full. Integer sin/cos table values introduce rounding in diagonal motion.')])
gb('danmaku_clear_map','danmaku','32×18タイル分のdm_map 576バイトを0で埋めます。','Clear all 576 bytes of the 32×18 RAM tile map.',notes=[note('dmmap','弾の状態とVRAMは変更しません。毎フレーム clear_map → 装飾の書き込み → step → 転送の順で使います。','Leaves bullet state and VRAM unchanged. Each frame use clear_map, write decorations, step, then upload.')])
gb('danmaku_step','danmaku','全弾を1回移動し、範囲外の弾を削除して、弾のタイル合成とヒット/かすり判定を行います。','Advance every bullet once, remove outside bullets, compose bullet tiles and detect hits/grazes.',notes=[note('dmcollision','描画中心は座標を4ピクセル区画へ丸めた中心です。プレイヤーとの各軸差が8以下で初回かすり、3以下でヒットします。無敵はヒットだけを抑えます。dm_hit/dm_grazeは呼び出しごとに初期化され、かすりは各弾1回です。タイル0～15を4つの区画ビットとして合成し、占有セルの装飾ID16以上は置き換えます。','Rendered centers are snapped to four-pixel cells. Axis differences at most eight produce a first graze; at most three produce a hit. Invulnerability suppresses hits only. dm_hit/dm_graze reset each call; each bullet grazes once. Tile IDs 0..15 encode four quadrant bits; occupied decoration IDs 16 or above are replaced.')])
gb('danmaku_present_now','danmaku','CGBのGDMAでdm_map全576バイトを背景マップ$9800へ同期転送します。','Synchronously upload all 576 dm_map bytes to background map $9800 using CGB GDMA.',notes=[note('dmgdma','CGB専用です。DMGでは呼ばないでください。LCD停止中またはVBlank開始直後に使い、VRAMバンクは0になります。以前のVBKは復元しません。弾用タイル0～15はアプリ側で用意します。','CGB only; do not call on DMG. Use with LCD off or at the start of VBlank. Selects VRAM bank zero without restoring prior VBK. The application supplies bullet graphics in tiles 0..15.')])

# Display and coordinate intrinsics have separate contracts despite sharing lessons.
for n,bit,subject in [('__getbgmapbase',3,'背景'),('__getwinmapbase',6,'ウィンドウ')]:
    gb(n,'display','LCDCのbit'+str(bit)+'から'+subject+'のタイルマップ先頭を求めます。','Read LCDC bit '+str(bit)+' to select the '+('background' if bit==3 else 'window')+' tile-map base.','$9800または$9C00。タイル画像の格納先アドレスではありません。','Returns $9800 or $9C00, the tile-map base rather than the tile graphics address.')
gb('__tile_addr','display','32タイル幅のマップで、1セルのCPUアドレスを計算します。','Compute one cell’s CPU address in a 32-tile-wide map.','base + y*32 + xの下位16ビット。メモリの読み書きはしません。','Returns (base + y*32 + x) modulo 65536 without accessing memory.',[('base','背景/ウィンドウのマップ先頭。通常$9800/$9C00。','Tile-map base, normally $9800/$9C00.'),('x','列0～31を指定します。','Column, normally 0..31.'),('y','行0～31を指定します。','Row, normally 0..31.')])
gb('__scroll_bg_set','display','背景のX/YスクロールをSCX/SCYへ即時設定し、内部の現在値・保留値も同期します。','Write background SCX/SCY immediately and synchronize current/pending software values.',args=[('scx','Xスクロール0～255ピクセル。','Horizontal scroll, 0..255 pixels.'),('scy','Yスクロール0～255ピクセル。','Vertical scroll, 0..255 pixels.')],notes=[note('scrollnow','保留中の背景更新フラグを消します。画面途中の書き込みはその後の走査へ影響するので、通常はVBlankで呼びます。','Clears the pending background-update flag. Mid-frame writes affect subsequent scanning; normally call during VBlank.')])
gb('__wait_vblank','display','LCDが動作していれば、現在のVBlankを抜けて次のLY≧144まで待ちます。','With LCD running, wait out any current VBlank and then wait for the next LY≥144.',notes=[note('waitvb','LCD停止中は即座に戻ります。割り込みの有効化やフレームカウンターの更新は行わず、LYをポーリングします。','Returns immediately with LCD off. Polls LY without enabling interrupts or advancing a library frame counter.')])
gb('__wait_ly','display','LCD動作中にLYが指定値と一致するまで待ちます。','With LCD running, wait until LY equals the target line.',args=[('ly','走査線0～153。LCD動作中に154以上を指定すると戻りません。','Scanline 0..153; values above 153 do not complete while the LCD runs.')],notes=[note('waitly','すでにその走査線なら即座に戻り、過ぎていれば次フレームまで待ちます。LCD停止中も即座に戻ります。','Returns immediately on the target line; if that line has passed, waits until the next frame. Also returns immediately with LCD off.')])
gb('__critical_enter','display','ソフトウェアのネスト深さを1増やしてDIを実行します。','Increment software nesting depth and execute DI.','増加前の深さをu8トークンとして返します。外側は0、次の内側は1です。','Returns the previous depth as a u8 token: zero for the outer scope, one for its first nested scope.',notes=[note('critical','トークンは逆順にleaveへ渡し、256段の周回を起こさないでください。以前のハードウェアIMEは保存しません。もともとDI状態を保つ必要がある場面には使わないでください。','Pass tokens to leave in reverse order and avoid depth wrapping at 256. Previous hardware IME is not saved; do not use this pair where a pre-existing DI state must be preserved.')])
gb('__critical_leave','display','ネスト深さを減らし、外側のトークン0ならEIで割り込みを再開します。','Decrease nesting depth and execute EI for outer token zero.',args=[('token','対応する__critical_enterの返したトークン。','Token returned by the matching __critical_enter.')],notes=[note('leave','非0トークンではEIしません。任意の0を渡すと、ほかの区間が残っていても有効化するため、必ず正しく対応させます。','Nonzero tokens do not execute EI. Passing an arbitrary zero can enable interrupts despite other active scopes; pair calls correctly.')])
for p in ['gb','fc']:
    add(p,'__xy_in_rect','coordinates','点が左上を含み右端・下端を含まない矩形内にあるか調べます。','Test membership in a rectangle including its top/left and excluding its bottom/right.','内部なら1、それ以外は0。幅または高さ0は空です。','Returns 1 inside, otherwise 0. Zero width or height is empty.',[(n,j,e) for n,j,e in [('x','点のX座標0～255。','Point X, 0..255.'),('y','点のY座標0～255。','Point Y, 0..255.'),('rx','矩形左端0～255。','Rectangle left, 0..255.'),('ry','矩形上端0～255。','Rectangle top, 0..255.'),('rw','幅0～255。','Width, 0..255.'),('rh','高さ0～255。','Height, 0..255.')]], [note('rect_wrap','差分で比較するのでrx+rwが255を超えても左端へ周回しません。','Uses coordinate differences: a right bound above 255 does not wrap to the left.')])
    add(p,'__manhattan','coordinates','2点のX差の絶対値とY差の絶対値を足します。','Add the absolute X and Y differences between two points.','|x1−x2|+|y1−y2|の下位8ビット。255を超える距離は周回します。','Returns the low byte of |x1−x2|+|y1−y2|; distances above 255 wrap.',[(n,'点'+('1' if n.endswith('1') else '2')+'の'+n[0].upper()+'座標0～255。','Point '+n[-1]+' '+n[0].upper()+' coordinate, 0..255.') for n in ['x1','y1','x2','y2']])
    add(p,'__map_index','coordinates','行優先配列のセル位置を1次元インデックスへ変換します。','Convert a cell coordinate to a row-major array index.','y*width+xをu16で返します。座標の範囲検査はありません。','Returns y*width+x as u16; does not validate coordinates.',[('x','列0～255。通常はwidth未満です。','Column 0..255, normally less than width.'),('y','行0～255。','Row 0..255.'),('width','1行のセル数0～255。','Cells per row, 0..255.')])

# Arithmetic units follow each backend's actual implementation, including FC's raw-product aliases.
selected=json.loads((HERE/'batch300_selection.json').read_text())
for item in selected:
    p,n=item['key'].split(':')
    if not any(t in n for t in ['mul','mac','dot']):continue
    record=item['record'];argnames=[regex.search(r'(\w+)\s*$',a).group(1) for a in record['args'].split(',') if a.strip()]
    signed=n.startswith('__s');q='q1_7' in n;dot='dot' in n;mac='mac' in n;hi='8x8_hi' in n
    count=3 if 'dot3' in n else 2
    kinds=(['acc','value','coefficient'] if mac else ['value']*count+['coefficient']*count if dot else ['byte','byte'] if hi else ['value','coefficient'])
    args=[]
    for i,(a,kind) in enumerate(zip(argnames,kinds)):
        if kind=='acc':j,e='加算する16ビットの累積値。','16-bit accumulator to add.'
        elif kind=='byte':j,e='符号なし8ビット値0～255。','Unsigned byte, 0..255.'
        elif kind=='value':j,e=('符号付き16ビットのビット列。数値は−32768～32767。','Signed 16-bit bit pattern, representing −32768..32767.') if signed else ('符号なし16ビット値0～65535。','Unsigned word, 0..65535.')
        else:j,e=('符号付き8ビットのビット列。係数は−128～127。','Signed byte bit pattern, coefficient −128..127.') if signed else ('符号なし8ビット係数0～255。','Unsigned coefficient, 0..255.')
        args.append((a,j,e))
    if hi:
        j='8ビット同士を掛け、積の上位8ビットを取り出します。';e='Multiply two unsigned bytes and return the high byte.';rj='floor(a*b/256)、0～254。';retn='floor(a*b/256), in 0..254.';notes=[]
    else:
        operation='2項の内積' if dot and count==2 else '3項の内積' if dot else '積和' if mac else '乗算'
        eng='two-term dot product' if dot and count==2 else 'three-term dot product' if dot else 'multiply-accumulate' if mac else 'multiplication'
        j=('符号付き' if signed else '符号なし')+operation+'を計算します。';e='Compute a '+('signed' if signed else 'unsigned')+' '+eng+'.'
        if p=='gb':
            term='2*trunc(a*b/256)' if q else 'trunc(a*b/256)' if signed else 'floor(a*b/256)'
            rj='各積を'+term+'で求め'+('て合計します。' if dot else '、accへ加えます。' if mac else 'ます。')+'戻り値は下位16ビットです。'
            retn='Each term is '+term+('. Sum the terms' if dot else ', added to acc' if mac else '')+'; returns the low 16 bits.'
            notes=[note('gbmath','GBのこれらの乗算は積を256で割り、符号付きでは0方向に切り捨てます。Q1.7版はその結果を2倍するため、厳密な128除算と最大1だけ異なります。各項を別々に丸め、最後の加算は16ビットで周回します。','GB products are divided by 256; signed results truncate toward zero. Q1.7 variants double that truncated result and can differ by one from exact division by 128. Terms are rounded separately; final addition wraps at 16 bits.')]
        else:
            rj=('a0*b0+a1*b1'+('+a2*b2' if count==3 else '') if dot else 'acc+a*b' if mac else 'a*b')+'の下位16ビットです。';retn='Returns the low 16 bits of '+('a0*b0+a1*b1'+('+a2*b2' if count==3 else '') if dot else 'acc+a*b' if mac else 'a*b')+'.'
            notes=[note('fcmath','FCでは名前にq8_8/q1_7があっても生の整数積を使い、固定小数点の縮小シフトは行いません。Q1.7の3関数は対応する符号付き関数への別名です。単位変換は呼び出し側で行います。符号付き結果もu16のビット列として返します。','On FC, q8_8/q1_7 names still use raw integer products without a fixed-point downshift. The Q1.7 functions alias their corresponding signed operations. The caller handles units; signed results are returned as u16 bit patterns.')]
    add(p,n,'math',j,e,rj,retn,args,notes)

# FC rendering helpers.
nt=[('nt_base','論理ネームテーブル先頭$2000/$2400/$2800/$2C00。物理的な独立性はミラーリング設定によります。','Logical nametable base $2000/$2400/$2800/$2C00; mirroring determines physical independence.')]
direct=note('pputime','直接転送はPPUCTRLのアドレス増分を1にし、描画停止中か転送量が収まるVBlankで行います。これらのヘルパーは描画停止も待機もしません。','For direct transfers, set PPUCTRL increment to one and use rendering-off setup or a VBlank long enough for the upload. These helpers neither disable rendering nor wait.')
shadow=note('shadow','共有属性シャドー64バイトはCPU RAM $03E0～$041Fです。ほかのデータと重ねないでください。属性1バイトは4×4タイル、各2ビットは2×2タイルのパレットを表します。','The shared 64-byte attribute shadow occupies CPU RAM $03E0..$041F. Reserve that range. One attribute byte covers 4×4 tiles; each two-bit field selects a palette for a 2×2-tile quadrant.')
queue=note('queue','runtime.cをリンクします。キューはデータをコピーし、後のNMIまたは安全な描画停止中のflushで反映します。キューへの登録と消費を競合させないでください。複数行の途中で容量不足になった場合、それまでの行は残ります。','Link runtime.c. The queue copies payloads for a later NMI or safe rendering-off flush. Serialize production against consumption. If a multirow operation runs out of capacity, earlier admitted rows remain queued.')
rect=[('tile_x','左端のタイル列。可視範囲は0～31。','Left tile column, visible range 0..31.'),('tile_y','上端のタイル行。可視範囲は0～29。','Top tile row, visible range 0..29.'),('width','幅（タイル数）。','Width in tiles.'),('height','高さ（タイル数）。','Height in tiles.')]
for n,ja,en in [('nes_attr_shadow_build_from_palette_map','完成済みの属性64バイトを共有シャドーへコピーします。','Copy 64 already-packed attribute bytes into the shared shadow.'),('nes_attr_shadow_copy','属性テーブル全体をRAMへコピーし、編集の初期値にします。','Copy a complete attribute table into RAM as the starting point for edits.')]:fc(n,'attributes' if 'build' in n else 'nametable',ja,en,args=[('src64','読み取り可能な64バイトのpacked属性表。1タイルごとのパレット番号配列ではありません。','Readable 64-byte packed attribute table, not an array of per-tile palette IDs.')],notes=[shadow])
fc('nes_attr_shadow_fill_rect','attributes','矩形が触れる2×2タイル区画すべてのパレット番号を変更します。','Replace the palette fields of every 2×2-tile quadrant touched by a rectangle.',args=rect+[('pal_index','パレット番号。下位2ビットを使います。','Palette index; only the low two bits are used.')],notes=[shadow,note('attrrect','矩形全体を32×30タイル内に収めます。空または範囲外の矩形では何も変更しません。奇数の境界は区画へ広がるので、矩形の外側の隣接タイルも同じパレットになります。','Keep the entire rectangle within 32×30 tiles. Empty or invalid rectangles change nothing. Odd boundaries expand to quadrant boundaries, so neighboring tiles outside the rectangle can share the new palette.')])
fc('nes_attr_queue_rect','attributes','タイル矩形が触れる属性バイトを行単位でキューへコピーします。','Copy rows of attribute bytes covering a tile rectangle into the queue.','全行登録または空矩形なら1、範囲外または容量不足なら0。範囲外では登録を始めません。','Returns 1 for complete admission or an empty rectangle, 0 for invalid bounds or insufficient capacity. Invalid bounds enqueue nothing.',nt+rect,[shadow,queue,note('attrbyte','1属性バイトは4×4タイルです。関数は矩形に触れるバイト全体を転送するため、隣接区画の値もシャドーへ正しく保持しておきます。','An attribute byte covers 4×4 tiles. Whole intersecting bytes are transferred, so preserve correct neighboring quadrant values in the shadow.')])
fc('nes_nt_base_from_index','nametable','番号の下位2ビットから論理ネームテーブルの先頭を求めます。','Compute a logical nametable base from the low two index bits.','$2000 + (index & 3)*$400。','Returns $2000 + (index & 3)*$400.',[('index','番号。0～3を使い、4以上は下位2ビットへ周回します。','Index; 0..3 select tables, larger values wrap to the low two bits.')])
fc('nes_attr_base_from_nt','nametable','ネームテーブル先頭に$3C0を足し、属性表の先頭を求めます。','Add $3C0 to a nametable base to locate its attribute table.','nt_base+$3C0。入力の妥当性は検査しません。','Returns nt_base+$3C0 without validating the input.',nt)
fc('nes_attr_shadow_clear','nametable','属性シャドー64バイトを同じpacked値で埋めます。','Fill all 64 shadow bytes with the same packed value.',args=[('value','packed属性値。例0x55は全区画パレット1、0xAAは2です。','Packed attribute byte; e.g. 0x55 selects palette 1 in all quadrants, 0xAA selects 2.')],notes=[shadow])
fc('nes_attr_shadow_set_quad','nametable','1つの2×2タイル区画だけのパレットを変更し、同じバイト内の他の区画を保ちます。','Replace one 2×2-tile quadrant’s palette while preserving the other fields in its byte.',args=rect[:2]+[('pal_index','パレット番号の下位2ビット。','Low two bits of the palette index.')],notes=[shadow,note('quadbounds','座標を32未満に保ちます。奇数座標もそのセルを含む2×2区画を選びます。可視行は0～29です。','Keep coordinates below 32. Odd coordinates select their containing 2×2 quadrant. Visible rows are 0..29.')])
fc('nes_attr_apply_now','nametable','共有シャドー64バイトを指定ネームテーブルの属性表へ即座に転送します。','Immediately upload all 64 shadow bytes to a nametable’s attribute table.',args=nt,notes=[shadow,direct])
fc('nes_attr_queue_all','nametable','属性シャドー全体をキューにコピーします。','Copy the entire attribute shadow into the queue.','登録成功で1、容量不足で0。1件67バイトを使います。','Returns 1 on admission, 0 if full; one record uses 67 queue bytes.',nt,[shadow,queue])
for n,queued in [('nes_nt_stream_row',False),('nes_nt_queue_row',True)]:
    fc(n,'nametable','1行32タイルを'+('キューへコピーします。' if queued else 'PPUへ直接書き込みます。'),'Copy one complete 32-tile row '+('into the queue.' if queued else 'directly to the PPU.'),'成功1、容量不足0。キューを35バイト使います。' if queued else '戻り値はありません。','Returns 1 on admission, 0 if full; uses 35 queue bytes.' if queued else 'No return value.',nt+[('row','行番号0～29。範囲検査はありません。','Row 0..29; not bounds-checked.'),('src32','読み取り可能な32バイトのタイル番号。','Thirty-two readable tile IDs.')],[queue if queued else direct])
for n,queued,fill in [('nes_nt_stream_rect',False,False),('nes_nt_queue_rect',True,False),('nes_nt_queue_fill_rect',True,True)]:
    fc(n,'nametable','矩形の各行を'+('同じタイルで埋めるキューへ登録します。' if fill else 'キューへコピーします。' if queued else '元配列のpitch間隔で読み、PPUへ直接転送します。'),'For each rectangle row, '+('queue a fill with one tile ID.' if fill else 'copy the source into the queue.' if queued else 'read at the source pitch and upload directly to the PPU.'),'全行成功または高さ0で1、途中の容量不足で0。' if queued else '戻り値はありません。','Returns 1 after all rows or for zero height, 0 on admission failure.' if queued else 'No return value.',nt+rect+([('value','塗りつぶすタイル番号0～255。','Fill tile ID, 0..255.')] if fill else [('pitch','元配列で次の行まで進むバイト数。行の末尾の余白を飛ばせます。','Source byte stride between row starts; can skip trailing padding.'),('src','(height−1)*pitch+widthバイト以上の読み取り元。','Readable source spanning at least (height−1)*pitch+width bytes.')]),[queue if queued else direct,note('ntrectbounds','座標と幅・高さは可視ネームテーブル内に収め、pitchは通常width以上にします。クリッピングはありません。キュー版の1行幅は127以下、矩形の通常の最大幅は32です。','Keep coordinates and extents within the visible nametable; normally pitch≥width. No clipping is performed. Queued row lengths must be at most 127; a normal nametable rectangle is at most 32 tiles wide.')])
fc('nes_nametable_apply_now','nametable','960バイトのタイル番号に続けて64バイトの属性表を一括転送します。','Upload 960 tile IDs followed by a 64-byte attribute table.',args=nt+[('nam960','32×30タイルの行優先配列。','Row-major 32×30 tile array.'),('attr64','64バイトのpacked属性表。シャドーとは別の入力でも構いません。','Sixty-four packed attribute bytes; need not be the shared shadow.')],notes=[direct,note('ntbulk','1024バイトを同期転送するため、通常は起動時など描画を止めた場面で使います。フレームを分けた転送は行いません。','A synchronous 1024-byte upload normally belongs in rendering-off setup. The helper does not spread it across frames.')])
actor=[('actor','書き込み可能なNesActorへのポインタ。','Pointer to a writable NesActor.')]
fc('nes_actor_set_world','actor','アクターのワールドX/Yを更新します。','Set an actor’s world X/Y.',args=actor+[('x','ワールドX、0～65535ピクセル。','World X, 0..65535 pixels.'),('y','ワールドY、0～65535ピクセル。','World Y, 0..65535 pixels.')],notes=[note('actorcache','screen_x/screen_yは更新しません。カメラを反映するにはupdate_screenを呼びます。','Does not update screen_x/screen_y. Call update_screen to project through the camera.')])
fc('nes_actor_update_screen','actor','ワールド座標からカメラ座標を引き、下位8ビットを画面座標へ保存します。','Subtract camera coordinates from world coordinates and cache the low bytes as screen coordinates.',args=actor+[('camera_x','カメラのワールドX。','Camera world X.'),('camera_y','カメラのワールドY。','Camera world Y.')],notes=[note('actorclip','負や256以上の結果は周回します。画面外のアクターを自動で隠さないので、描画前にゲーム側で判定します。','Negative or ≥256 results wrap. It does not hide offscreen actors; the game must cull before drawing.')])
fc('nes_actor_draw_metasprite','actor','保存済み画面座標を基点に、メタスプライトをシャドーOAMへ書きます。','Write a metasprite into shadow OAM using the actor’s cached screen coordinates.','次のOAMスロット番号。64スロット末尾を越えると周回します。','Returns the next OAM slot index, wrapping at the end of 64 slots.',actor+[('oam_index','開始スロット0～63。全パーツ分の空きを確保します。','First slot, 0..63; reserve room for every part.'),('metasprite','dx,dy,tile,attrの4バイト列。dx=255が終端です。','Four-byte records dx,dy,tile,attr; dx=255 terminates.')],[queue,note('actordraw','attr/flagsフィールドは適用しません。Yは生のOAM値なので表示上端は1ピクセル下です。実際の表示にはOAM DMAが別途必要です。','Does not apply the actor’s attr/flags fields. Y is a raw OAM byte, so the visible top is one pixel lower. An OAM DMA is required to display the shadow.')])
fc('nes_actor_collide','actor','ワールド座標の軸に平行な矩形同士が重なるか調べます。','Test overlap of axis-aligned actor rectangles in world coordinates.','重なれば1、離れているか辺が接するだけなら0。','Returns 1 for overlap; 0 for separation or edges that merely touch.',[('a','1つ目のアクター。','First actor.'),('b','2つ目のアクター。','Second actor.')],[note('actorbounds','幅と高さは1以上、座標＋サイズは65535以下にします。画面座標・attr・flagsは判定に使いません。','Use positive widths/heights and keep position+size≤65535. Screen coordinates, attr and flags are ignored.')])

assert len(auth)==100,len(auth)
modules['gb:rpg']=[note('module_rpg_maps','RPGのマップ表示・メタタイル・スクリプト・SRAM保存・経路探索を提供します。通常マップは8×8、メタタイルは16×16ピクセルのセルです。マップ読み込みと描画、移動マスク、攻撃マスクは別の処理で、画像の読み込みやイベント実行はゲーム側が組み合わせます。','Provides map/metatile drawing, scripts, SRAM saves and pathfinding. Ordinary cells are 8×8 pixels; metatiles are 16×16. Loading/drawing, movement masks and attack masks are separate operations; the game coordinates graphics loading and event execution.'),pathlimits,savefmt]
modules['gb:danmaku']=[note('module_danmaku','160×128ピクセル内の最大96発を固定配列で処理する弾幕ライブラリです。1/16ピクセルの位置更新、32方向の扇形生成、ヒット・かすり、4区画のタイル合成を行います。シミュレーションはGBでも動きますが、present_nowはCGB専用の転送です。','An allocation-free bullet field for up to 96 shots in 160×128 pixels. Provides sixteenth-pixel motion, 32-direction fans, hit/graze events and four-quadrant tile composition. Simulation runs on GB; present_now is a CGB-only upload.')]
modules['fc:attribute']=[shadow,note('module_attr','パレット区画の矩形編集と、必要な属性バイトだけのキュー転送を扱います。32×30タイルの範囲検査を行います。palette_map入力は完成済みの属性64バイトで、1タイル1色の配列ではありません。','Edits palette quadrants by rectangle and queues only the intersecting attribute bytes, checking 32×30 tile bounds. The palette_map input is a completed 64-byte attribute table rather than one color per tile.')]
modules['fc:nametable_asset']=[note('module_nt','32タイルの行、pitch付き矩形、塗りつぶし、960+64バイトの画面全体を転送します。属性シャドーの編集と転送もここにあります。即時転送と後で消費するキューを用途に応じて選びます。','Uploads 32-tile rows, pitched rectangles, fills and complete 960+64-byte screens; also edits and uploads attribute shadow data. Choose immediate transfers or deferred queue consumption for the situation.'),direct,queue]
modules['fc:actor']=[note('module_actor','ワールド座標・画面座標・矩形サイズをNesActorにまとめます。カメラからの相対座標、メタスプライトOAM生成、ワールド矩形の衝突を扱い、移動速度・画面外の非表示・OAM DMAはゲーム側で管理します。','NesActor groups world position, screen position and rectangle size. Helpers project through a camera, write metasprite OAM and test world-space overlap. The game owns velocity, offscreen culling and OAM DMA.')]
def block(source,start):
    masked=catalog.clean(source);i=masked.index('{',start)+1;depth=1
    while depth:depth+=(masked[i]=='{')-(masked[i]=='}');i+=1
    return source[start:i].strip(),source.count('\n',0,start)+1
specs=json.loads((HERE/'batch300_examples.json').read_text())
expect={
'math':('固定値とRAM変数で同じ計算を行う例です。画面には代表値を符号なし16ビットで表示し、負数は2の補数の値になります。GBは固定小数点の縮小を行い、FCは整数積を返すため、同じ入力でも両機種の結果は異なります。','Compare literal inputs with values stored in RAM. Representative results appear as unsigned 16-bit values; negatives use two’s-complement bit patterns. GB rescales fixed-point products, while FC returns integer products, so identical inputs need not give identical results.'),
'coordinates':('矩形の内部・端・外側・幅0を試します。INSIDE=1、RIGHT EDGE=0、LEFT EDGE=0、HIGH X=1です。距離15、距離の周回254、配列位置64と65280を確認します。','Exercise the interior, boundaries, outside point and zero width: INSIDE=1, RIGHT EDGE=0, LEFT EDGE=0, HIGH X=1. Verify distance 15, wrapped distance 254 and array indices 64/65280.'),
'display':('背景とウィンドウのマップ切り替え、スクロール、ネスト、走査線待ちを学びます。先頭アドレスは38912/39936、トークンは0/1、待ったLYは80/144です。LCD停止中の待ちが戻ることも確認します。','Learn map selection, scrolling, nesting and scanline waits. Bases are 38912/39936; nested tokens are 0/1; observed target LY values are 80/144. Also verify waits return with the LCD off.'),
'save':('7・42・255の3バイトを保存し、長さ不一致・無効スロット・破損チェックサムを試します。読み込み成功時の中央値は42、破損時には出力先77を保持し、消去後の検査は0です。','Save three bytes, 7/42/255, then test length mismatch, an invalid slot and a damaged checksum. A successful load yields middle byte 42; a failed read preserves destination 77; validation after clearing returns 0.'),
'far':('別ROMバンクの34 12 AB（16進）を読みます。1バイトは52、下位バイト先行のワードは4660、コピーした末尾は171と表示します。','Read hexadecimal 34 12 AB from another ROM bank: first byte 52, little-endian word 4660 and copied final byte 171.'),
'script':('バンク1からバンク2へジャンプし、フラグ19を立てて待つ例です。最初の待ち2回は1、ジャンプ先のフラグは1、WAIT後に終了2となります。別バンクへ制御が届いたことをフラグで確認します。','Jump from bank 1 to bank 2, set flag 19 and wait. Initial two waiting calls return 1; destination flag becomes 1; completion after WAIT returns 2. The flag proves control reached the other bank.'),
'map_path':('左に移動3歩以内のコスト、右にSからGまでの最短経路を表示します。赤い3セルの壁を避け、緑の*が9歩の経路を示します。青い数字は到達コストです。DMGは同じ配置を黒で表示します。射程マスクは壁を無視する点もRAMで検査します。','The left grid shows movement costs within three steps; the right shows a shortest route from S to G. Green asterisks trace nine steps around a red three-cell wall; blue digits show costs. DMG uses the same layout in black. RAM checks also demonstrate that the attack mask ignores walls.'),
'metatile':('メタタイルIDをRAMで変え、dirtyを付けてflushする例です。カメラ(1,0)で左上に16×16の緑の正方形が現れます。パレットのメタデータはサンプル側がCGB属性へ反映しています。DMGでは黒い正方形です。','Edit a metatile ID in RAM, mark it dirty and flush. Camera (1,0) shows a green 16×16 square at the upper-left. The sample explicitly applies palette metadata to CGB attributes. DMG shows a black square.'),
'danmaku':('CGB専用の描画例です。中央(80,64)から8方向へ弾を放ち、8回更新して赤い3×3の点8個を放射状に表示します。縦横は32ピクセル進み、斜め方向は整数近似で進みます。プールの消去と生涯生成数の保持も検査します。','CGB-only drawing lesson. Spawn eight directions at (80,64), update eight times and show eight red 3×3 dots in a radial arrangement. Cardinal bullets travel 32 pixels; diagonals use integer approximation. Also check pool clearing and retained lifetime spawn counts.'),
'attributes':('属性の矩形転送を学びます。(16,32)に赤の32×32、(80,32)に青の32×32、画面右下(240,224)に緑の16×16を表示します。隣の区画を壊さず、右下の属性バイトまで正しく転送する例です。','Learn rectangular attribute uploads: red 32×32 at (16,32), blue 32×32 at (80,32), green 16×16 at bottom-right (240,224). The example preserves adjacent quadrants and reaches the final attribute byte correctly.'),
'nametable':('行・pitch付き矩形・塗りつぶし・一括転送を組み合わせます。上に赤い32×8の横棒2本、下に青い16×16、赤い16×24と32×24の矩形が並びます。直接転送とキュー転送で異なる位置へ描きます。','Combine row, pitched rectangle, fill and full-table uploads. Two red 32×8 bars appear above a blue 16×16 square and red 16×24/32×24 rectangles. Direct and queued transfers draw at distinct positions.'),
'actor':('ワールド(300,95)のアクターへカメラ(268,32)を適用し、画面(32,64)と(40,64)へ赤と青の8×8パーツを並べます。生のOAM Y=63が表示では64になること、辺が接するだけでは衝突せず1ピクセル重なると衝突することを確認します。','Project world (300,95) through camera (268,32): red and blue 8×8 parts appear at (32,64) and (40,64). This demonstrates raw OAM Y=63 appearing at 64, and collision changing from zero for touching edges to one for a one-pixel overlap.')}
datasets={p:json.loads((SITE/'reference'/f'{p}-api.json').read_text(encoding='utf-8')) for p in ['gb','fc']}
for key,c in auth.items():
    p,n=key.split(':');record=next(r for r in datasets[p]['records'] if r['name']==n);g=c.pop('group')
    spec=next(s for s in specs if s['platform']==p and s['group']==g);path=REPOS/record['path'];sources[record['path']]=sha(path)
    if path.suffix=='.h' and record.get('kind')!='macro':
        d=next(d for d in catalog.definitions(path) if d['name']==n)
        for field in ['ret','args','signature','path','line','comment','body']:record[field]=d[field]
    if record.get('definition'):
        lib=REPOS/record['definition']['path'];record['definition']=next(d for d in catalog.definitions(lib) if d['name']==n);sources[lib.relative_to(REPOS).as_posix()]=sha(lib)
    elif n.startswith('__'):
        compiler=REPOS/f'kitaq{p}/kitaq{p}/CodeGenerator.cs';src=compiler.read_text(encoding='utf-8');sources[compiler.relative_to(REPOS).as_posix()]=sha(compiler)
        if p=='gb':excerpt,line=block(src,src.index('if (funcName == "'+n+'")'))
        else:
            start=src.index('case "'+n+'":');end=src.find('case "',start+8);excerpt=src[start:end].strip();line=src.count('\n',0,start)+1
            method='void EmitHelperGeometryAndRng(' if n in ['__xy_in_rect','__manhattan','__map_index'] else 'void EmitHelperMath('
            excerpt+='\n\n'+block(src,src.index(method))[0]
        record.update(implementation_excerpt=excerpt,implementation_source={'path':compiler.relative_to(REPOS).as_posix(),'line':line})
    if p=='gb' and next(item['record'] for item in selected if item['key']==key).get('arity_only'):
        if n=='__getwinmapbase':params=[];ret='u16'
        elif n in ['__sram_read8','__sram_write8']:
            params=[('u16','address')]+([('u8','value')] if n.endswith('write8') else []);ret='void' if n.endswith('write8') else 'u8'
        elif '8x8_hi' in n:params=[('u8','a'),('u8','b')];ret='u8'
        elif 'dot' in n:
            count=3 if 'dot3' in n else 2;params=[('u16','a'+str(i)) for i in range(count)]+[('u8','b'+str(i)) for i in range(count)];ret='u16'
        else:params=([('u16','acc')] if 'mac' in n else [])+[('u16','a'),('u8','b')];ret='u16'
        assert len(params)==len(c['args']),key
        for item,(_,name) in zip(c['args'],params):item[0]=name
        record.update(args=', '.join(t+' '+name for t,name in params),ret=ret,signature=ret+' '+n+'('+', '.join(t+' '+name for t,name in params)+');',arity_only=False)
    names=[regex.search(r'(\w+)\s*$',a).group(1) for a in record['args'].split(',') if a.strip() not in ['', 'void']]
    assert names==[a for a,_ in c['args']],(key,names,c['args'])
    fingerprint=hashlib.sha256(json.dumps({k:record.get(k) for k in ['name','signature','comment','definition','implementation_excerpt']},sort_keys=True).encode()).hexdigest()
    program=spec['source'];sample=(SITE/program).read_text(encoding='utf-8');m=regex.search(r'// example:'+regex.escape(n)+r':start\s*\n(.*?)\s*// example:'+regex.escape(n)+r':end',sample,regex.S);assert m,key
    command='.\\kitaq'+p+'\\kitaq'+p+'.exe '+('.\\kitaqfc\\lib\\runtime.c ' if spec.get('runtime') else '')+'.\\kitaq-docs\\'+program.replace('/','\\')+' -I .\\kitaq'+p+'\\lib -I .\\kitaq-docs\\samples -o .\\out\\batch3_'+g+('.gb' if p=='gb' else '.nes')+' --no-cache --no-disasm'
    command+=(' --profile=dev --rst-disable --stack-bank=fixed --cgb=cgb --cart=mbc5 --romsize=64k --ramsize='+spec.get('ramsize','none') if p=='gb' else ' --mapper=nrom --nes-chr=.\\kitaq-docs\\'+spec.get('chr','samples/font.chr').replace('/','\\'))
    c.update(review='batch300-source-20260916',record_sha256=fingerprint,example={'program':program,'code':m[1],'build':'New-Item -ItemType Directory -Force .\\out | Out-Null\n'+command,'expected':pair('expected_'+g,*expect[g])})
    if g=='math':
        indices=[int(i) for i in regex.findall(r'result\[(\d+)\]\s*=',m[1])]
        values=', '.join('result['+str(i)+']='+str(spec['expected'][i]) for i in indices)
        c['example']['expected']+=pair('values_'+p+'_'+n,
            'この抜粋で保存する16ビット値は '+values+' です。固定値とRAM変数を使った計算は、それぞれ同じ値になります。画面は代表値を表示し、全結果はresult配列に保存します。',
            'The excerpt stores these 16-bit values: '+values+'. Each literal-input calculation matches its RAM-input counterpart. The screen shows representative values; the result array holds every result.')
    contracts[key]=c;reviews[key]={'record_sha256':fingerprint,'header_line':record['line']}
for p,data in datasets.items():(SITE/'reference'/f'{p}-api.json').write_text(json.dumps(data,ensure_ascii=False,indent=2),encoding='utf-8')
for n,data in [('batch300_contracts.json',contracts),('batch300_texts.json',texts),('batch300_modules.json',modules),('batch300_review_sources.json',{'source_sha256':sources,'records':reviews})]:(HERE/n).write_text(json.dumps(data,ensure_ascii=False,indent=2),encoding='utf-8')
print('100 individually authored bilingual contracts bound to source and samples.')
