"""Author the FC bullet-pool API from source and its visible/state examples."""
from pathlib import Path
import hashlib,json,sys
HERE=Path(__file__).resolve().parent;SITE=HERE.parents[1];REPOS=SITE.parents[1]/'publish/github_20260912'
sys.path.insert(0,str(SITE/'tools'))
import catalog
catalog.ROOT=REPOS
texts={};contracts={}
def msg(key,ja,en):
    key='fc_danmaku_'+key;texts[key]={'ja':ja,'en':en};return key
none=msg('none','戻り値はありません。','No return value.')
memory=msg('memory','64発の弾のため、書き込み可能なカートリッジPRG RAM $6000～$627F（640バイト）を予約します。使用するマッパーでRAMを有効にしてください。共有状態を使うため再入できません。','Reserve writable cartridge PRG RAM at $6000–$627F (640 bytes) for 64 bullets. Enable that RAM in the cartridge mapper. Shared state makes this library non-reentrant.')
state=msg('state','dm_countは生存弾数、dm_peakは最大生存弾数です。dm_spawnedとdm_rejectedは成功・失敗した発生数を16ビットで数え、65535の次は0へ戻ります。dm_x・dm_yは弾の中心座標で、dm_activeが0のスロットの値は使わないでください。','dm_count is the live bullet count and dm_peak its high-water mark. The 16-bit dm_spawned and dm_rejected counters track successful and failed spawns and wrap after 65535. dm_x and dm_y are center coordinates; ignore their values when dm_active is zero.')
expected=msg('expected','左側の黄色い4発は中心(48,64)から上下左右へ16ピクセル移動した単発弾です。右側の黄色い16発は中心(160,104)から約32ピクセル広がった円形弾です。水色の自機は(112,192)で、OAMスロット0を予約しています。画像は16回の更新後に止めてあります。','The four yellow bullets on the left have moved 16 pixels in the cardinal directions from (48,64). The sixteen yellow bullets on the right form a ring roughly 32 pixels from (160,104). The cyan player at (112,192) owns reserved OAM slot zero. This example holds the image after sixteen logic updates.')
verified=msg('verified','KUROSAKIで4種類のコンパイル設定を実行し、全画素、弾の数と位置、予約したOAM、表示順の回転を照合しています。命中・かすり・画面外除去・満杯の処理は別の数値検証でも確認しています。実機での検証ではありません。','KUROSAKI checks four compiler configurations against all pixels, bullet counts and positions, reserved OAM and rotating draw order. Separate numeric checks cover hits, grazing, offscreen removal and a full pool. Hardware has not been tested.')
build='New-Item -ItemType Directory -Force .\\out | Out-Null\n.\\kitaqfc\\kitaqfc.exe .\\kitaq-docs\\samples\\api-examples\\fc\\danmaku_patterns.c -I .\\kitaqfc\\lib --mapper=nrom --nes-chr-ram -o .\\out\\danmaku_patterns.nes --no-cache --no-disasm\n.\\kurosaki\\kurosaki.exe run .\\out\\danmaku_patterns.nes --headless --frames 180 --png .\\out\\danmaku_patterns.png'
path=SITE/'reference/fc-api.json';data=json.loads(path.read_text(encoding='utf-8'))
declarations={r['name']:r for r in catalog.definitions(REPOS/'kitaqfc/lib/danmaku.h')}
definitions={r['name']:r for r in catalog.definitions(REPOS/'kitaqfc/lib/danmaku.c')}
program='samples/api-examples/fc/danmaku_patterns.c';source=(SITE/program).read_text(encoding='utf-8')
def arg(name,ja,en):return [name,[msg('arg_'+name+'_'+str(len(texts)),ja,en)]]
def add(short,ja,en,args,snippet,notes=(),returns=None):
    name='danmaku_'+short;r=dict(declarations[name]);r.update(module='danmaku',availability='implementation',definition=definitions[name],example={'source':program,'calls':[name]})
    data['records']=[old for old in data['records'] if old['name']!=name]+[r]
    assert snippet in source,name
    fingerprint=hashlib.sha256(json.dumps({k:r.get(k) for k in ['name','signature','comment','definition','implementation_excerpt']},sort_keys=True).encode()).hexdigest()
    contracts['fc:'+name]=dict(review='fc-danmaku-source-20260922',record_sha256=fingerprint,purpose=[msg(short+'_purpose',ja,en)],args=args,returns=[returns or none],notes=list(notes)+[memory,state,verified],example=dict(program=program,code=snippet,build=build,expected=[expected]))

add('reset','全弾を無効にし、命中・かすり・最大弾数・発生数の統計と、割り当て・表示順の巡回位置を0へ戻します。','Deactivate every bullet and reset hit/graze events, peak and lifetime counts, and allocation/draw-order cursors.',[],'danmaku_reset();',notes=[msg('reset_preserves','dm_player_x、dm_player_y、dm_invulnerableは保持します。OAMや画面は消さないため、画面上の弾を取り除くには空になったプールをdrawしてDMAするか、別途OAMを隠します。','Player position and dm_invulnerable are preserved. OAM and the display are not cleared; draw the empty pool and perform DMA, or hide OAM separately, to remove visible bullets.')])
add('clear','全弾を無効にし、dm_count・dm_hit・dm_grazeを0にします。プレイ中に弾だけを消す用途です。','Deactivate every bullet and zero dm_count, dm_hit and dm_graze. Use this to remove bullets during play.',[],'danmaku_clear();',notes=[msg('clear_preserves','dm_peak、dm_spawned、dm_rejected、割り当て位置と表示順の巡回位置、自機設定を保持します。サンプルでは1発発生させてclearした後、生存数は0、累計発生数は1になります。OAMの更新は別途必要です。','Preserve dm_peak, dm_spawned, dm_rejected, allocation and draw-order cursors, and player settings. The sample spawns one bullet and clears it: the live count becomes zero while the lifetime spawn count remains one. Update OAM separately.')])
positions=[arg('x','発生位置の横中心座標です。8以上248未満のピクセル値を指定します。','Horizontal center in pixels; accepted values are 8 through 247.'),arg('y','発生位置の縦中心座標です。24以上232未満のピクセル値を指定します。','Vertical center in pixels; accepted values are 24 through 231.')]
velocities=[arg(n,('横' if n=='vx' else '縦')+'方向の速度です。符号付きQ4.4で、16は1更新あたり1ピクセル、−16は逆向き1ピクセルです。値域−128～127は−8～+7.9375ピクセルに相当します。',('Horizontal' if n=='vx' else 'Vertical')+' velocity in signed Q4.4. A value of 16 moves one pixel per update; −16 moves one pixel in the opposite direction. Values −128..127 represent −8..+7.9375 pixels.') for n in ['vx','vy']]
add('spawn','空きスロットを巡回して1発を割り当て、位置・速度と未かすり状態を設定します。発生した時点では移動や命中判定をしません。','Search the pool cyclically for one free slot and initialize its position, velocity and ungrazed state. Spawning alone does not move it or test collisions.',positions+velocities,'danmaku_spawn(48,64,16,0);',returns=msg('spawn_return','成功時は1、位置が範囲外または64スロットすべて使用中なら0です。成功時はdm_count・dm_spawnedを増やし、必要ならdm_peakを更新します。失敗時はdm_rejectedを増やします。','Return 1 on success, or 0 for an invalid position or a full 64-slot pool. Success increments dm_count and dm_spawned and updates dm_peak as needed; failure increments dm_rejected.'))
add('fan','方向を一定量ずつ進めながら複数の弾を発生させます。刻みと個数で扇形や全周の弾を作れます。','Spawn bullets while advancing direction by a fixed step. The step and count can produce a fan or a full ring.',positions+[arg('direction','最初の方向です。32段階で1周し、0=右、8=下、16=左、24=上です。下位5ビットを使います。','Initial direction in 32 steps per turn: 0 right, 8 down, 16 left, 24 up. Only the low five bits are used.'),arg('step','1発ごとに加える方向の刻みです。加算後は32で折り返します。0ならすべて同方向です。','Direction increment after each bullet, wrapping modulo 32. Zero sends every bullet in the same direction.'),arg('count','発生を試みる弾数です。64を超える値は64になり、0では何もしません。','Number of spawn attempts. Values above 64 are clamped to 64; zero does nothing.'),arg('speed','速度の大きさを1/16ピクセル単位で指定します。16は1、32は2ピクセル/更新です。64を超える値は64になります。','Speed magnitude in sixteenths of a pixel per update: 16 is one pixel and 32 is two. Values above 64 are clamped to 64.')],'danmaku_fan(160,104,0,2,16,32);',notes=[msg('fan_limits','整数の正弦表から速度を求め、0方向へ丸めます。斜め方向の速度や半径には量子化誤差があります。満杯でも残りの発生試行を続け、失敗分をdm_rejectedに加えます。','Velocities come from an integer sine table and truncate toward zero, so diagonal speeds and radii are quantized. A full pool does not cancel remaining attempts; each failure increments dm_rejected.')])
add('step','有効な弾を1回移動し、画面外の弾を除去して、自機との命中・かすりを判定します。呼び出し回数が弾の時間を進めます。','Advance each live bullet once, remove offscreen bullets and evaluate player hits and grazing. Bullet time advances with calls, not elapsed wall-clock time.',[],'danmaku_step();',notes=[msg('step_events','呼び出す前にdm_player_x・dm_player_yへ自機の中心を指定します。移動後の位置で、各軸の距離が3以下なら命中です。dm_invulnerableが0のときdm_hitを1にして弾を消し、無敵なら弾を残します。','Set dm_player_x and dm_player_y to the player center before calling. After movement, distances of at most three pixels on both axes count as a hit. If dm_invulnerable is zero, set dm_hit to one and remove the bullet; invulnerability leaves it alive.'),msg('step_graze','命中範囲外で各軸の距離が11以下なら、弾ごとに1回だけかすりを数えます。dm_hitとdm_grazeは呼び出しの冒頭で0に戻る、その更新回だけの結果です。無敵で命中範囲内にある弾はかすりとして数えません。','Outside the hit box, distances of at most eleven pixels on both axes produce one graze per bullet. dm_hit and dm_graze are reset at entry and describe only this update. A bullet inside the hit box while the player is invulnerable does not count as a graze.'),msg('step_owner','この処理はOAMを書かず、ダメージ処理や効果音のコールバックも呼びません。dm_hit・dm_grazeを読んで、ゲーム側で自機の状態や得点を更新します。','This function neither writes OAM nor calls damage or sound callbacks. Read dm_hit and dm_graze and update player state or scoring in game code.')])
add('draw','弾の中心座標から8×8スプライトを組み立て、指定したシャドーOAM範囲へ書きます。弾の移動や命中判定は行いません。','Build 8×8 sprites from bullet centers and write the requested shadow-OAM range, without moving bullets or testing collisions.',[arg('first_oam','先頭OAMスロット番号（0～63）です。64以上なら書かずに0を返します。サンプルは0を自機用に予約して1から使います。','First OAM slot (0..63). Values of 64 or more return zero without writing. The sample starts at one to reserve slot zero for the player.'),arg('slots','使用できる連続スロット数です。残りの64−first_oam個に制限します。0なら書き込みませんが表示順の巡回位置は進みます。','Number of consecutive available slots, clamped to 64−first_oam. Zero writes nothing but still advances draw priority.'),arg('tile','全弾に使う8×8パターンのタイル番号です。スプライトを8×8モードにして、同じ形の弾に使います。','8×8 pattern tile shared by all bullets. Configure 8×8 sprite mode; this call uses the same shape for every bullet.'),arg('attributes','全弾に使うNESスプライト属性です。下位2ビットはパレット、ビット5は背景の後ろ、6は左右反転、7は上下反転です。','NES sprite attributes shared by all bullets: bits 0–1 palette, bit 5 behind background, bit 6 horizontal flip, bit 7 vertical flip.')],'bullet_result[9]=danmaku_draw(1,24,1,0);',returns=msg('draw_return','実際にOAMへ書いた弾数です。生存弾数と有効なスロット数の小さい方になります。','Return the number of bullets written to OAM: the smaller of the live count and available slots.'),notes=[msg('draw_priority','開始する弾スロットを呼び出しごとに13ずつ、64で折り返して進めます。固定した弾だけが常に優先されることを避けます。指定範囲の未使用スロットはY=240で隠し、範囲外のOAMは保持します。','Advance the starting bullet slot by 13 modulo 64 on each call so fixed bullets do not always get priority. Hide unused slots within the requested range with Y=240, preserving OAM outside that range.'),msg('draw_dma','中心からXは4、OAMのYは5を引き、ハードウェアの表示Y+1を含めて中央を合わせます。DMAは呼び出さないため、VBlankで__oam_dmaを実行してください。1走査線8スプライトというハードウェアの上限は残ります。','Subtract four from center X and five from center Y; the hardware adds one to OAM Y, centering the sprite. Call __oam_dma during VBlank yourself. The hardware limit of eight sprites per scanline still applies.')])
assert len(contracts)==6
data['headers']=sorted(set(data['headers']+['kitaqfc/lib/danmaku.h']));data['records'].sort(key=lambda r:(r['module'],r['name']))
path.write_text(json.dumps(data,ensure_ascii=False,indent=2),encoding='utf-8')
modules={'fc:danmaku':[msg('module','danmakuは64発の固定小数点弾プールです。初期化→発生→stepで移動・判定→drawでOAM作成→VBlankでDMAの順に使います。自機の入力、ダメージ、得点、音はゲーム側で処理します。サンプルは独自に作成したひし形のタイルをCHR RAMへ書きますが、ライブラリ自体はCHR ROMでも使えます。','danmaku is a 64-bullet fixed-point pool. Initialize it, spawn bullets, call step for movement and collisions, call draw to build OAM, then perform DMA in VBlank. Handle player input, damage, scoring and audio in game code. The sample uploads an original diamond tile to CHR RAM; the library itself can also use CHR ROM sprites.')]}
for name,value in [('fc_danmaku_contracts.json',contracts),('fc_danmaku_texts.json',texts),('fc_danmaku_modules.json',modules),('fc_danmaku_review_sources.json',{'source_sha256':{('kitaqfc/lib/'+n):hashlib.sha256((REPOS/'kitaqfc/lib'/n).read_bytes()).hexdigest() for n in ['danmaku.c','danmaku.h']}})]:
    (HERE/name).write_text(json.dumps(value,ensure_ascii=False,indent=2),encoding='utf-8')
print('6 FC danmaku API contracts and library overview added')
