"""Source-reviewed bilingual additions for foreground SFX and pause control."""
def extend(data,msg,texts,void):
    def replace(key,ja,en):texts['fc_audio_vblank_'+key]={'ja':ja,'en':en}
    replace('starvation','待機時間が尽きて次のBGMレコードがなければBGMの音を停止し、補充後のNMIで再開します。独立したSFXは進み続けます。補充不足は空の状態へ移った回数として数えます。HOLDだけを補充しても停止前のBGM音は復元しません。通常は毎フレームrefillを呼び、重い処理の前に十分な待機時間をキューへ入れてください。','When the delay expires without another BGM record, stop the BGM notes and resume at an NMI after data arrives. An independent SFX continues. Count entries into starvation, not every empty frame. Enqueueing only HOLD values does not restore the old BGM notes. Normally refill each frame and queue enough playing time before lengthy work.')
    replace('stop_note','BGMとSFXをともに停止し、キュー、補充元、両方の再生位置、一時停止状態を破棄します。音色と補充不足カウンターは保持し、NMIは無効にしません。位置を保って休止するにはpauseを使います。set_musicとplay_musicも内部でこの停止を行うため、SFXを取り消します。','Stop both BGM and SFX, discarding the queue, feeder, both playback positions and pause state. Retain timbres and the starvation counter; do not disable NMI. Use pause to preserve position. set_music and play_music also perform this stop internally, cancelling SFX.')
    replace('playing_return','BGM消費が有効なら1、停止・終端後は0です。一時停止中や補充不足中も1のままです。SFXだけが鳴っている場合は0です。この値は可聴音やSFXの再生中判定ではありません。','Return 1 while the BGM consumer is enabled, including pause and starvation, or 0 after stop/end. An SFX playing alone still returns 0. This does not report audible output or SFX activity.')
    replace('queued_return','BGMの0～7レコードです。現在の待機時間とSFXレコードは数えません。NMIが消費を進めるため、読み取り時点の値です。','Return 0..7 queued BGM records, excluding the current delay and all SFX records. NMI advances consumption, so the result is a momentary observation.')
    replace('free_return','BGMキューの0～7スロットで、7−queued()です。バイト数ではなく、1スロットに5バイトを格納します。SFXの35バイト領域はこのキューと別です。','Return 0..7 BGM slots, equal to 7−queued(). This is a slot count, with five bytes per slot. The separate 35-byte SFX buffer is not part of this queue.')
    replace('control','パルスは上位2ビットがデューティ（0=12.5%、1=25%、2=50%、3=75%）、下位4ビットが固定音量0～15です。ノイズは通常、下位4ビットが固定音量です。NES_AUDIO_NOISE_ENVELOPE（128）をORすると、下位4ビットは減衰周期0～15になり、次のノイズ音は音量15から一度だけ減衰します。周期が大きいほど遅く、15では約1秒です。ノイズの長さカウンターは減衰が完了する長さに設定します。三角波は0で消音設定、0以外で発音設定です。','For pulses, bits 7..6 select duty (0=12.5%, 1=25%, 2=50%, 3=75%) and bits 3..0 set constant volume 0..15. Noise normally uses bits 3..0 as constant volume. OR in NES_AUDIO_NOISE_ENVELOPE (128) to use those bits as decay period 0..15: the next noise note starts at volume 15 and decays once. Larger periods are slower; 15 takes about one second. The noise length counter allows the decay to finish. Triangle uses zero for a silent next note and nonzero for an audible one.')
    replace('start_note','初期化と補充を先に行ってください。NMI自体は有効にせず、現在の待機時間や読み取り位置も変更しません。一時停止の解除にはpause(0)を使います。startだけでは一時停止を解除しません。','Initialize and enqueue first. This neither enables NMI nor changes the current delay or read position. Resume a paused driver with pause(0); start alone does not unpause it.')
    foreground=msg('foreground','前景処理から呼びます。NMIはコピー済みのSFXデータを使います。別のAPUドライバーを並行して動かさず、BGMとSFXをこのライブラリで管理してください。','Call from the foreground. NMI consumes the copied SFX data. Let this library manage both BGM and SFX; do not run another APU driver concurrently.')
    data['pause']=('BGMとSFXの再生位置を保ったまま両方を休止・再開します。','Pause or resume both BGM and SFX while preserving their playback positions.',[['on',[msg('pause_on','0以外で休止、0で再開です。休止はAPUの4音源を直ちに無効にします。','Nonzero pauses; zero resumes. Pausing immediately disables the four APU channels.')]]],void,[foreground,msg('pause_note','休止中はBGMの待機時間・キュー読取位置とSFXの待機時間・読取位置が進みません。refillによる補充は可能です。再開後の最初のNMIで現在の音を再トリガーして通常の刻みを進めます。波形位相や減衰エンベロープの途中の音量は保存しません。is_playingのBGM有効フラグも変更しません。0は休止中でなくても音の復元を予約するため、毎フレーム呼ぶ用途には使わないでください。','During pause, neither BGM delay/queue position nor SFX delay/position advances. Foreground refill remains possible. The first NMI after resume retriggers the current notes and advances the normal tick. Waveform phase and a partially decayed envelope level are not saved. The BGM enable flag reported by is_playing is unchanged. Zero requests note restoration even when already running, so do not call it every frame.')])
    data['play_sfx']=('短い効果音をRAMへコピーし、選んだ音源の出力を次のNMIから一時的に置き換えます。','Copy a short effect to RAM and temporarily take over selected channel outputs starting at the next NMI.',[
      ['records',[msg('sfx_pointer','5バイトレコード列の先頭。戻るまでcount×5バイトを読み取れるように保持・マッピングします。コピー後は元の配列を再利用できます。','Start of five-byte records. Keep count×5 bytes readable and mapped until the call returns. The source may be reused after the copy.')]],
      ['count',[msg('sfx_count','1～7レコード（最大35バイト）。各待機時間は1～255です。SFXでは待機時間0の終端を使わず、指定個数を再生すると終了します。','1..7 records, at most 35 bytes. Every delay must be 1..255. SFX do not use delay-zero terminators; they end after the specified records.')]],
      ['mask',[msg('sfx_mask','下位4ビットが対象音源です。1=CH1、2=CH2、4=CH3、8=CH4。ORで複数選べます。上位4ビットは無視します。下位が全て0なら拒否します。','Low four bits select channels: 1=CH1, 2=CH2, 4=CH3, 8=CH4. OR bits to select several. High bits are ignored; a zero low mask is rejected.')]]],
      msg('sfx_return','コピーして有効にしたら1。null、範囲外の個数、対象音源なし、待機時間0、不正な音階・ノイズ値なら0です。不正入力では現在のSFXを変更しません。対象外の音源の値も検査します。','Return 1 after copying and enabling the effect. Return 0 for null, an invalid count, no selected channels, a zero delay or invalid tonal/noise values. Invalid input leaves the current effect unchanged. Values on unselected channels are validated too.'),
      [foreground,msg('sfx_note','BGMは背後で進み続け、効果音が終わるとその時点のBGM音へ戻ります。SFXは1本で、新しい呼び出しは前の効果音を置き換えます。HOLD/STOPの値はBGMと共通ですが、SFX開始時の保持音は停止状態なので、最初のHOLDはBGMの音を引き継ぎません。BGMが無効でもSFXは再生できます。一時停止中に予約したSFXは再開まで進みません。音色はBGMと共用です。','BGM keeps advancing underneath; when the effect ends, outputs return to its current notes. There is one SFX stream; a new call replaces it. HOLD/STOP values match BGM, but an effect starts with stopped held notes, so an initial HOLD does not inherit the BGM note. SFX can play without BGM. An effect queued while paused waits for resume. Timbres are shared with BGM.')])
    data['stop_sfx']=('効果音による音源の占有を取り消し、次のNMIで現在のBGM音へ戻します。','Cancel effect ownership so the next NMI restores the current BGM notes.',[],void,[foreground,msg('stop_sfx_note','APUレジスターをこの呼び出しでは書き換えません。BGMのキュー・位置・有効状態は保ちます。SFXだけを鳴らしていた場合は次のNMIで停止状態へ戻ります。一時停止中は再開後に反映されます。音を直ちに止めて両方の位置を破棄するにはstopを使います。','This call does not write APU registers. It retains the BGM queue, position and enabled state. If SFX was playing alone, the next NMI returns the channels to stopped notes. While paused, the change takes effect on resume. Use stop to mute immediately and discard both positions.')])
    hook=data['__hook'];data['__hook']=('NMIでBGMとSFXの待機時間を進め、現在の音源所有権に従ってAPUへ反映するフックです。','NMI hook that advances BGM and SFX delays and updates the APU according to current channel ownership.',*hook[2:])
    return msg('effects_expected','サンプルは操作不要です。CH1の約220HzのBGMに約880HzのSFXを30フレーム重ね、現在のBGMへ戻ります。30フレームの無音の休止後にBGMが再開します。次のSFXは15フレームで明示的に打ち切ります。その後、CH4のノイズが一度だけゆっくり減衰します。画面のCOMPLETE / ALL CHANNELS OFFは全工程の終了を示します。添付音声で高低の切り替え、休止区間、ノイズの減衰を確認してください。','No input is needed. CH1 plays BGM near 220 Hz, switches to an SFX near 880 Hz for 30 frames, then returns to the current BGM. After a 30-frame silent pause, BGM resumes. A second effect is explicitly cut short after 15 frames. Finally, CH4 noise decays slowly once. COMPLETE / ALL CHANNELS OFF marks the end. Listen to the attached recording for the pitch changes, silent pause and noise decay.')
